zellij-org/zellij

- docs/ARCHITECTURE.md
- docs/TERMINOLOGY.md
This will address https://github.com/mosaic-org/mosaic/issues/22
> docs(contributing): explanations about the project arhictecture and some cheat sheet about terminal terminology

- src/terminal_pane/scroll.rs
- src/terminal_pane/terminal_pane.rs
After this, the starship prompt plays rather nicely with pane resizes. For full details see here: https://github.com/mosaic-org/mosaic/issues/36
> fix(compatibility): various issues involving starship

- src/terminal_pane/terminal_character.rs
So, apparently terminals with more than 256 colors are a thing ;P
This addresses https://github.com/mosaic-org/mosaic/issues/87 (I hope)
> fix(compatibility): support rgb color notation

- src/terminal_pane/terminal_character.rs
Sorry for accidentally deleting your changes, @TheLostLambda !
> fix(style): bring the nice match back

- docs/ARCHITECTURE.md
Well, this is too small of a change for a PR, but I was afraid I will forget about it later :)
> fix(docs): teack -> track

- src/boundaries.rs
Brought to you by vim macros :smile:
> fix(style): make match arms consistent

- src/screen.rs
- src/tab.rs
- src/tests/integration/snapshots/mosaic__tests__integration__basic__max_panes-10.snap
- src/tests/integration/snapshots/mosaic__tests__integration__basic__max_panes-11.snap
- src/tests/integration/snapshots/mosaic__tests__integration__basic__max_panes-9.snap
> Refactor terminal to panes

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/wasm_vm.rs
We're on a semi-stable version of wasmer now! This is still very WIP, but should be mergable without any harm (all behind a feature flag).
> Fully Working WebAssembly Loading!

- src/panes/grid.rs
- src/panes/terminal_pane.rs
This addresses the color on resize part of: https://github.com/mosaic-org/mosaic/issues/139
> fix(compatibility): clear characters should preserve current styling

- .github/ISSUE_TEMPLATE/blank_issue.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- CONTRIBUTING.md
- README.md
Ideas of what more should be added are most welcomed :smile: 
The `CHANGELOG` part is for future use as we don't have proper releases at the moment.
> docs: Add initial issue template and CONTRIBUTING.md

- default-tiles/strider/src/main.rs
This adds vim navigation keys to strider
> feat(strider): add vim keys

- default-tiles/strider/src/main.rs
> feat(strider): add vim h key

- src/client/tab.rs
- src/common/input/handler.rs
- src/common/input/keybinds.rs
- src/common/os_input_output.rs
Low hanging Clippy fixes.
I opted to allow the single match in the signal handler for now,
since there is already a todo item, and as soon as the WINCH
feature comes that should handle more than one case probably
anyway.
> Clippy fixes.

- Cargo.lock
- Cargo.toml
- src/client/boundaries.rs
- src/client/panes/plugin_pane.rs
- src/client/tab.rs
- src/common/errors.rs
- src/common/input/handler.rs
- src/common/mod.rs
- src/common/screen.rs
Will leave as draft for now, as there's a little bit more work left on this
> feature: Focused pane border coloring

- src/client/tab.rs
Fixes https://github.com/zellij-org/zellij/issues/208
> fix(tabs): do not crash if closing pane in fullscreen

- src/client/panes/terminal_pane.rs
Closes https://github.com/zellij-org/zellij/issues/43
> fix(compatibility): reset

- src/client/panes/grid.rs
This fixes a bug in htop where it would not delete lines and update over them.
> fix(compatibility): rotate scroll region

- src/client/panes/grid.rs
This fixes some weird overwrites when doing bash reverse search.
> fix(compatibility): bash reverse search

- .github/workflows/rust.yml
- CONTRIBUTING.md
- Cargo.lock
- Cargo.toml
- Makefile.toml
- README.md
- assets/completions/_zellij
- assets/completions/zellij.bash
- assets/completions/zellij.fish
- src/cli.rs
- src/client/layout.rs
- src/common/install.rs
- src/common/mod.rs
- src/main.rs
Just waiting for CI mainly, but I might be about to delete half of the build system
> feat(build): allow arguments to be passed to Zellij

- src/client/panes/grid.rs
This is another fix for htop where we didn't properly react to the `S` CSI.
> fix(compatibility): properly scroll up in scroll region

- src/common/input/keybinds.rs
> fix(keybinding): fix tab mode

- CHANGELOG.md
> Update Changelog #342

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/common/mod.rs
- src/common/wasm_vm.rs
- zellij-tile/Cargo.toml
- zellij-tile/src/data.rs
- zellij-tile/src/shim.rs
Helps address part of #383 
Also cleaned up the plugin code a little bit!
> feat(plugin): added the `get_plugin_ids()` query function

- default-plugins/tab-bar/src/tab.rs
> Fix Tab (Sync) suffix

- CONTRIBUTING.md
Add X11 as a dependency to the docs.
> docs(contributing): Update Dependencies

- src/client/boundaries.rs
Not very complex, but I did something similar a while back and I like having fewer lines of code. :)
> Simplify the boundary logic a little

- README.md
explain debug build command for bug reports
> README: shortening + add explanation

- docs/ARCHITECTURE.md
- src/client/mod.rs
- src/client/panes/plugin_pane.rs
- src/client/panes/terminal_pane.rs
- src/client/tab.rs
- src/common/errors.rs
- src/common/input/actions.rs
- src/common/input/handler.rs
- src/common/mod.rs
- src/common/pty.rs
- src/common/screen.rs
- src/common/thread_bus.rs
- src/common/wasm_vm.rs
- src/main.rs
- src/server/mod.rs
- src/server/route.rs
- src/tests/fakes.rs
> Refactoring sender/receiver stuff - post-merge

- .github/ISSUE_TEMPLATE/bug_report.md
Fold instructions, give copy-paste commands and give example of typical
information density. Refer to common sense of the issue author.
> improve bug report template

- CHANGELOG.md
- src/cli.rs
- src/client/mod.rs
- src/common/input/options.rs
- src/common/screen.rs
- src/server/mod.rs
Merges the cli and file configuration in `options`
> Slight rework of config loading.

- src/server/mod.rs
This PR removes unused stuff.
Lets see what CI tells us about me deleting code :smile:
> Remove unused imports/functions

- src/common/os_input_output.rs
- src/main.rs
> handle error on termios initialization

- Cargo.lock
- default-plugins/status-bar/src/main.rs
- default-plugins/tab-bar/src/line.rs
- default-plugins/tab-bar/src/main.rs
- default-plugins/tab-bar/src/tab.rs
- src/tests/fakes.rs
- src/tests/utils.rs
- zellij-client/Cargo.toml
- zellij-client/src/lib.rs
- zellij-client/src/os_input_output.rs
- zellij-server/src/lib.rs
- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/panes/unit/grid_tests.rs
- zellij-server/src/route.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab.rs
- zellij-utils/src/ipc.rs
This implements most of the OSC methods. And specifically solves some issues where we weren't replying to queries about the terminal background color. This should fix: https://github.com/zellij-org/zellij/issues/320 among other things
> Osc implementation

- CHANGELOG.md
- zellij-utils/src/cli.rs
- zellij-utils/src/setup.rs
* Make distinction clearer between certain
flags
> Change Description of Config Flags

- src/main.rs
- zellij-client/src/lib.rs
- zellij-server/src/lib.rs
- zellij-server/src/route.rs
- zellij-utils/src/ipc.rs
* Attaching a new session now also respects the
default_mode setting of the client
> Add default_mode to attach

- default-plugins/status-bar/src/second_line.rs
- default-plugins/tab-bar/src/line.rs
- zellij-client/src/input_handler.rs
- zellij-client/src/lib.rs
- zellij-server/src/tab.rs
- zellij-server/src/ui/pane_resizer.rs
- zellij-utils/src/consts.rs
- zellij-utils/src/input/config.rs
- zellij-utils/src/input/layout.rs
- zellij-utils/src/input/options.rs
- zellij-utils/src/setup.rs
> chore(clippy): needless_borrow

- CONTRIBUTING.md
I hit this while trying to test the new system, 
are these dependencies correct?
> Add new dependencies to `CONTRIBUTING.md`

- Cargo.toml
- zellij-client/Cargo.toml
- zellij-client/src/lib.rs
- zellij-server/Cargo.toml
- zellij-server/src/lib.rs
- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/pty.rs
- zellij-utils/Cargo.toml
- zellij-utils/src/setup.rs
This PR aims to remove the "test" feature and the little hacks we had for our former testing framework
> Remove test feature and hacks

- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/terminal_character.rs
- zellij-server/src/panes/terminal_pane.rs
#646 introduced a very big performance degradation. This fixes it while still maintaining the compatibility fix.
> fix(performance): undo degredation introduced in 646

- zellij-server/src/panes/alacritty_functions.rs
> eliminate unused imports warnings during compile

- zellij-server/src/screen.rs
> fix(ui): render correctly after tab closing

- zellij-server/src/tab.rs
- zellij-server/src/ui/pane_resizer.rs
> fix(ui): offset content after viewport construction

- zellij-server/src/pty.rs
- zellij-utils/src/input/layout.rs
> feat(screen): support specifying tab's name in layout

- zellij-server/src/ui/pane_boundaries_frame.rs
> fix: don't pad empty pane title

- README.md
Add a doc-shield that links to the documentation to `README.md`.
> Add link to docs to README.md

- src/main.rs
- src/sessions.rs
- zellij-utils/src/cli.rs
Hey!
Addressing #541 to help my automated zellij remote workspace :D
Thanks!
>  Implement `attach --create` subcommand flag to create session if one does not exist

- zellij-server/src/screen.rs
- zellij-server/src/tab.rs
- zellij-tile/src/data.rs
> add visiblity event for plugin

- src/tests/e2e/remote_runner.rs
- zellij-server/src/panes/grid.rs
Fixes https://github.com/zellij-org/zellij/issues/743
> fix(compatibility): scroll lines into scrollback when clearing screen

- Cargo.lock
- src/tests/e2e/cases.rs
- src/tests/e2e/remote_runner.rs
- zellij-client/src/input_handler.rs
- zellij-client/src/lib.rs
- zellij-client/src/os_input_output.rs
- zellij-client/src/unit/input_handler_tests.rs
- zellij-utils/src/errors.rs
Fixes: https://github.com/zellij-org/zellij/issues/749
> hotfix(stdin): poll for mouse hold in the stdin thread

- zellij-utils/assets/config/default.yaml
- add information to configuration directly to the config file
> add(config): add information to the config file

- zellij-server/src/panes/grid.rs
Move cursor to beginning of line after moving it down.
fixes #860.
> fix(compatibility): CSI cursor next line fix

- INSTALL.md
- README.md
- THIRD_PARTY_INSTALL.md
A lot of people love Zellij ❤️  
Currently, people who like zellij are managing it through various `package managers`.
So I've put together the documentation to make it easily accessible to a variety of people.
There is still little content, but I believe this will grow over time.
> doc: add INSTALL.md

- zellij-server/src/screen.rs
- zellij-server/src/tab.rs
* add overlay instructions to the `render` function
this is a continuation of #871
> add(overlay): add overlay

- CONTRIBUTING.md
> fix: Update CONTRIBUTING.md

- zellij-utils/src/input/config.rs
Signed-off-by: Tw <wei.tan@intel.com>
> Fix: missing theme in config

- zellij-utils/assets/config/default.yaml
* update config option examples:
```
no_pane_frames -> pane_frames
no_mouse_mode -> mouse_mode
```
closes #916
> fix(assets): update config option examples

- zellij-client/src/os_input_output.rs
> fix(perf): throttle resizes on sigwinch

- example/layouts/multiple_tabs_layout.yaml
- example/layouts/multiple_tabs_layout_htop_command.yaml
- example/layouts/run_htop_layout_with_plugins.yaml
- test-template.yaml
Updated usage of deprecated plugins.
> chore: update example layout

- THIRD_PARTY_INSTALL.md
Update THIRD_PARTY_INSTALL.md to add installation instructions for Fedora Linux
> Add instructions for Fedora Linux

- zellij-utils/src/input/theme.rs
> fix typo that gives plugins the wrong theme

- zellij-server/src/tab.rs
> fix: left click on tabs when pane is on fullscreen mode

- zellij-server/src/screen.rs
Fixes https://github.com/zellij-org/zellij/issues/988
> fix(tabs): dont panic when tab history is empty and closing tab

- zellij-server/src/tab/pane_grid.rs
This is a bug introduced by the recent tab refactor, so it only affected main for a brief while.
> fix(panes): do not crash when closing fixed pane

- src/tests/fixtures/grid_copy_wrapped
- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/unit/grid_tests.rs
When copying wrapped lines do not treat them as separate lines.
> fix(copy): rejoin wrapped lines

- CONTRIBUTING.md
The verb `consider` is followed by a gerund form verb.
When you want to follow `consider` by to-infinitive verb, you should use it with a pronoun.
> Fix a grammatical error in `CONTRIBUTING.md`

- Cargo.toml
Closes: https://github.com/zellij-org/zellij/issues/1068
> Bump `suggestion` version to the latest

- zellij-server/src/panes/grid.rs
> fix(compatibilty): do not use current cursor style in csi erase display

- flake.nix
* used for snapshotting the e2e tests
> add(nix): add `cargo-insta`

- flake.nix
> fix(nix): add `example` to exclude

- zellij-utils/assets/completions/comp.fish
> fix(comp): typo and add new option

- zellij-server/src/screen.rs
> fix(floating-panes): update tooltip after hiding floating panes with mouse

- .github/workflows/update-flake-lock.yml
> fix(ci): `update-flake-lock`

- README.md
And improve readability / contrast of the other badges.
> add(readme): built-with-nix badge

- default-plugins/status-bar/src/tip/data.rs
> fix(ui): add missing closing >

- Cargo.lock
- zellij-utils/Cargo.toml
> update termwiz to 0.16.0

- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/unit/grid_tests.rs
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__ansi_capital_s.snap
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__ansi_capital_t.snap
This fixes some regressions with ANSI scrolling - tests were added to make sure this does not happen again!
> fix(compatibility): various ansi fixes

- zellij-server/src/tab/mod.rs
> fix(mouse): clicks not forwarded to plugin pane

- zellij-server/src/tab/mod.rs
> fix(mouse): middle or right clicks creating selection

- zellij-server/src/lib.rs
- zellij-server/src/pty_writer.rs
- zellij-utils/src/errors.rs
> fix: ensure pty_writer thread closes

- default-plugins/compact-bar/src/line.rs
Minor UI tweaks to make things stand out a little more.
> feat(ui): minor tweaks to the compact tab bar

- default-plugins/compact-bar/src/line.rs
- default-plugins/compact-bar/src/main.rs
- default-plugins/compact-bar/src/tab.rs
- default-plugins/status-bar/src/first_line.rs
- default-plugins/status-bar/src/main.rs
- default-plugins/tab-bar/src/main.rs
- default-plugins/tab-bar/src/tab.rs
Make simplified UI (in both compact and non-compact layouts) a little clearer and nicer.
> Tweak simplified UI

- .github/workflows/release.yml
resolve #1478 
I tested it in my personal repo(https://github.com/jaeheonji/zellij/releases/tag/v0.18.2).
> ci: add checksum for release binary

- docs/MANPAGE.md
Update manpage for recently added features.
> docs(manpage): update manpage

- zellij-client/src/fake_client.rs
- zellij-server/src/screen.rs
- zellij-utils/src/logging.rs
> fix: various typos

- src/sessions.rs
Found this while browsing the source.
> Refactor match session name

- .github/workflows/nix.yml
- .github/workflows/release.yml
* Fix potential globbing of variables
* Add missing terminating quote
> fix(ci): quoting issues

- example/themes/solarized-light.yaml
I was missing this file so I'm just adding it :)
> Adding solarized-light

- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/tab/mod.rs
> forward OSC52 events

- rust-toolchain.toml
Automatic change by the [update-rust-toolchain](https://github.com/a-kenji/update-rust-toolchain) Github Action.
Github Actions will not run workflows on pull requests which are opened by a GitHub Action.
> rust-toolchain: Update

- zellij-server/src/ui/pane_contents_and_ui.rs
Fixes https://github.com/zellij-org/zellij/issues/1700
As much as it pains me to "fix" this amazing feature...
> fix(ui): sort multiple ui cursors

- zellij-server/src/os_input_output.rs
- zellij-utils/src/input/layout.rs
- zellij-utils/src/kdl/kdl_layout_parser.rs
Fixes https://github.com/zellij-org/zellij/issues/1824, https://github.com/zellij-org/zellij/issues/1823, https://github.com/zellij-org/zellij/issues/1818
And partially https://github.com/zellij-org/zellij/issues/1825
Great work finding these @raphCode !
> fix(layouts): various bugs and better errors

- example/themes/everforest-dark.kdl
- example/themes/everforest-light.kdl
Added `everforest` theme in `example/themes/`
> Add `everforest` theme in theme examples

- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
Fixes https://github.com/zellij-org/zellij/issues/1857
> fix(ui): clear floating panes indication when closing a command pane

- src/main.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-utils/src/cli.rs
- zellij-utils/src/input/actions.rs
Fixes https://github.com/zellij-org/zellij/issues/1856
> fix(edit): treat cwd properly

- src/commands.rs
- zellij-client/src/os_input_output.rs
Fixes https://github.com/zellij-org/zellij/issues/1861
> fix(cli-actions): do not query termios for the cli client

- CONTRIBUTING.md
- docs/ERROR_HANDLING.md
and add more TL;DRs and new sections about handling specific errors, and logging errors.
> docs: Improve error handling docs

- zellij-client/src/input_handler.rs
According to #1922 and #1915  , this pr is mainly to support text input from clipboard. 
Hi @jaeheonji , i'm not sure if my implementation is correct, could you review it?
> Support text input from clipboard

- example/themes/catppuccin.kdl
This PR is from [catppuccin/zellij](https://github.com/catppuccin/zellij).
Related history can be found in the this [PR](https://github.com/catppuccin/zellij/pull/7).
> feat(themes): add catppuccin themes

- zellij-server/src/route.rs
Fixes https://github.com/zellij-org/zellij/issues/1949
> fix(router): handle client empty message

- example/themes/tokyo-night-dark.kdl
> fix(themes): missing tokyo-night-dark theme

- zellij-server/src/panes/grid.rs
Fixes https://github.com/zellij-org/zellij/issues/2164 and https://github.com/zellij-org/zellij/issues/1760
There are two fixes here:
1. When deleting characters with `CSI K` and `CSI J`, we now only take the background color from the pending styles rather than the whole style
2. When we get intermediate characters in a `CSI m`, we ignore the whole CSI (this happens when we get an `esc_dispatch` whose length we're unsure about).
> fix(grid): only use background pending styling when deleting characters

- Cargo.lock
- Cargo.toml
- README.md
- zellij-client/Cargo.toml
- zellij-server/Cargo.toml
- zellij-tile-utils/Cargo.toml
- zellij-tile/Cargo.toml
- zellij-utils/Cargo.toml
This PR includes some README and other minor updates before releasing the version.
> chore(repo): version 0.35.0

- src/commands.rs
Fixes https://github.com/zellij-org/zellij/issues/2232
This was caused by an oversight when fixing another bug. Fixed now!
> fix(sessions): attach --create regression

- zellij-server/src/panes/floating_panes/floating_pane_grid.rs
- zellij-server/src/panes/floating_panes/mod.rs
- zellij-server/src/panes/tiled_panes/mod.rs
- zellij-server/src/panes/tiled_panes/tiled_pane_grid.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/unit/screen_tests.rs
Fixes https://github.com/zellij-org/zellij/issues/2275
> fix(screen): focus pane on screen edge when moving pane focus offtab

- README.md
Since we created the roadmap, quite a few items have already been implemented. This updates the image to reflect that.
> docs(readme): update roadmap image

- README.md
Hi! Thank you for [zellij](https://github.com/zellij-org/zellij)!
Added launch in xonsh.
> Added launch in xonsh

- Cargo.lock
- zellij-server/src/pty.rs
> fix: cwd of newtab action

- default-plugins/status-bar/src/tip/utils.rs
> fix: runtime panic because of local cache

- default-plugins/strider/src/main.rs
- default-plugins/strider/src/search/search_state.rs
Minor UI improvement for the new strider search
> fix(strider): clear search term on ESC

- Cargo.lock
- default-plugins/strider/Cargo.toml
- default-plugins/strider/src/search/mod.rs
- zellij-server/src/plugins/watch_filesystem.rs
This adds a smart ignore to the Strider search (eg. respect .gitignore and do not traverse hidden files)
> feat(plugins): strider improvements

- zellij-tile/src/lib.rs
Document the API so that it would look nice on docs.rs
> docs(plugins): better zellij-tile-docs

- Cargo.lock
- zellij-utils/Cargo.toml
- zellij-utils/src/consts.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/setup.rs
fix #2565 
and fixed theme file not being embedded in binary
> hotfix: include theme files into binary

- zellij-utils/src/session_serialization.rs
Fixes a few edge cases when serializing sessions with stacked panes
> fix(resurrection): properly serialize certain edge cases

- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/pty.rs
- zellij-server/src/tab/mod.rs
Fixes #2910 
First contribution, please let me know if I can make it better somehow (even with the conventional commits, or whatever else). I tested it locally and it seems to work correctly, and the changes are pretty uncontroversial IMO
> Dropping to shell in command panes reuses CWD

- zellij-server/src/background_jobs.rs
Fixes https://github.com/zellij-org/zellij/issues/2946
This separates the session read interval from the session serialization interval. I tied the two of these together by mistake. This caused sessions to take a long time (by default 1 minute) to update in the session manager.
> fix(sessions): untie serialization interval from session read interval

- zellij-server/src/panes/grid.rs
Recover from various crashes in our ANSI parser.
Fixes https://github.com/zellij-org/zellij/issues/2867 and https://github.com/zellij-org/zellij/issues/2860 (as well as some others).
> fix(grid): various crashes

- zellij-server/src/panes/grid.rs
This implements the Terminal Synchronized renders protocol as described here: https://gist.github.com/christianparpart/d8a62cc1ab659194337d73e399004036
Fixes https://github.com/zellij-org/zellij/issues/2828 (among other things)
> feat(terminal): implement synchronized renders

- zellij-server/src/plugins/plugin_loader.rs
Fixes https://github.com/zellij-org/zellij/issues/3099
This was happening because we weren't checking to make sure the host folder of plugins still exists after attaching a session.
> fix(plugins): crash when reattaching to a non-existent host folder

- zellij-server/src/panes/tiled_panes/mod.rs
Fixes https://github.com/zellij-org/zellij/issues/3150
> fix(panes): no-op on unset fullscreen when no clients are connected

- zellij-server/src/lib.rs
Fixes https://github.com/zellij-org/zellij/issues/2924
What was happening here:
1. The Zellij client was overflowing, not keeping up with the server (likely a temporary resource utilization issue)
2. The server client channel buffer filled up and so the client was disconnected
3. In certain cases where this happens while looping through the connected clients in the `SessionState`, there was a deadlock: on the one hand, the `SessionState` was locked for reading the client_ids, but the recovery (disconnecting the client) requires writing to the `SessionState` - and so the server got stuck.
I fixed this by getting a list of client_ids and looping through it instead. This specific occasion happened in `UnblockInputThread`, but I found some other potential offenders and fixed them as well.
> fix(router): deadlock when unblocking input thread

- README.md
added missing section to clarify the origin of the project name.
> add name section in readme

- zellij-utils/assets/themes/atelier.kdl
from: https://github.com/atelierbram/atelier-schemes-terminal
> feat(themes): add atelier sulphurpool theme

- zellij-utils/assets/themes/night-owl.kdl
Add new theme port of Night Owl.
> Add night-owl theme

- funding.json
I decided to add a funding.json file in order to apply for an OSS grant to to help me pay my bills. I'm unsure if anything will come of it - so if nothing does, I'll remove this file in a few months.
> chore(repo): add funding.json

- zellij-server/src/panes/floating_panes/floating_pane_grid.rs
- zellij-server/src/panes/floating_panes/mod.rs
- zellij-server/src/tab/layout_applier.rs
- zellij-server/src/tab/mod.rs
This handles various previously uncaught errors around floating panes.
> fix(floating-panes): handle uncaught errors

- zellij-utils/assets/themes/gruber-darker.kdl
Based on gruber-darker theme colors from github.com/rexim/gruber-darker-theme/
> Add gruber-darker theme

- zellij-client/assets/input.js
- zellij-client/assets/utils.js
Similar to #4291 but for paste with `cmd+v` on Mac.
> fix(web): allow pasting with cmd-v

- default-plugins/about/src/pages.rs
This adds in-app release notes for the upcoming 0.43.0 release (next week!)
> docs(about): release notes for version 0.43.0

- .github/workflows/release.yml
- xtask/src/ci.rs
- xtask/src/flags.rs
This fixes passing the `--no-web` flag to the cross compilation flow and some other minor issues.
> fix(ci): make cross compilation work with the no-web variant
