zellij-org/zellij

- src/main.rs
- src/screen.rs
- src/terminal_pane/scroll.rs
- src/terminal_pane/terminal_pane.rs
- src/tests/integration/basic.rs
- src/tests/integration/snapshots/mosaic__tests__integration__compatibility__run_bandwhich_from_fish_shell-2.snap
- src/tests/integration/snapshots/mosaic__tests__integration__compatibility__run_bandwhich_from_fish_shell.snap
- src/tests/utils.rs
I originally set out to fix a bug where if you'd expand a vim pane to fullscreen, the pane would only expand vertically and not horizontally (the same amount of lines would stay on screen).
Turns out this was caused (surprisingly enough) because we weren't properly reacting to the cursor show/hide CSI instructions.
Why? Vim uses the terminal scrolling region (as described here: https://vt100.net/docs/vt102-ug/chapter5.html). Apparently, when the cursor is hidden, the scroll region should be ignored (because the cursor is not between the first and last line of the scroll region - it is nowhere). Now it works, AND we support hiding the cursor.
> fix(scroll): support show/hide cursor and fix vim scrolling behaviour

- src/main.rs
- src/os_input_output.rs
- src/screen.rs
* Arrow keys now work as expected.
* Ctrl-c now works as expected.
* ESC now works as expected
(maybe some other stuff that I wasn't aware of should also start working)
Instead of reading one byte from stdin, we now read 10. It's a little arbitrary, but I guess should work for most (all?) cases. A better way to go about it would be to detect how many bytes we read and match against that, but it's really not critical for the moment.
> fix(compatibility): better stdin reading to fix various issues

- README.md
- src/main.rs
- src/screen.rs
- src/tests/fakes.rs
- src/tests/integration/basic.rs
- src/tests/integration/close_pane.rs
- src/tests/integration/compatibility.rs
- src/tests/integration/resize_down.rs
- src/tests/integration/resize_left.rs
- src/tests/integration/resize_right.rs
- src/tests/integration/resize_up.rs
- src/tests/possible_tty_inputs.rs
- src/tests/utils.rs
* change scroll shortcuts to ctrl-pgup and ctrl-pgdown because ctrl-[ and ctrl-] were colliding with esc.
* do not send trailing zeros to terminal because it was messing things up
* fix test infrastructure to be able to support characters with more than one byte (eg. ctrl-pgup and ctrl-pgdown). This also introduces some much needed refactoring and clarity to the tests.
> fix(compatibility): do not interpret esc as scroll-up

- src/terminal_pane/scroll.rs
- src/terminal_pane/terminal_pane.rs
This happened because apparently a carriage return should go to the beginning of a line-wrap and not a canonical line. Starship is depending on this behaviour for a multi-line prompt.
> fix(compatibility): do not break starship multiline prompt

- src/terminal_pane/terminal_character.rs
This addresses https://github.com/mosaic-org/mosaic/issues/15
What caused this issue was that apparently one is able to set the font color using the bold code. As in, while `[1m` is "set to bold", `[1;32m` is "set to red bold". But the bold reset code `[22m` (that which I initially thought would reset whatever one places in `[1m`) only resets the bold and not the red.
Because of that assumption of mine, in the case of starship we were only sending the reset code for bold and thus the color stayed red when it wasn't supposed to.
To solve this, when we decide which styles to send to a new character (we do this by diffing the styles with the previous character, because styles stick around until they are reset), if the new character is a full reset, we send a full reset rather than bothering …
> fix(colors): send full style reset in diff

- src/main.rs
- src/os_input_output.rs
- src/tests/fakes.rs
This was happening for two reasons:
1. We set the attributes of each terminal we opened to match those of the current "main" terminal. This meant that once we entered raw mode (no echo, get input character by character, etc.) for the main terminal, we also set it for each pane we opened.
2. We didn't unset raw mode when we exited
This was fixed by keeping the original termios object that holds all the terminal attribute before we change anything, and using it to set all the terminals. (And also, restoring it once we exit)
> fix(ux): properly echo characters and do not mess up exit

- src/pty_bus.rs
This change means that the asynchronous events we get from listening to the pty are allowed to fail. The only time they fail is if the pty_bus thread is dead, in which case the app is either exiting or has crashed anyway. The former happens sometimes in our tests, which makes the CI fail. This should (hopefully) fix that.
> fix(atomicity): allow async vte events sending to fail

- Cargo.toml
- src/main.rs
- src/pty_bus.rs
- src/screen.rs
- src/utils/logging.rs
This is a bit a variety PR, but it brings build times down from 53 to 23 seconds (less than half the time) and gets rid of nearly all of the compiler warnings.
Oh, also fixes a race condition with pty_bus and layouts!
> Fix a race condition, build-times, and warnings

- Cargo.lock
- Cargo.toml
- src/errors.rs
- src/input.rs
- src/main.rs
- src/screen.rs
- src/terminal_pane/scroll.rs
- src/tests/fakes.rs
- src/tests/integration/layouts.rs
- src/tests/integration/resize_down.rs
feat: print backtrace on panic and ensure proper shutdown.
The implementation works as follows- a custom panic hook collects the backtrace, sends it over to the ipc_thread via socket. The ipc_thread unsets `raw_mode` and prints the backtrace and sends a message to the main thread which joins the active threads and exits.
`Sender<AppInstruction>` does not implement `Sync` and thus could not be captured by the closure in `panic::set_hook()`. We, therefore, have to go through `ipc_thread` for signalling the main thread.
> Add custom panic hook. Print backtrace and thread, error info on panic.

- src/screen.rs
- src/terminal_pane/terminal_pane.rs
This fix adds support for "keyboard transmit". The terminal event `DECCKM` switches it on and off. This essentially means that the arrow keys should transmit their ansi movement codes instead of the arrow key codes themselves.
Some terminals support this and some do not, as indicated *I think* by their terminfo. This is read by the application running inside the terminal, which then decides whether to send this event or not. So we just need to react to the event and transmit the proper codes accordingly - which is what this PR does.
For more information: https://vt100.net/docs/vt100-ug/chapter3.html#T3-6
> fix(compatibility): keypad arrow fixes

- src/terminal_pane/scroll.rs
- src/terminal_pane/terminal_pane.rs
- src/tests/integration/snapshots/mosaic__tests__integration__compatibility__htop_scrolling.snap
- src/utils/logging.rs
This fixes a bug where when we had a scroll region (eg. in vim, htop, etc.) the first line was offset by 1 in certain cases.
> fix(compatibility): do not offset first scroll region line

- src/terminal_pane/scroll.rs
Before this PR, when saving a file in vim, the confirmation message that appeared on the bottom of the screen (when the file has been modified since opening it) would offset the screen and mess it up. No longer!
> fix(compatibility): vim offset issues

- src/terminal_pane/scroll.rs
- src/terminal_pane/terminal_pane.rs
This fixes an issue where neovim did not scroll up/down properly (it deleted the whole screen).
This happened because we previously treated clearing the scroll region as deleting all of it (in order to re-create the vim/htop/etc. behaviour of returning to the previous terminal state when exiting the app). This apparently happens in a different signal (mode setting with CSI l/h). Moved it there and it fixed this bug (as well as keeping the behaviour of clearing the terminal buffer when exiting vim/htop).
> fix(compatibility): fix neovim scrolling

- src/panes/grid.rs
- src/panes/terminal_pane.rs
This fixes the second half of: https://github.com/mosaic-org/mosaic/issues/139
Namely:
Entering neovim, increasing the size of the pane to the left and then exiting.
The issue was that when we resized the alternative grid (the one we stored once we entered neovim) we were dropping an empty line, so when we came back, the cursor overrode it and so a part of it was still left that the cursor did not delete.
> fix(compatibility): don't drop empty lines when resizing

- src/panes/grid.rs
This bug happened when we resized a pane with a scrolling region (eg. vim) in certain edge cases.
It happened because we were adding a linewrap instead of a line when when scrolling inside of a scroll region. This created a cascade that messed up the state and caused problems. No longer!
> fix(compatibility): fix grid glitch edge-case when resizing

- src/main.rs
- src/screen.rs
There are two fixes here:
1. As per @TheLostLambda's request, we now have a more predictable close order for the threads. Waiting for one to close before closing the other in main.
2. Before, in the render method when we had no tabs left, we would send a quit message to the app. This caused a deadlock when we got a render instruction from the pty (eg. when there was some data left in its buffer) while quitting. To fix this, I moved this logic to the `close_tab` method, and then in the render method if there's no active tab it becomes a no-op.
> fix(main): do not hang on exit

- src/panes/grid.rs
- src/panes/terminal_pane.rs
This is an additional fix for: https://github.com/mosaic-org/mosaic/issues/115
The issue was as follows:
When vim/nvim is opened, it switches the terminal display to a new buffer. When it exits, it tells the terminal emulator to restore the display to the previous buffer. This issue happened when the previous buffer had tab characters.
What was happening is that we were forwarding the tab character to the terminal emulator, who then skipped to the next tab stop in the line, not clearing the styles beneath it (from the previous buffer we just cleared). And that's why we had some leftover styles from the buffer.
To fix this, I introduced a `clear_viewport_before_rendering` flag to the terminal pane, to be set when we switch buffers (grids for us). When that flag is set, the render function …
> fix(compatibility): properly erase previous state before switching grids

- Cargo.toml
Add metadata to `Cargo.toml`, which is required by `cargo-deb` to build the deb package.
> feat(metadata): Add metadata to Cargo.toml for building deb packages

- build.rs
Before this, assets were only copied to the plugins folder when the `--release` flag was set. This fixes it.
> fix(build): copy assets also without --release

- .gitignore
- src/client/panes/terminal_pane.rs
- src/client/tab.rs
- src/common/errors.rs
- src/common/input/actions.rs
- src/common/input/handler.rs
- src/common/input/keybinds.rs
- src/common/input/mod.rs
- src/common/ipc.rs
- src/common/mod.rs
- src/common/os_input_output.rs
- src/common/pty_bus.rs
- src/common/screen.rs
- src/common/utils/consts.rs
- src/common/utils/logging.rs
- src/common/utils/mod.rs
- src/common/utils/shared.rs
Adding some documentation wherever I felt confident enough to do so in a clear and concise manner.
Mostly just added documentation (`///`) comments throughout the project. These comments aren't limited to public items, as the documentation is meant for developers. `cargo doc` should therefore be passed the `--document-private-items` flag.
I have also reworked some (not many) of the `use` directives, as I think we should try to not `use` functions from external crates directly, but rather `use` the module they live in, as to not confuse them with locally-defined functions (true of `struct`s to a certain extent as well, see the official Rust book's [comment on idiomatic `use` paths](https://doc.rust-lang.org/stable/book/ch07-04-bringing-paths-into-scope-with-the-use-keyword.html#creating-idi …
> First documentation step

- src/client/tab.rs
This is done by hiding the cursor before rendering and bringing it back afterwards.
> fix(ux): hide cursor while rendering to prevent it from flickering around

- rust-toolchain.toml
- src/client/tab.rs
- src/common/input/actions.rs
- src/common/input/handler.rs
- src/common/input/keybinds.rs
closes #184
Added the NoOp from:
https://github.com/zellij-org/zellij/issues/184
Now text is only written in normal Mode.
> Input normal mode

- src/client/panes/grid.rs
- src/client/panes/terminal_pane.rs
This is a fix for https://github.com/zellij-org/zellij/issues/201
The issue was that when creating a new line inside a terminal pane, we did not pad characters with the current style as is the expected behaviour of terminal emulators. Now we do :)
> Fix vim background color

- src/client/panes/grid.rs
This happened in certain edge cases where we would reflow lines in a pane and try to pull more lines from the top buffer than it had.
> fix(grid): do not crash when reflowing lines with an empty top buffer

- build-all.sh
When the user has `CARGO_TARGET_DIR` set, it messes up the build system. This PR fixes it.
> fix(build): This is getting uglier :/

- assets/layouts/default.yaml
- default-tiles/status-bar/src/main.rs
- default-tiles/tab-bar/src/line.rs
- default-tiles/tab-bar/src/main.rs
- default-tiles/tab-bar/src/tab.rs
- src/client/layout.rs
- src/client/tab.rs
- src/common/errors.rs
- src/common/input/actions.rs
- src/common/input/handler.rs
- src/common/input/keybinds.rs
- src/common/mod.rs
- src/common/screen.rs
- src/common/wasm_vm.rs
- zellij-tile/src/lib.rs
- zellij-tile/src/shim.rs
#166 
Ctrl-G/t/r to rename the active tab.
This is a fairly moderate change as I needed a way to selectively funnel input streams to a specific plugin. I got the idea that the  `PluginInstruction::Input` needs to be divided into two cases:
1. the input needs to be forwarded to the active pane, which happens to be a plugin, identified by pid (existing case)
2. the input needs to be forwarded to one or more plugins, based on whether or not they are interested in that information
I implemented this by adding  `events` to the layout. When an input comes in that is destined for a plugin (decided based on the InputMode) it is forwarded to the plugin:
In layout.yml:
```
parts:
- direction: Vertical
split_size:
Fixed: 1
plugin: tab-bar
events:
- Tab
```
When a tab loads a plugin it now sends the …
> Add ability to set tab name

- src/client/panes/terminal_pane.rs
This fixes a performance bottleneck that we had when rendering terminals. It reduces the size and amount of allocations performed when converting the state of the terminal panes to stringified ANSI. For me this improves the app's performance significantly.
> fix(performance): smaller allocations when rendering

- default-tiles/tab-bar/src/main.rs
- src/common/screen.rs
handle delete and backspace keys when renaming tab.
closes #221
> delete characters when renaming tab

- src/client/panes/terminal_pane.rs
- src/client/tab.rs
- src/tests/fakes.rs
- src/tests/integration/expansion_boundary.rs
- src/tests/integration/resize_down.rs
- src/tests/integration/resize_left.rs
- src/tests/integration/resize_right.rs
- src/tests/integration/resize_up.rs
- src/tests/utils.rs
Previously we re-rendered every pane upon any change to any pane.
Now we only re-render those panes which changed.
This change additionally reduces some unneeded renders (eg. when resizing - we rely on the panes updating themselves when we send them a SIGWINCH instead). For this reason the tests had to be adjusted to add some sleeps (otherwise there would not be enough time to wait until the panes are updated and the resize would not be rendered).
> Performance: only render panes that should be updated

- src/client/panes/terminal_pane.rs
This makes terminal panes always render themselves when there's a re-render. Not ideal for performance, but in order to bring back their conditional rendering we have to solve several other bugs.
> fix(render): various rendering issues

- src/common/input/handler.rs
Remove `unimplemented!` macro for mouse and unsupported events,
essentialy mimicking the NoOp.
Should not crash anymore when handling mouse events.
Alternatives:
Keep the `unimplemented!` macro for `termion::event::Event::Unsupported` ?
closes #243
> Fix(Mouse): Remove unimplemented! Macro for Mouse

- default-tiles/strider/src/main.rs
Adds a guard to check if the directory is empty before
trying to descend into it.
Eg:
Doesn't error anymore, if inside ./git/branches directory
and pressing `l`.
> Fix(strider): Ignore descending into empty dir

- src/client/tab.rs
Closes https://github.com/zellij-org/zellij/issues/251
Closes https://github.com/zellij-org/zellij/issues/217
> fix(tabs): do not resize title bar when closing pane under it

- src/client/panes/terminal_pane.rs
When we move the cursor inside a terminal pane to a location with no previous character, we pad characters up until that position with an empty character. Previously, we would keep the current styles for the padding (similar behaviour is true in other examples, eg. when deleting characters up to a position). This isn't the right behaviour - those pad characters should have no special styling (reset style). This PR fixes this.
An example place where this has effect is in htop (the line under the selected line previously had some extra background characters that looked weird).
> fix(terminal): reset styles on cursor movement

- src/common/command_is_executing.rs
- src/common/os_input_output.rs
This bug happened when we opened lots of new panes very quickly and there was no room for the last new pane. The app would try to kill the new pty that was opened, but would hang waiting for it - thus causing the whole app to be stuck.
I fixed this by sending a `SIGKILL` instead of  `SIGINT` to the pty (essentially the equivalent of doing `kill -9` instead of just `kill`). This is not an ideal solution (as mentioned in the comment I left) but solves the problem for now. A better and more involved solution is suggested in the comment for a future iteration.
> fix(terminal): do not hang app if terminal refuses to quit

- src/client/tab.rs
- src/common/mod.rs
If an event happens in a pane and no one is there to see it, does it update its state?
> fix(screen): handle events directed at other tabs

- src/client/tab.rs
Before this, the fullscreen would be toggled even if there were no other panes. Which would force one to untoggle it in certain situations. (eg. when moving to other panes outside the expansion boundary).
> fix(tabs): do not toggle fullscreen if there are no other panes

- src/client/panes/plugin_pane.rs
- src/client/panes/terminal_pane.rs
- src/client/tab.rs
- src/common/errors.rs
- src/common/mod.rs
- src/common/pty_bus.rs
- src/common/screen.rs
- src/main.rs
Up until this PR, we would parse bytes coming from the pty and then send them as events to the screen thread. In order to do that we had to create a needlessly complex structure `VteEvent` so that these events would make sense and be serializable.
Now, instead of doing that, we transfer the bytes in one big vector and parse them on the Screen side. This dramatically improves performance, especially with large amounts of data.
> fix(performance): remove unnecessary allocations from pty

- src/common/errors.rs
- src/common/input/handler.rs
- src/common/mod.rs
- src/common/pty_bus.rs
Senders no longer store a copy of error context so the `SenderWithContext::update()` has been removed. When calling `sender.send()`, the sender automatically sends the task_local `ASYNCOPENCALLS` or the thread_local `OPENCALLS` to the receiver. Also, senders no longer have to be mutable.
> Make error model more autonomous

- default-tiles/status-bar/src/second_line.rs
This removes the black background from the shortcuts menu in the status bar, instead using the terminal default background.
> fix(status-line): remove black background from shortcuts

- src/common/mod.rs
Makes it easy and flexible to check
whether zellij is already running.
This carries no further information
for now and is initialised to `0`.
closes 304.
> Add ZELLIJ Environment Varable on startup(#304)

- .github/workflows/release.yml
This fixes the GitHub Actions workflow of #279.
Each job in a GitHub Actions workflow runs in a fresh instance of the virtual environment and does not share artifacts with previous jobs by default. You need to use [`actions/upload-artifact`] to share artifacts between jobs.
[`actions/upload-artifact`]: <https://github.com/actions/upload-artifact>
> fix(ci): use `actions/upload-artifact` action (#279)

- src/client/panes/grid.rs
This is a quickfix for https://github.com/zellij-org/zellij/issues/288
It likely happens due to a corrupted terminal state. We don't need to crash because of it, just silently not perform the CSI action.
> fix(stability): do not clear line if it's not there

- src/client/tab.rs
- src/tests/integration/resize_down.rs
- src/tests/integration/resize_up.rs
- src/tests/integration/snapshots/zellij__tests__integration__resize_down__cannot_resize_down_when_pane_below_is_at_minimum_height.snap
- src/tests/integration/snapshots/zellij__tests__integration__resize_down__resize_down_with_panes_above_and_below.snap
- src/tests/integration/snapshots/zellij__tests__integration__resize_up__cannot_resize_up_when_pane_above_is_at_minimum_height.snap
This is a fix for: https://github.com/zellij-org/zellij/issues/292
When opening a new pane we were trying to split the status bar, which we probably shouldn't.
> fix(ui): do not open new pane on the status bar

- Cargo.toml
Here is my call to action :D: 
On top of that I verified that `cargo package` is still able to build,
adjusting the includes in the process to assure required assets are
packaged, too.
I am happy to adjust the includes to your liking so we find a way to reduce the overall crate size.
> Reduce crate size by 4.8MB using `cargo diet`, to 77kB

- src/client/layout.rs
- src/client/panes/plugin_pane.rs
- src/client/panes/terminal_pane.rs
- src/client/tab.rs
- src/tests/integration/basic.rs
- src/tests/integration/close_pane.rs
- src/tests/integration/compatibility.rs
- src/tests/integration/layouts.rs
- src/tests/integration/move_focus_down.rs
- src/tests/integration/move_focus_left.rs
- src/tests/integration/move_focus_right.rs
- src/tests/integration/move_focus_up.rs
- src/tests/integration/resize_down.rs
- src/tests/integration/resize_left.rs
- src/tests/integration/resize_right.rs
- src/tests/integration/resize_up.rs
- src/tests/integration/tabs.rs
- src/tests/integration/terminal_window_resize.rs
- src/tests/integration/toggle_fullscreen.rs
This is a fix for https://github.com/zellij-org/zellij/issues/301 and https://github.com/zellij-org/zellij/issues/303
The problem was:
For some reason, if invoked as the default command in a terminal, when Zellij requests the terminal size from the OS it gets a wrong window size. Very shortly afterwards, the OS sends a SIGWINCH and then Zellij gets the correct window size.
In this scenario, we had a bug where plugins (in this case, the tab bar) would only set their "max_height" limitation (which is supposed to prevent this issue from happening) *after* the layout has already been arranged (and in most cases, the initial correct SIGWINCH received).
This fixes the issue by having the `Fixed` attribute in the layout do the same as `set_max_height`/`set_max_width` in the plugin API. This is …
> fix(ui): draw ui properly on terminal start

- src/client/panes/plugin_pane.rs
- src/client/panes/terminal_pane.rs
- src/client/tab.rs
- src/tests/integration/move_focus_down.rs
- src/tests/integration/move_focus_left.rs
- src/tests/integration/move_focus_right.rs
- src/tests/integration/move_focus_up.rs
- src/tests/integration/snapshots/zellij__tests__integration__move_focus_down__move_focus_down_to_the_largest_overlap.snap
- src/tests/integration/snapshots/zellij__tests__integration__move_focus_down__move_focus_down_to_the_most_recently_used_pane.snap
- src/tests/integration/snapshots/zellij__tests__integration__move_focus_left__move_focus_left_to_the_largest_overlap.snap
- src/tests/integration/snapshots/zellij__tests__integration__move_focus_left__move_focus_left_to_the_most_recently_used_pane.snap
- src/tests/integration/snapshots/zellij__tests__integration__move_focus_right__move_focus_right_to_the_largest_overlap.snap
- src/tests/integration/snapshots/zellij__tests__integration__move_focus_right__move_focus_right_to_the_most_recently_used_pane.snap
- src/tests/integration/snapshots/zellij__tests__integration__move_focus_up__move_focus_up_to_the_largest_overlap.snap
- src/tests/integration/snapshots/zellij__tests__integration__move_focus_up__move_focus_up_to_the_most_recently_used_pane.snap
Using last activity time to determine which pane was previously active when moving back to a direction.
Closes #230
> Adding field active_at and using it to sort panes

- rust-toolchain
Rustfmt doesn't build on current nightly.
Please check out the toolchain before merge! `rustup update`, should do it I think.
I consume this file a little differently. 
Also if it takes a while to merge, check if the pin is still necessary. It shouldn't be a big fix for rustfmt.
> Pin to nightly 2021-04-23

- .github/workflows/release.yml
This adds `aarch64-apple-darwin` (Apple Silicon macOS) target support to #279.
I don't have an Apple Silicon Mac and didn't verify that the binary actually works, but it at least compiles fine.
Cc @qballer.
> feat(ci): build release binary for `aarch64-apple-darwin` (#279)

- CHANGELOG.md
- src/common/mod.rs
- src/common/wasm_vm.rs
- zellij-tile/src/data.rs
- zellij-tile/src/shim.rs
This plugin:
```rust
impl ZellijPlugin for State {
fn load(&mut self) {
subscribe(&[EventType::Timer]);
set_timeout(1.0);
}
fn update(&mut self, event: Event) {
if let Event::Timer(secs) = event {
dbg!(secs);
set_timeout(secs * 2.0);
}
}
}
```
Outputs:
```
[default-plugins/strider/src/main.rs:18] secs = 1.000064727
[default-plugins/strider/src/main.rs:18] secs = 2.000187283
[default-plugins/strider/src/main.rs:18] secs = 4.000435719
[default-plugins/strider/src/main.rs:18] secs = 8.000938307
[default-plugins/strider/src/main.rs:18] secs = 16.001934982
```
> feat(plugin): simple timers implemented via the `set_timeout()` call

- src/common/input/handler.rs
I believe this is a trivial change, so I created a PR directly.
Because `handle_key` can refer to `self.config.keybinds` by itself, it doesn't have to receive the third argument. Also, this change may slightly improve the performance as it deletes `clone()`.
By the way, I love zellij and started to use it on my laptop.
Thanks,
> refactor(handler): refer to self.config.keybinds internally

- src/client/layout.rs
- src/common/mod.rs
Doesn't try loading `default` files, other than
the plugin directory by default anymore.
I think we need to separate the `layout` flag
into `layout` and `layout-path` in the future.
Where `layout` looks at all known plugin directories,
and `layout-path` looks at the specific path.
Adresses  #322.
> Fix Startup with Default in Same Folder

- Cargo.lock
- Cargo.toml
- src/common/input/config.rs
- src/common/mod.rs
- src/main.rs
- src/tests/integration/basic.rs
- src/tests/integration/close_pane.rs
- src/tests/integration/compatibility.rs
- src/tests/integration/layouts.rs
- src/tests/integration/move_focus_down.rs
- src/tests/integration/move_focus_left.rs
- src/tests/integration/move_focus_right.rs
- src/tests/integration/move_focus_up.rs
- src/tests/integration/resize_down.rs
- src/tests/integration/resize_left.rs
- src/tests/integration/resize_right.rs
- src/tests/integration/resize_up.rs
- src/tests/integration/tabs.rs
- src/tests/integration/terminal_window_resize.rs
- src/tests/integration/toggle_fullscreen.rs
Close #414
Previously, a config file was loaded within `start()`, and if the config file is invalid, Zellij was supposed to show a user what's wrong with it. However, since `start()` starts setting up its terminal with an alternative screen buffer, neither standard output nor standard error could display such an error.
This change intends to address this issue by making Zellij load a config file before `start()`.
In addition, the patch also includes some refactorings:
* Redefine `from_cli_config` with `TryFrom`, which was introduced in Rust 1.34
* Remove conditional declaration `cfg(not(test))` because `start()` now receive a `Config` as the third argument
* Introduce [`tempfile`](https://crates.io/crates/tempfile) in order to run tests with actual files
* Typo?: "Deserialisation" -> …
> Load config before start()

- CHANGELOG.md
- src/common/input/config.rs
- src/common/mod.rs
- src/common/setup.rs
- src/main.rs
* Renaming of the install module to convey the intent more,
move functions that install to a sub module install of setup.
* Fix a clippy lint.
> Rename install -> setup

- src/common/input/config.rs
For now, it fails if there is a local config, differing
from the default config.
There needs to be a split again, I think between normal runs and test runs.
> Disable Default Config Test

- src/common/input/config.rs
- src/common/setup.rs
The split of test/no_test happens now in
find_default_config_dir, it always returns Null in tests.
That way differing configurations of zellij shouldn't
make the test fail anymore.
> Enables the Default Config Test

- src/common/os_input_output.rs
- src/common/utils/shared.rs
Attempt at fixing  #434.
The `hex_to_rgb` function propagates the Option now.
If it is None, it tries to load the default Palette in most cases.
> Make Xrdb Loading More Forgiving

- Cargo.lock
- Cargo.toml
- default-plugins/status-bar/src/first_line.rs
- default-plugins/status-bar/src/main.rs
- default-plugins/status-bar/src/second_line.rs
- default-plugins/tab-bar/src/line.rs
- default-plugins/tab-bar/src/main.rs
- default-plugins/tab-bar/src/tab.rs
- src/client/boundaries.rs
- src/common/os_input_output.rs
- src/common/utils/shared.rs
- src/tests/fakes.rs
- zellij-tile-extra/src/lib.rs
- zellij-tile/src/data.rs
This includes various fixes to the new coloring system:
1. Support 8bit terminals - this is done by having the default palette being 8bit
2. Do not crash on boxes without an x11 system (this was unfortunately done by removing the automatic xrdb reading - we can find a way to re-add it later)
3. Fix the colors in the interface (the colors of some elements were wrong)
4. Fix the interface breaking in smaller sizes (the lengths and coloring of the more/less messages in the tabs and the single-letter ctrl shortcuts on the status bar were wrong and made them seem broken).
> fix(colors): stabilize colors

- CHANGELOG.md
- src/common/input/handler.rs
Since termion has issues identifying certain key sequences (eg. ctrl+left arrow), this change forwards all such keys to the active terminal. This is a bit of a hack until we find a solution for this (sot hat we could also bind those keys for example).
> fix(input): forward unknown keys to active terminal

- src/cli.rs
- src/common/input/config.rs
- src/common/setup.rs
- src/common/utils/consts.rs
- src/main.rs
* The check option communicates default and config options to the user
as well as optional compile time features
* Move generate-completion from a subcommand to a flag in the setup
subcommand
> Add `check` flag to the setup subcommand

- Cargo.toml
- src/common/utils/consts.rs
- src/server/mod.rs
* changed `enable_automatic_asset_installation` to
`disable_automatic_asset_installation`
This ensures that people by default get the
asset installation and need to opt out at
compile time, rather than opt in.
* removed default features
Not needed anymore.
> Invert Assets Installation Feature

- CHANGELOG.md
- src/main.rs
- zellij-utils/src/setup.rs
* The setup subcommand was exiting the programm no matter what,
even if the `clean` flag was provided.
Now it returns to the main function on encountering the clean flag.
> Fix `clean` flag

- src/tests/fakes.rs
- zellij-server/src/os_input_output.rs
- zellij-server/src/pty.rs
- zellij-server/src/route.rs
- zellij-server/src/tab.rs
- zellij-utils/src/logging.rs
Assorted refactors and fixes:
* use Pid instead of RawFd for processes in ServerOsApi
* improve debug performance by writing entire buffers instead of per-byte
* remove muts where not needed
They should have no user-visible impact (except for faster debug output on heavy workloads).
> Random fixes

- Cargo.lock
- src/tests/fakes.rs
- zellij-server/Cargo.toml
- zellij-server/src/os_input_output.rs
- zellij-server/src/pty.rs
This patch fixes #509 by using async read instead of polling a
non-blocking fd. This reduces CPU usage when the ptys are idle.
> fix(pty): use async io to avoid polling

- zellij-server/src/panes/grid.rs
This fixes a crash that happened when left-padding a line whose last character was a wide character.
> fix(compatibility): do not crash when padding before wide char

- src/main.rs
- src/sessions.rs
- zellij-server/src/lib.rs
- zellij-utils/src/cli.rs
If only one session is running, attach to it. Otherwise, list the active sessions (if any).
This also fixes some exit status.
> Make session-name option in attach command

- zellij-client/src/os_input_output.rs
- zellij-server/src/os_input_output.rs
As discussed in https://github.com/zellij-org/zellij/pull/539#issuecomment-850349322, provide context, comment and clippy lint hint.
> Fix build on platforms with TIOCGWINSZ / ioctl() integer type mismatch.

- zellij-client/src/lib.rs
- zellij-server/src/lib.rs
- zellij-server/src/route.rs
- zellij-tile/src/data.rs
- zellij-utils/src/input/config.rs
- zellij-utils/src/input/mod.rs
- zellij-utils/src/input/options.rs
- zellij-utils/src/input/theme.rs
- zellij-utils/src/shared.rs
* add option `theme` that allows for setting of a theme,
the default is `default`
* under `themes` the themes can be described as follows:
either
```
themes:
default:
fg: [0,0,0]
bg: [0,0,0]
black: [0,0,0]
red: [0,0,0]
green: [0,0,0]
yellow: [0,0,0]
blue: [0,0,0]
magenta: [0,0,0]
cyan: [0,0,0]
white: [0,0,0]
orange: [0,0,0]
```
or
```
themes:
default:
fg: 0
bg: 0
black: 0
red: 0
green: 0
yellow: 0
blue: 0
magenta: 0
cyan: 0
white: 0
orange: 0
```
If the key is different from default, it needs to either be specified on
start with `options --theme [THEME]`, or in the configuration file under
theme: [THEME].
closes #390
> Add color theme config

- zellij-utils/src/input/options.rs
* options depended on specification of the
`simplified_ui` flag, now they are independent of each other
> Fix options in config file

- default-plugins/tab-bar/src/tab.rs
- zellij-server/src/tab.rs
This PR aims to solve issue #474.
I decided to put the logic in `Tab::new`. This approach felt the "cleanest" to me.
If this breaks any style guides or should be done differently for other reasons please let me know and I'll change it.
> Don't rename 'unnamed' tabs upon deletion of other tabs

- CHANGELOG.md
- Makefile.toml
The `layout-dir` got removed, but the
make action depended on the `dir`.
> Fix missing `layout-dir` in makefile

- zellij-client/src/lib.rs
Auto detach the session when receiving a forced close signal (SIGWINCH, SIGTERM, SIGINT, SIGQUIT, SIGHUP).
The current behavior when the user manually closes Zellij (ctrl-q) remains the same and does not auto detach.
Closes #572
> Detach session when forced close detected (handling SIGTERM and other signals)

- zellij-server/src/lib.rs
- zellij-server/src/pty.rs
- zellij-server/src/route.rs
- zellij-utils/src/input/options.rs
* Adds an option to specify a default shell
either by specifying `default_shell: [PATH]`
in the config, or running zellij with
`zellij options --default-shell [PATH]`
> Add option to specify a default-shell

- zellij-server/src/route.rs
- zellij-utils/src/input/actions.rs
- zellij-utils/src/input/command.rs
Add the ability to bind running commands to
an action.
Eg:
```
- action: [Run: {command: "htop",},]
key: [F: 6,]
```
Optionally the direction and arguments can be
specified:
```
- action: [Run: {command: "htop", args: ["-C",]},]
key: [F: 7,]
```
The directional splits are analogous to the `[NewPane]` splits.
```
- action: [Run: {command: "htop", args: ["-C",], direction: "Up"},]
key: [F: 8,]
```
> Add running commands to an action

- zellij-server/src/os_input_output.rs
- zellij-server/src/pty.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-server/src/unit/tab_tests.rs
This is a fix for https://github.com/zellij-org/zellij/issues/597 (and likely some other issues).
Previously we sent a `SIGKILL` to a child process whenever we wanted to kill it (eg. closing a pane).
Not only is this overkill (pun intended) but in some cases the children get stuck (likely if they have some critical cleanup to do that we're not giving them a chance to).
Now we make 3 attempts to send a `SIGTERM`, and then send a `SIGKILL`. This has a super minor performance implication when closing Zellij with several dozen panes open, but it's (at least on my machine) a question of +1-2 seconds, and it's just on exit in this edge case. So I think it's bearable.
> fix(os): attempt to stop children with SIGTERM before SIGKILL

- zellij-utils/src/input/command.rs
Change
```
Run: {command: <path>, args: [ARGS], direction: <direction> }
```
into
```
Run: {cmd: <path>, args: [ARGS], direction: <direction> }
```
> Change name of `Run` binding for actions

- zellij-client/src/lib.rs
- zellij-utils/assets/config/default.yaml
- zellij-utils/src/input/actions.rs
- zellij-utils/src/input/options.rs
This allows the user to configure the behaviour for when zellij receives `SIGTERM, SIGINT, SIGQUIT or SIGHUP`. User can choose between quit and detach.
> Add on_force_close config option

- example/run_htop_layout.yaml
- example/run_htop_layout_with_plugins.yaml
- zellij-server/src/pty.rs
- zellij-server/src/tab.rs
- zellij-utils/assets/layouts/default.yaml
- zellij-utils/assets/layouts/disable-status-bar.yaml
- zellij-utils/assets/layouts/strider.yaml
- zellij-utils/src/input/command.rs
- zellij-utils/src/input/layout.rs
Add the ability to run commands on loading a layout:
```
- direction: Horizontal
split_size:
Percent: 50
run:
command: {cmd: htop}
```
or respectively:
```
- direction: Horizontal
split_size:
Percent: 50
run:
command: {cmd: htop, args: ["-C"]}
```
In order to specify the difference of commands and
plugins now the plugins need to be under the `run` section:
```
- direction: Vertical
split_size:
Fixed: 2
run:
plugin: status-bar
```
This also means that this is a breaking change for people
that already have a custom layout.
Example layouts:
```
---
direction: Vertical
parts:
- direction: Horizontal
split_size:
Percent: 50
parts:
- direction: Vertical
split_size:
Percent: 50
- direction: Vertical
split_size:
Percent: 50
run:
command: {cmd: htop}
- direction: Horizontal
split_size:
Percent: 50 …
```
> Add commands to layout

- zellij-server/src/panes/plugin_pane.rs
* Comments the `unimplemented!` macro out, in favor of a noop
The macro is still there for easy greppability.
It is still unimplemented, but zellij doesn't need to panic once
a plugin does get a scroll event.
> Add noop for mouse actions on `plugins`

- src/main.rs
- zellij-utils/src/setup.rs
Adds the ability to dump the default layouts to
stdout, similar to the `zellij setup --dump-config`,
but now it needs the name of a currently existing
layout:
- default
- strider
- disable-status
`zellij setup --dump-layout [LAYOUT]`
> Add cmd to dump `layout` to stdout

- zellij-server/src/route.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab.rs
- zellij-utils/assets/config/default.yaml
- zellij-utils/src/errors.rs
- zellij-utils/src/input/actions.rs
Fixes #606
Currently scroll down to bottom then exits scroll mode.
> feat(scroll): Restore scroll position on SIGINT

- src/main.rs
- zellij-utils/src/input/layout.rs
- zellij-utils/src/setup.rs
Simplify deserialzation for layouts, config and config options.
Move the logic responsible to `Setup::from_options()` in order
to be able to parse `main.rs` as well as adding new command easier.
> Simplify deserialization for layouts, config

- zellij-server/src/screen.rs
- zellij-server/src/tab.rs
- zellij-server/src/wasm_vm.rs
Fixes #621
* `ScreenInstruction::SetSelectable` etc.
were not updating correctly, if a NewTab was spawned, before
the plugin was finished setting the attributes.
Now the `tab_index` is used to send the instructions to
their respective tabs and plugins.
> Fix plugin attribute update on inactive tab

- CHANGELOG.md
- src/tests/e2e/remote_runner.rs
- zellij-server/src/panes/alacritty_functions.rs
- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/mod.rs
- zellij-server/src/panes/terminal_character.rs
This adds support for OSC 4 (and friends) which enables temporarily changing the index colors of the terminal to an arbitrary RGB color.
This should solve (among other things): https://github.com/zellij-org/zellij/issues/613
> fix(compatibility): support changing index colors with osc

- zellij-server/src/os_input_output.rs
nushell doesn't create a new process group when spawning a process,
so all processes including the ones spawned by us are in the same
foreground group. So the kernel will send signal to every member of this
group.
This patch fixes this issue by creating a new foreground process group
when spawnning a new terminal pane.
Fix #615
> fix unexpected pane closing issue with nushell

- zellij-server/src/panes/terminal_pane.rs
This fixes an issue in the new pane UI where when we switched to an alternative grid (eg. when opening nvim or htop) the frame around the pane was sometimes erased.
> fix(compatibility): do not remove frame when clearing viewport

- zellij-client/src/input_handler.rs
- zellij-client/src/unit/input_handler_tests.rs
Fixes: https://github.com/zellij-org/zellij/issues/560
This was happening because while we were properly dealing with bracketed paste, we weren't forwarding the instructions to the active terminal. Now we are.
> fix(compatibility): properly paste multilines

- CHANGELOG.md
- zellij-server/src/panes/grid.rs
This fixes docker-compose progress bars, and might also be a fix for https://github.com/zellij-org/zellij/issues/353 (but I'm not 100% sure it's the same bug).
It fixes them by properly treating the 'B' CSI signal when on the edge of the screen. Before we would add newlines where we should just stop instead.
> fix(compatibility): docker-compose progress bar

- zellij-client/src/input_handler.rs
- zellij-server/src/route.rs
- zellij-server/src/screen.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-utils/assets/config/default.yaml
- zellij-utils/src/errors.rs
- zellij-utils/src/input/actions.rs
- zellij-utils/src/input/mod.rs
Fixes #398.
Tab key is used as default for the `GoToLastTab` action.
A test have been added, All other tests still pass.
> feat(tab): add keybind to go to last tab visited

- CHANGELOG.md
- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/terminal_pane.rs
This fixes a bug introduced in https://github.com/zellij-org/zellij/pull/653
We would be sending the bracketed paste instructions to terminals regarding of whether they requested them or not, which was causing some issues in eg. vim.
> fix(compatibility): only send bracketed paste to terminals requesting it

- CHANGELOG.md
- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/terminal_character.rs
- zellij-server/src/panes/terminal_pane.rs
Previously we treated the "block" cursor shape as the default, changing to it every time we received the `[0 q` CSI. But this is not the correct behaviour, as in some terminals the default shape is another one. This fixes the issue.
Fixes: https://github.com/zellij-org/zellij/issues/552
> fix(compatibility): maintain original cursor shape

- zellij-server/src/panes/plugin_pane.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/tab.rs
This removes some hacks we previously had where we'd use a panes `select`ability when deciding if we should draw a border for it. Now we explicitly use the new `borderless` layout/pane attribute for that.
> refactor(tab): use borderless instead of selectable where appropriate

- CHANGELOG.md
- zellij-server/src/screen.rs
This fixes cases where sometimes on tab close the contents of the tab would stick around on the screen.
I think it's also a fix for https://github.com/zellij-org/zellij/issues/678
> fix(tabs): force render by index rather than by position

- zellij-server/src/tab.rs
This PR fixes a small visual bug that causes tab names to have the same name if we close any tab that is not the last and create a new tab.
Previously, if we had tabs 2, 3, and created a new tab, we would end up with tabs 2, 3, 3. Now we get 2, 3, 4.
> fix(tabs): use tab index for tab name

- CHANGELOG.md
- test-template.yaml
- zellij-server/src/ui/pane_boundaries_frame.rs
Fixes: https://github.com/zellij-org/zellij/issues/689
> fix(borders): properly handle wide chars in pane titles

- CHANGELOG.md
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/tab.rs
Fixes https://github.com/zellij-org/zellij/issues/690
> fix(borders): properly handle in-viewport borderless panes

- example/default.yaml
The default keybind file in the examples folder has a syntax error for the NewTab action. The file is being referenced in the docs so when copy pasting it (like I did) to customize off of it, zellij won't be able to read the config on start up.
> fix(example) Update NewTab action in example/default.yaml to new syntax

- src/tests/e2e/cases.rs
- src/tests/e2e/remote_runner.rs
- zellij-client/src/unit/input_handler_tests.rs
- zellij-server/src/logging_pipe.rs
- zellij-server/src/panes/unit/grid_tests.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-utils/src/input/config.rs
- zellij-utils/src/input/unit/keybinds_test.rs
I split this into two commits, as unused_io_amount is a correctness fix while the others are mostly style.
Fixes unusused_io_amount, needless_borrow, let_and_return, vec_init_then_push, unit_arg, useless_format, field_reassign_with_default, redundant_clone.
> Various clippy fixes

- default-plugins/tab-bar/src/line.rs
- default-plugins/tab-bar/src/main.rs
- default-plugins/tab-bar/src/tab.rs
This PR fixes #668 (somewhat) and #699. The active bar won't disappear anymore, but which tabs render is still inconsistent. I think the only way to make it more consistent would be to calculate space required for the collapsed tabs beforehand and remove that amount before calling tabs_to_render.
> fix(tab-bar): prevent active tab from being hidden

- Cargo.lock
- default-plugins/tab-bar/Cargo.toml
- default-plugins/tab-bar/src/line.rs
- default-plugins/tab-bar/src/tab.rs
- zellij-utils/Cargo.toml
- zellij-utils/src/shared.rs
In preparation for tab names from layout files #706, we need to account for wide characters.
After changing tab-bar, this was the result (notice the line below tab bar).
The culprit was in zellij-utils, using unicode-width in ansi_len fixed it.
> Calculate width with unicode-width in tab-bar and utils

- src/main.rs
- fixes #702 
- handle opts before client os input setup
> fix automated build errors on setup command

- zellij-utils/src/input/config.rs
- zellij-utils/src/input/layout.rs
Improves the way empty valid `yaml` files are handled.
When deserializing a `config` or `layout` file, that is
an empty valid `yaml` file, eg:
```
---
```
We now assume the default configuration is desired.
> Improve handling of empty valid `yaml` files

- src/main.rs
- zellij-client/src/lib.rs
- zellij-utils/src/cli.rs
Add options subcommand to attach
fixes #688
- the `options` subcommand of `attach` functions the same,
as the `options` subcommand of creating the normal session,
but not every option will have an effect on reattaching,
for example the `default_mode` setting would make no sense
to switch.
In the future it would make sense to be able to hot swap some
of the options on reattach, but we are not able to do that yet,
for example the `default_shell` one.
Eg:
```
zellij attach <session-name> options --theme <theme>
```
> Feature attach options

- CHANGELOG.md
- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__clear_scroll_region.snap
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__emacs_longbuf.snap
Fixes https://github.com/zellij-org/zellij/issues/321
This makes sure we do not wrap empty lines when resizing panes.
> Fix prompt line overflowing when resizing panes

- zellij-server/src/tab.rs
fixes #727
Inheriting the current working directory didn't work when switching between tabs. This happened because the event to notify the pty of an pane change was triggered when setting the active pane inside of the current tab, but switching between tabs will only cause a re-render of the newly selected tab and it's panes without setting the active pane. This was fixed by moving the event to notify the pty of the pane change into the tabs render method.
> fix(cwd-pane): Fix for cwd not being inherited when switching tabs

- zellij-server/src/lib.rs
Currently, when the server exits, Session data is leaked because 'server_listener' thread still holds a reference to it.
Due to this thread blocking on the socket accepting, to fix this problem, we change it to polling mode (the timer interval is 10 milliseconds) and add a flag to indicate exit.
> fix(server): fix leakage of SessionMetaData

- zellij-server/src/wasm_vm.rs
Every plugin will have following two directories for its use:
`./`: Plugin's own data should be saved here, every plugin will have its own directory.
`/global/`: All plugins have access to this directory, Some shared data could be saved here.
> fix(plugin): Set preopen directories properly

- zellij-utils/src/input/config.rs
- zellij-utils/src/input/layout.rs
Allow specifying only the tab name in the `tabs` section
- For example this is now possible:
```
tabs:
- name: first
parts:
- direction: Vertical
- direction: Vertical
- name: second
- name: third
```
For that the tab section defaults the direction to
`direction::Horizontal`
- Adds an error upon specifying a tab name inside the `parts` section
of the tab-layout
> feat(layout): specify only tab name in `tabs` section

- Makefile.toml
fixes #733
Copy the default config to the examples folder on release,
Add the `copy-default-config` task to the makefile, and add it to the release process.
> feat(release): Copy default config to the examples folder on release

- Makefile.toml
- add building plugins `build-plugins` as a dependency for the task
`build-dev-data-dir`
> fix(makefile): build-plugins on building dev-dir

- Makefile.toml
- switch the `update-default-config` task to be prior to commiting
changes
> fix(makefile): update `update-default-config`

- default-plugins/strider/src/main.rs
This prevents strider from descending into the /host folder, which was causing it to display an irrecoverable blank screen
> fix(strider): do not descend into host folder

- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/plugin_pane.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab.rs
Fix #306 
Currently, if a command is producing output (eg `tail`), then scrolling up causes the command to overwrite the scroll buffer.
This PR fixes it. Now when a pane is scrolled up, new vte events are buffered and when we exit scroll, the events are played at once.
> Fix(scroll): Prevent scroll buffer overwrite

- zellij-utils/src/input/config.rs
- zellij-utils/src/input/layout.rs
Fix #714
Fix #756
Allow empty `config` and `layout` files
- Currently empty files are parsed as yaml documents, since they
are empty they are invalid yaml files and a deseralization error would
follow.
Now we ignore the incorrect yaml on an empty document and treat it as
an empty yaml document.
Eg:
```
```
and
```
---
```
Are now treated equally.
Alternative: Keep treating the files as `yaml` documents.
> feat(config): Allow empty config files

- zellij-utils/src/setup.rs
- commands that don't use the config file now wont throw an error on
malformed config files
> fix(setup): switch setup order

- src/main.rs
- src/sessions.rs
- zellij-utils/src/ipc.rs
I am working on another work on zellij, but during this, I found typos. `occured` should be replaced `occurred`.
Ref: https://www.grammarly.com/blog/occurred-occured-ocurred/
> fix(typo): Correct typo from `occured` to `occurred`

- CONTRIBUTING.md
This PR brings a fix for arguments of `cargo make run` command in `CONTRIBUTING.md`.
When I tried the command before this change, I got the error below:
```sh
$ cargo make run -- -l strider
[cargo-make] ...
...
Finished dev [unoptimized + debuginfo] target(s) in 0.09s
Running `target/debug/zellij --data-dir /tmp/zellij-org/zellij/target/dev-data/ -- -l strider`
error: Found argument '-l' which wasn't expected, or isn't valid in this context
USAGE:
zellij --data-dir <data-dir>
For more information try --help
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```
This is because `cargo make run` just passes all subsequent arguments to zellij binary. Therefore, I suggest that `--` argument be removed from the example shown in `CONTRIBUTING.md`. …
> fix(docs): fix wrong arguments for `cargo make run` given in CONTRIBUTING.md

- zellij-server/src/os_input_output.rs
Building zellij on macOS shows a warning in `zellij-server/src/os_input_output.rs`:
```sh
warning: unused import: `std::fs`
--> zellij-server/src/os_input_output.rs:7:5
|
7 | use std::fs;
|     ^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: `zellij-server` (lib) generated 1 warning
```
`std::fs` is only used when `target_os` is Linux:
https://github.com/zellij-org/zellij/blob/03e62eb91c4f53a5be1548fecacc1fd5173adf47/zellij-server/src/os_input_output.rs#L364-L367
> fix(warning): Fix an unused import warning of std::fs on macOS

- zellij-server/src/route.rs
- zellij-utils/src/input/actions.rs
* Behaves like the `Write` action, but one can specify
strings themselves instead of their bytecodes.
Usage:
WriteChars: "cargo make test",
> add: `WriteChars` action

- .github/ISSUE_TEMPLATE/bug_report.md
I found a typo and some grammatical errors in `bug_report.md` from `ISSUE_TEMPLATE`.
> fix(docs): Fix a typo and some grammatical errors in bug_report.md

- Cargo.toml
* specifies the minimum version the package can be compiled with,
may be ignored with `--ignore-rust-version` option
ref: https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-rust-version-field
> add: `rust-version` (msrv) field to `Cargo.toml`

- Cargo.lock
- zellij-server/Cargo.toml
- zellij-server/src/os_input_output.rs
- zellij-server/src/pty.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-server/src/unit/tab_tests.rs
This is a fix for both https://github.com/zellij-org/zellij/issues/803 and https://github.com/zellij-org/zellij/issues/796
The major user facing effects are that this should significantly improve our resource utilization in regards to process count and memory usage. It also means child processes are not exposed to the open FDs of the main Zellij process.
The major changes:
1. Instead of creating new terminals with `forkpty` we now use `openpty` and do the forking ourselves with Rust's `Command` - which we were doing anyway. This saves considerable amounts of RAM and actually makes a lot of stuff simpler (eg. we don't need to set the process group of the forked process because `Command` does it for us. We also need to do the acrobatics we were doing to find out the shell's pid because it's …
> fix(unix): forkpty => openpty

- Cargo.lock
- zellij-utils/Cargo.toml
- zellij-utils/src/shared.rs
* `colors_transform` is deprecated and superceded by `colorsys`
ref: https://crates.io/crates/colors-transform
> Fix: move `colors_transform` to `colorsys`

- zellij-server/src/pty.rs
> fix(cwd): open pane in cwd even if default shell is explicit

- zellij-server/src/tab.rs
The (by now not so new) resizing algorithm unfortunately ignores the minimum pane sizes. Which can sometimes cause rendering issues (eg. cursor being displayed on the pane border). This doesn't fix it 100%, but it at least fixes it for cases when we resize panes directly - which is the vast majority of cases. Otherwise it's just when resizing the whole terminal window.
@TheLostLambda - any chance you can see if I'm missing something critical? This seems good to me.
> fix(resize): do not ignore minimums when doing directional resizes

- Cargo.lock
- zellij-utils/Cargo.toml
- zellij-utils/src/errors.rs
I completed an inline TODO in `zellij-utils/src/errors.rs` :) The `handle_panic` function has a usage of low color code, but I could not understand what the codes mean. So, I didn't touch them.
> fix(errors): Add colored crate to replace primitive color formatting

- Cargo.lock
- zellij-utils/Cargo.toml
- zellij-utils/src/input/config.rs
- zellij-utils/src/input/plugins.rs
What I did:
* Added [`thiserror`](https://crates.io/crates/thiserror).
* Made error types simpler.
Related to:
* https://github.com/zellij-org/zellij/pull/824#discussion_r741158278
> fix(errors): Introduce `thiserror` to make error types simpler

- Cargo.lock
- Cargo.toml
- src/commands.rs
- src/main.rs
What I did:
* Split one massive main function in `src/main.rs` into multiple functions in `src/commands.rs`.
* Introduced `dialoguer` to bring a confirmation prompt (`[y/n]`) for the following code. (I thought it is better to use a well-maintained library instead of implementing low-code in the same function.)
https://github.com/zellij-org/zellij/blob/043a3cf388bbe041d9900a431ae0d718cfc6ac92/src/main.rs#L46-L60
NOTE: This PR depends on:
* https://github.com/zellij-org/zellij/pull/824
> fix(main): Refactor src/main.rs by splitting one massive main function into commands.rs

- .github/workflows/rust.yml
Zellij seems to support macOS as well on the release page.
I think supporting macOS CI would make Zellij more robust and prevent regression for macOS.
It would be better to support it on e2e tests as well.
> feat(ci): Support macOS build & test on CI

- CONTRIBUTING.md
I think the e2e test instruction needs more information for macOS.
> fix(docs): Add additional e2e test instruction for macOS users (including m1)

- docker-compose.yml
I suggest using the key-value style for environments to prevent human errors in `docker-compose.yml` instead of the array. YAML detects duplicate keys.
I have two more suggestions: one is removing `---` on the top, another is bumping the docker-compose file version to 3. Are there any reasons to use them? If no reasons, I would like to do them.
> fix(docker-compose): Use the key-value style for environments to prevent human errors

- Cargo.lock
- src/sessions.rs
- zellij-client/src/lib.rs
- zellij-server/src/lib.rs
- zellij-utils/Cargo.toml
- zellij-utils/src/consts.rs
- zellij-utils/src/envs.rs
- zellij-utils/src/input/mod.rs
- zellij-utils/src/lib.rs
This PR aims to prevent Zellij environment variable manipulation from being scattered in various places of code and to make adding new variables such as `ZELLIJ_PANE_ID` easy.
> fix(envs): Unify operation of Zellij environment variables

- src/commands.rs
- zellij-client/src/input_handler.rs
- zellij-server/src/lib.rs
- zellij-server/src/screen.rs
- zellij-utils/src/cli.rs
- zellij-utils/src/input/options.rs
add the ability to toggle boolean options with a cli flag:
example:
if the pane frames are turned off in the config file,
then passing in the `--no-pane-frames` flag will toggle the
pane frames on
> add(feature): toggle boolean options with cli flag

- zellij-client/src/input_handler.rs
- zellij-client/src/lib.rs
- zellij-client/src/stdin_handler.rs
When fixing some paste issues in https://github.com/zellij-org/zellij/pull/810 I accidentally broke querying panes for whether they have bracketed paste on or not (oops!). This resulted in several issues.
Here this is fixed by sending the bracketed paste instructions separately to the backend so that it can recognize them and do the right thing depending on the terminal pane.
This should fix https://github.com/zellij-org/zellij/issues/854 and https://github.com/zellij-org/zellij/issues/856
> fix(input): properly query bracketed paste mode in terminals

- zellij-client/src/input_handler.rs
- zellij-server/src/screen.rs
- zellij-utils/src/input/options.rs
- zellij-utils/src/setup.rs
* previously it was only possible to turn off certain features with a
command line option, now it is possible to also overwrite this
behavior in a sane way, for that some breaking changes happened:
following options got renamed and inverted:
```
disable_mouse_mode -> mouse_mode
no_pane_frames -> pane_frames
```
following cli options got added:
```
mouse-mode [bool]
pane-frames [bool]
simplified-ui [bool]
```
the following cli flag got removed:
```
simplified-ui
```
They can be specified in the following way:
```
zellij options --mouse-mode true
```
in order to enable the mouse mode, even if it is turned off in the
config file:
```
mouse_mode: false
```
The order is now as follows:
1. corresponding flag (`disable-mouse-mode`)
2. corresponding option (`mouse-mode`)
3. corresponding config …
> fix(options): handling and overwriting cli opts

- Cargo.lock
- Cargo.toml
- src/sessions.rs
I implemented a suggestion for a similar session name if the provided name does not exist.
If an invalid session name is provided, `attach` and `kill session` commands output errors:
```
$ zellij k scientific-activ
No session named "scientific-activ" found.
$ zellij a scientific-activ
No session named "scientific-activ" found.
```
This PR adds help to this using [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) as the same with [rustc implementation](https://github.com/rust-lang/rust/blob/46b8e7488eae116722196e8390c1bd2ea2e396cf/compiler/rustc_span/src/lev_distance.rs#L53):
```
No session named "scientific-activ" found.
help: Did you mean `scientific-activity`?
```
> feat(sessions): Suggestion for a similar session name

- zellij-server/src/tab.rs
Prepare for break pane command (#196) by making close_pane return the closed
pane. Also split the function up to hopefully be more readable.
> refactor(tab): close_pane returns closed pane

- zellij-server/src/panes/terminal_character.rs
These changes make the code a bit simpler, and avoid outputting ansi reset escape codes each time an EMPTY_TERMINAL_CHARACTER is found.
Example output to terminal emulator:
- before:
```
"\x1b[3;2H\x1b[mWelcome to fish, the friendly interactive shell\x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m \x1b[m "
```
- after:
```
"\x1b[3;2H\x1b[mWelcome to fish, the friendly interactive shell\x1b[m …
```
> Simplify terminal character style diff

- zellij-utils/src/setup.rs
Fixing a typo in `setup --check`.
> fix(typo): fix setup --check

- zellij-server/src/panes/grid.rs
initial attempt at solving #877 
missing handling of when the viewport gets switched to alternative_viewport
> keep track of scrollback buffer size

- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/link_handler.rs
- zellij-server/src/panes/mod.rs
- zellij-server/src/panes/terminal_character.rs
- zellij-server/src/panes/terminal_pane.rs
This adds support for osc8, for a quick idea of how it works see: https://iterm2.com/documentation-escape-codes.html, while this [gist](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) has a lot more details covered. 
The case of a newline immediately after a link ends, for example
```shell
printf '\e]8;;\n\nhttp/example.com\e\\LINK1\e]8;;\e\\\n
```
was  a bit problematic, since the line gets padded with empty characters up to the width of the row:
I handled this by adding a zero width null character to end the link in this situation, not quite sure if that's a reasonable solution though.
> add support for osc 8 escape code

- .github/dependabot.yml
* dependabot will check weekly, if the gh actions have new versions
available and will open a pr, if necessary
> feat(update): integrate dependabot for gh actions

- zellij-server/src/wasm_vm.rs
- zellij-tile/src/shim.rs
> feat: provide the zellij version to plugins

- src/commands.rs
- zellij-client/src/lib.rs
> Prevent a zellij session from attaching to itself.

- zellij-client/src/stdin_handler.rs
- zellij-server/src/panes/terminal_character.rs
- zellij-server/src/tab.rs
- zellij-server/src/ui/overlay/mod.rs
- zellij-utils/src/input/layout.rs
Fixes https://github.com/zellij-org/zellij/issues/885
Windows terminal apparently chunks stdin quite a bit, also when pasting. We detect bracketed paste in Zellij and interpret it for performance reasons (we chunk it up to reduce traffic between Zellij's client/server). There were certain cases in which we didn't handle this correctly and ended up duplicating the bracketed paste instruction and so it appeared on screen.
This fixes that.
Thanks @tranzystorek-io for the hand in debugging this!
EDIT: also a bunch of clippy fixes because a new stable rust came in the middle :)
> fix(compatibility): do not duplicate bracketed paste in chunked stdin input

- zellij-utils/src/input/config.rs
* turn off the merging of key bindings of layout and configuration
files for now.
In certain situations the keybindings would be overwritten.
Fix #923
> fix(config): unbind keys correctly

- src/tests/e2e/snapshots/zellij__tests__e2e__cases__mirrored_sessions.snap
- zellij-server/src/lib.rs
- zellij-server/src/panes/plugin_pane.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/route.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab.rs
- zellij-server/src/ui/pane_contents_and_ui.rs
- zellij-server/src/unit/tab_tests.rs
- zellij-server/src/wasm_vm.rs
- zellij-utils/src/errors.rs
This is another layer of preparation for supporting multiple users.
In this episode, we:
1. Change plugins so that one is created for each user
2. Change the infrastructure around them so that plugins are individually updated by user actions (rather than all relevant plugins be updated for each relevant user action)
3. Change the various input mode tracking around the app so that it's per client. This has the upshot that even not in mirrored sessions, the plugins are unique per client (which provides for a much nicer user experience).
> Fix(plugins): support multiple users

- zellij-server/src/tab.rs
- zellij-server/src/unit/screen_tests.rs
This is a fix for https://github.com/zellij-org/zellij/issues/940
This was a regression - when switching tabs, we didn't check to see if there's a fullscreen pane we should switch to. I also added a test for this.
> Fix tab fullscreen switch

- Cargo.lock
- src/tests/fixtures/wide_characters_middle_line_insert
- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/unit/grid_tests.rs
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__insert_character_in_line_with_wide_character.snap
This is a fix for https://github.com/zellij-org/zellij/issues/943
The issue was that specifically when inserting a character in the middle of the line, we did not account for wide characters in the line before it and inserted at the absolute position rather at the relative position (removing the excess width caused by wide characters).
> fix(compatibility): handle inserting characters after wide character

- src/tests/fixtures/wide-chars-delete-middle
- src/tests/fixtures/wide-chars-delete-middle-after-multi
- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/unit/grid_tests.rs
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__delete_char_in_middle_of_line_with_multiple_widechars.snap
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__delete_char_in_middle_of_line_with_widechar.snap
This is another fix for https://github.com/zellij-org/zellij/issues/943
In this case we make sure when deleting a character in the middle of the line with a widechar uses the proper absolute index.
> fix(compatibility): handle deleting chars in lines with widechars

- zellij-client/src/input_handler.rs
- zellij-client/src/stdin_handler.rs
- zellij-server/src/tab.rs
resolve #932 (workaround)
Avoid writing csi sgr mouse sequences that don't get parsed by termion to terminal.
Improve mouse copy by limiting copying only to release events that happen after a selection has been initiated.
> fix(mouse): prevent unhandled mouse events escape to terminal

- Makefile.toml
- src/tests/e2e/cases.rs
- src/tests/e2e/remote_runner.rs
- zellij-server/src/unit/tab_tests.rs
clippy is not currently configured to run on tests or examples when using cargo make.
This PR addresses that
> ensure clippy runs on all targets

- src/commands.rs
> Fix: missing install assets when `zellij` starts a attach command with `create` option

- zellij-server/src/wasm_vm.rs
Attach users cannot change tabs by clicking the mouse.
Because `tab-bar` plugin call the `host_switch_tab_to` function which it does not return `client_id`.
Since each client passes the `client_id` in the `PluginEnv` structure, I added it.
> fix: update switch to tab bug in multiple users

- zellij-server/src/wasm_vm.rs
This issue resolve #983 
Fixed the problem that the `client_id` variable is not updated normally because it has the same name.
The `client_id` of `plugin_map` was re-assigned and it was not updated with the connected `client_id`.
> fix: change duplicated `client_id` value name to underscore

- zellij-server/src/panes/plugin_pane.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/panes/unit/terminal_pane_tests.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/wasm_vm.rs
Another fix for (among other things): https://github.com/zellij-org/zellij/issues/983
> fix(plugins): send events to plugins properly in a multiuser env

- zellij-server/src/ui/pane_boundaries_frame.rs
fixes #931 and addresses part of #883.
The title format is "Zellij (<session_name>) - <active pane name/title>".
> Pass active terminal title through to terminal emulator

- zellij-server/src/lib.rs
- zellij-server/src/panes/grid.rs
- zellij-utils/Cargo.toml
- zellij-utils/assets/config/default.yaml
- zellij-utils/src/consts.rs
- zellij-utils/src/input/options.rs
> Feature: Configurable scroll buffer

- zellij-server/src/os_input_output.rs
This issue resolve #993 
Fix an error that occurs when calling the `current_dir` function with a non-existent `PathBuf`.
> fix: add exception for cwd does not exist

- default-plugins/status-bar/src/main.rs
- default-plugins/status-bar/src/second_line.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/copy_command.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/tab/unit/tab_tests.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-tile/src/data.rs
- zellij-utils/src/input/options.rs
Currently the copy to clipboard is done using OSC52 which is not supported by some linux terminals like `gnome-terminal` or `xfce4-term` etc. 
The proposal here is to allow users to set a specific copy command.
`zellij options --copy-command "xclip -sel clip"`
or 
`zellij options --copy-command "wl-copy"`
would be two examples for x11 and wayland.
This is my first ever rust code so I'm happy to hear any feedback.
This was tested on Ubuntu using `gnome-terminal`
> Proposal: Allow use of system clipboard

- zellij-utils/assets/config/default.yaml
Document the new --copy-command / copy_command option (#996) in the default config with examples.
> Add option to default config for copy_command (PR #996)

- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
> feat: accept only printable unicode char

- zellij-server/src/tab/mod.rs
use pane content_rows to take account of frame enabled/disabled
fix #1002
> fix(scroll): scroll pane by actual amount of rows

- zellij-utils/src/input/keybinds.rs
Log with a warning, if the user finds himself in a mode,
that has no action associated with it.
fix #949
> fix(config): warn on mode without actions

- default-plugins/status-bar/src/main.rs
- default-plugins/status-bar/src/second_line.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/clipboard.rs
- zellij-server/src/tab/copy_command.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/tab/unit/tab_tests.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-tile/src/data.rs
- zellij-utils/assets/config/default.yaml
- zellij-utils/src/input/options.rs
- zellij-utils/src/lib.rs
allow setting primary selection or system clipboard
resolve #1018
Add the `copy-clipboard` option which can be set to:
- `system`
- `primary`
By default it is set to `system`, setting it to `primary` will write the copied text to the primary selection buffer on x11/wayland (it won't work on `macos`).
> allow osc52 copy destination configuration

- default-plugins/status-bar/src/second_line.rs
This solves #1010 
- The instructions are now displayed correctly
- It slightly unifies the style (the angle brackets weren't colored green before)
- I refactored the code a bit, since I noticed, that we do the same thing over and over again in this function
Here are some pictures:
Before:
After:
> Solve Issue #1010

- Cargo.lock
`autocfg` 1.0.1 can cause problems when running cross compilation with the `--locked` configuration, for example in the Void Linux builds: https://github.com/void-linux/void-packages/issues/34889
> chore: bump internal autocfg dependency to 1.1.0

- zellij-server/src/panes/floating_panes.rs
- zellij-server/src/panes/plugin_pane.rs
- zellij-server/src/tab/mod.rs
Panes used to refocus (eg. when a pane is closed) based on the most recently active pane. But this was accidentally removed in a previous change (by yours truly). This brings it back, as well as removing some potential crashes due to API misuse that we intend to change anyway.
> fix(ui): restore get active at

- src/sessions.rs
- zellij-client/src/lib.rs
- zellij-server/src/lib.rs
- zellij-server/src/route.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/ipc.rs
This PR is related the invalid assignment of `client_id`.
As the above log, the problem occurs when `attaching` to a session.
The cause of the problem is the `assert_socket` function, which checks whether the socket is connected before attaching.
Ideally, this should work like this:
But, currently like this:
To solve this problem, `assert_socket` has to wait for a message from the server.
> fix: invalid assignment of `client_id` 

- zellij-server/src/tab/unit/tab_integration_tests.rs
`assert_eq!(..., true)` can be replaced with `assert!(...)`; this would be much simpler.
> Replace unnecessary `assert_eq!` with `assert!`

- zellij-utils/assets/config/default.yaml
add an action to send `^b` while in `tmux-mode`
> add(conf): add action to send `^b`

- zellij-server/src/wasm_vm.rs
This PR simplifies the `if` statement in `zellij-server/src/wasm_vm.rs`.
> Remove unnecessary `continue`

- zellij-server/src/tab/mod.rs
This PR fixes a warning pointed out by `clippy`:
```
warning: use Vec::sort_by_key here instead
--> zellij-server/src/tab/mod.rs:1331:9
|
1331 |         panes.sort_by(|a, b| b.active_at().cmp(&a.active_at()));
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `panes.sort_by_key(|b| Reverse(b.active_at()))`
|
= note: `#[warn(clippy::unnecessary_sort_by)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_sort_by
```
> Replace `sort_by` with `sort_by_key`

- zellij-server/src/ui/pane_boundaries_frame.rs
The set title escape code needs to be terminated with a bell character. See https://tldp.org/HOWTO/Xterm-Title-3.html
Before this change I was seeing the following
> Ensure Title doesn't overrun

- zellij-tile/src/shim.rs
`true` and `false` can respectively be `1` and `0` using the type cast expression simply.
> Simplify the conversion from `bool` to `i32`

- src/tests/e2e/cases.rs
- zellij-client/src/input_handler.rs
- zellij-client/src/lib.rs
- zellij-client/src/os_input_output.rs
- zellij-client/src/stdin_handler.rs
- zellij-client/src/unit/input_handler_tests.rs
This fixes the behaviour of our STDIN reader so that it can handle STDIN input that might not come in contiguously. Thanks @tlinford for finding the issue and kicking this off.
This PR also fixes a flaky e2e test.
Fixes https://github.com/zellij-org/zellij/issues/1110 https://github.com/zellij-org/zellij/issues/816 https://github.com/zellij-org/zellij/issues/1107 and possibly others :)
> fix(input): handle discontiguous STDIN input

- zellij-server/src/panes/grid.rs
This fixes cases in which when switching to alternate screen (eg. when opening vim), we sometimes wouldn't properly clear the render artifacts from the previous render eg. when the alternate screen didn't have enough content.
> fix(compatibility): properly clear pane before switching to alternate screen

- .github/workflows/rust.yml
This PR is created because of [this discussion](https://github.com/zellij-org/zellij/pull/1090#issuecomment-1051007086).
I could confirm that the clippy command I use is the same as the `cargo make clippy` command:
https://github.com/zellij-org/zellij/runs/5334524327?check_suite_focus=true#step:5:44
> Use the `clippy-check` action

- CONTRIBUTING.md
This PR adds information about clippy lints as being discussed [here](https://github.com/zellij-org/zellij/pull/1090).
> fix(docs): add information about clippy lints

- README.md
This change is very small but useful for users
> fix(docs): add a link to release page for roadmap

- zellij-utils/assets/config/default.yaml
The default keybinding for tmux detach is `ctrl+b` `d` adding this to the default might be nice for `tmux` users.
> add tmux ctrl+b d shortcut for detach

- .github/workflows/update-flake-lock.yml
as discussed in #1131
Add a github action that creating a weekly pr with updated
flake inputs.
> ci(add): update flake lock action

- zellij-server/src/ui/overlay/mod.rs
- zellij-server/src/wasm_vm.rs
This PR is doing what title suggests :bear:
I came across this while updating the Arch Linux package and thought they should be fixed :)
Log:
```
warning: field is never read: `rows`
--> zellij-server/src/ui/overlay/mod.rs:27:5
|
27 |     rows: usize,
|     ^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: field is never read: `cols`
--> zellij-server/src/ui/overlay/mod.rs:28:5
|
28 |     cols: usize,
|     ^^^^^^^^^^^
warning: field is never read: `plugin_own_data_dir`
--> zellij-server/src/wasm_vm.rs:76:5
|
76 |     plugin_own_data_dir: PathBuf,
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
warning: `zellij-server` (lib) generated 3 warnings
```
> Fix unused code warnings

- Cargo.toml
This PR resolve #1067 
This method will be applied in the next release.
> feat: add `cargo-binstall` method

- .github/workflows/e2e.yml
- Makefile.toml
- src/install.rs
- src/tests/e2e/remote_runner.rs
Spent some time debugging some strange test failures in #1045 with @RobWalt, and we realized that currently
the e2e tests are using the pre-built plugins from the assets folder. Also they are installed into a directory inside the container
that persists between runs when testing locally, so even updating the plugins in `assets` was not giving reliable results.
Solve this issue by:
- launching zellij with `--data-dir` flag in e2e tests, to avoid using prebuilt
plugins from assets dir, and instead use the ones from the docker
mount.
- making the tests use plugins built in release mode to avoid some test
failures due to timing issues.
Other changes are auto-formatting of Makefile.toml.
> fix(tests): ensure e2e tests use updated plugins

- zellij-client/src/lib.rs
- zellij-utils/src/envs.rs
- zellij-utils/src/input/config.rs
Add ability to set `ENVIRONMENT VARIABLES` from the
config and the layout files.
example:
```
env:
ZELLIJ_CONFIG:
DEFAULT
```
or
```
env:
ZELLIJ_LAYOUT_NAME:
BUILD_SESSION
```
If two keys conflict (configuration and layout), then the key
from the layout is used.
fixes: #1059
> add: set `env` var's from config and layout

- zellij-utils/src/input/layout.rs
A layout needed to be specified as follows:
```
---
template:
direction: Horizontal
parts:
- direction: Vertical
body: true
- direction: Vertical
borderless: true
split_size:
Fixed: 1
```
now the same layout can be specified as:
```
---
template:
direction: horizontal
parts:
- direction: vertical
body: true
- direction: vertical
borderless: true
split_size:
fixed: 1
```
> fix(layout): allow lowercase keys and values

- src/sessions.rs
Change `list-sessions` to report an error `1` on the shell
and put the output to stderr,
this can be valuable for scriping and should be consistent with expectations
> fix(cli): `list-sessions` stderr on fail

- zellij-utils/assets/completions/README.md
- zellij-utils/assets/completions/comp.fish
- zellij-utils/src/setup.rs
And infrastructure to make it possible
to add more dynamic completions for
different shells in the future.
eg:
```
zellij attach [completes-active-sessions]
zellij kill-session [completes-active-sessions]
```
fixes: #1030
> add(comp): dynamic completions for fish

- README.md
Switch the badges and the large gif on the landing page,
makes it easier to see the badges and get in contact with
the project, as well as find the documentation.
> fix(readme): switch badges and gif

- zellij-server/src/tab/mod.rs
Add `get_active_pane_or_floating_pane_mut` to `Tab` to allow some code deduplication in the various scroll methods.
> refactor(tab): simplify logic for scrolling active pane

- default-plugins/strider/src/main.rs
- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/plugin_pane.rs
- zellij-server/src/panes/selection.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/panes/unit/grid_tests.rs
- zellij-server/src/panes/unit/selection_tests.rs
- zellij-server/src/tab/mod.rs
- zellij-tile/src/data.rs
Simplify some code around mouse handling:
* remove unnecessary `Option` for position when ending selection, and return `None` when `Grid` has empty selection
* simplify `Tab` mouse release and hold handlers
* when a selection is initiated in a floating pane, and the mouse leaves the floating pane the selection stays active, instead of starting to move the pane
> refactor(tab): simplify mouse hold and release

- nix/crate2nix.nix
- nix/default.nix
Overrides in the global scope dont apply all
attributes for the package in `crate2nix`.
> build(nix): apply overrrides correctly

- Cargo.lock
- zellij-client/Cargo.toml
- zellij-client/src/stdin_handler.rs
- zellij-server/src/panes/terminal_pane.rs
When `DECCKM` is set, `Home` and `End` should also be adjusted. This builds upon the fix in https://github.com/zellij-org/zellij/pull/815 for vim compatibility, but should be also compatible with applications that don't expect the keys in `DECCKM` format.
Fixes #1182.
cc @imsnif
> fix(compatibility): home and end in cursor keys mode

- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/plugin_pane.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/tab/mod.rs
Initial support for forwarding mouse events for applications that request it.
For now support only `SGR` format.
Since the events we get from `termion` do not have mouse button information for `hold` and `release` events, forward them with hardcoded left button.
Thanks @dantepippi for the work in #624, I redid a new branch here since solving the conflicts looked a bit problematic.
Resolves #579
> feature(mouse): forward mouse events

- .envrc
Check, if direnv supports lorri, if not run
`use_flake` directly from direnv.
> add(nix): lorri integration

- zellij-utils/src/cli.rs
Allow multiple `--config` flags, then use the latter.
fixes: #310
> fix(config): allow POSIX style `--config` override

- Makefile.toml
Switch from "lightweight" tags to "annotated" tags for releases,
since "lightweight" tags are meant for private or temporary object
labels.
`man git tag`:
```
Tag objects (created with -a, -s, or -u) are called "annotated" tags; they contain a creation date, the
tagger name and e-mail, a tagging message, and an optional GnuPG signature. Whereas a "lightweight" tag is
simply a name for an object (usually a commit object).
Annotated tags are meant for release while lightweight tags are meant for private or temporary object
labels. For this reason, some git commands for naming objects (like git describe) will ignore lightweight
tags by default.
```
> fix: release tagging

- zellij-utils/src/setup.rs
`CommandFactory::into_app()` is deprecated in
favor of `CommandFactory::command()`
> fix: deprecated function in clap

- Cargo.toml
- src/commands.rs
- src/install.rs
- zellij-server/src/wasm_vm.rs
- zellij-utils/Cargo.toml
This fixes a regression in the feature system:
The asset installation didn't get turned off by the feature.
fixes #1130
> fix(feat): `disable_automatic_asset_installation`

- Cargo.lock
- zellij-utils/Cargo.toml
This PR related to #1231 
The current version of `nix` potentially contains security issues.
(of course, we're not currently using the "problem" function directly)
Updating the `nix` version does not affect the system, so it is recommended to update it.
> chore: bump `nix` version to 0.23.1

- .github/workflows/e2e.yml
- nix/default.nix
Should speed the e2e tests up by about 2 minutes.
> add(ci): install `cargo-make` through `nix`

- zellij-server/src/wasm_vm.rs
fixes #1217
Simply try and create the `ZELLIJ_TMP_DIR` in `start_plugin` before mapping it in wasi, instead of messing around with sticky bits as discusses in the issue, to keep things simpler.
> fix(crash): ensure ZELLIJ_TMP_DIR exists when starting plugins

- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
Fixes #1241 
Tabs will now close if there are no tiled panes left.
> fix(tab): do not crash when only floating panes are left

- zellij-server/src/panes/tiled_panes/mod.rs
- zellij-server/src/tab/mod.rs
This fixes two issues:
1. (regression only in main) when a floating pane is focused the active tiled pane is no-longer colored as active
2. when embedding a floated pane when a tiled pane is in fullscreen, it now behaves properly
> fix(tab): floating panes embed/fullscreen and frame color

- zellij-server/src/screen.rs
Fixes https://github.com/zellij-org/zellij/issues/1134, https://github.com/zellij-org/zellij/issues/805 and probably a few others
When this code was written, the Zellij architecture was a little bit different and it didn't make a whole lot of sense to perform checks to make sure the Tab a certain Action is operating on actually exists. As we moved stuff around (namely to a client/server architecture but not just), these edge-cases became more and more possible.
This fixes a lot (all?) of these potential pitfalls by performing a no-op in case the tab an action would like to use doesn't exist.
> fix(screen): handle various edge cases rather than crashing

- zellij-server/src/panes/grid.rs
Revert "fix(compatibilty): do not use current cursor style in csi erase display (#1142)"
This reverts commit efd2fa412f0f4494795d44a10826597b257dd525.
Fixes #1282, while #1097 should be properly handled now by the changes in #1250.
> fix(compatibility): revert change in csi erase in display handling

- zellij-server/src/panes/grid.rs
Fixes https://github.com/zellij-org/zellij/issues/1284
> fix(compatibility): don't crash on invalid state when padding line

- .git-blame-ignore-revs
Add `.git-blame-ignore-revs` file. That way we can accept `fmt` and
`clippy` PR's, that change quite a bit of our codebase without
negatively impacting the functionality of `git blame`.
Anyone wishing to use this file can set:
```
$ git config blame.ignoreRevsFile .git-blame-ignore-revs
```
> add: `.git-blame-ignore-revs` file

- rust-toolchain
Add `x86_64-unknown-linux-musl` target to `rust-toolchain`,
so that people are able to build the e2e tests.
Fixes #610
> add: `musl` target to `rust-toolchain`

- nix/default.nix
Move `ructc` & `cargo` to devInput, for the devShell.
> fix: remove redundant `rustc` from buildInputs

- nix/default.nix
- rust-toolchain
Build a musl package from the repo, by invoking:
```
nix build "github:zellij-org/zellij#zellij-musl"
```
makes it possible to build bundled applications, that don't need patches
to run:
```
nix bundle --bundler github:NixOS/bundlers#toDEB "github:zellij-org/zellij#zellij-musl"
```
This will build a `.deb` file, that can be installed with `apt`.
> add: musl package to nix

- zellij-server/src/panes/grid.rs
Fixed a bug where in certain (n)vim themes the background color would be lost in empty characters when scrolling.
> fix(compatibility): keep colors when scrolling

- zellij-server/src/panes/grid.rs
This fixes more bg color edge cases - namely scrolling a single line in vim with themes that have a background color different from the terminal color (eg. tokyo night with a black terminal background).
> fix(compatibility): single line scroll bg color and other edge cases

- nix/default.nix
Add `overlays` to the flake outputs.
- the `default` `overlay` supplies the package with the `zellij` name
- the `nightly` `overlay` supplies the package with the `zellij-nightly` name
> add(nix): `overlays` for `zellij` to flake outputs

- default-plugins/status-bar/src/second_line.rs
This is to avoid confusion: New users coming from tmux might expect
internal copy/paste buffers in zellij which are separate from the system
clipboard.
It may therefore be surprising where the copied text ends up and that
zellij has no dedicated "paste" functionality.
Related issues: #1288 #1018
> Improve message when copying to system clipboard

- zellij-server/src/os_input_output.rs
SIGHUP correctly states the intention behind sending a signal when a
pane is closed: The controlling terminal is "hung up".
Also, SIGHUP is better suited than SIGTERM since bash ignores the
latter. This led to the zombie processes observed by some users.
Furthermore, SIGHUP has a special meaning in bash's job control, namely
re-sending the signal to all owned jobs before exiting.
> Fix #1286 by sending SIGHUP when closing a pane

- src/commands.rs
- src/install.rs
- zellij-server/src/lib.rs
- zellij-utils/src/consts.rs
- zellij-utils/src/logging.rs
- zellij-utils/src/shared.rs
This PR is a suggestion from the [discord channel.](https://discord.com/channels/771367133715628073/777801519097184257/964380029297496094)
> - /tmp/zellij-1000/zellij-log/zellij.log this file seems to have 700 permission on linux systems. I don't understand why the executable permission is required here. It can just have 600.
> - I think that the No active zellij sessions found. message on running zellij attach command should go to stderr instead of stdout. Same with the zellij list-sessions command. It makes scripting easier e.g. zellij list-sessions | grep -qF "$session_name" . Ideally, there should be no output to stdout when no session is running.
> fix: minor system improvements

- flake.nix
`flake-utils` doesn't use `nixpkgs` as an input.
> fix: remove `flake-utils` follows attribute

- nix/default.nix
Separate default plugins from `nativeBuildInputs`,
in order to minimize rebuilds.
> fix(nix): separate default plugins

- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/unit/grid_tests.rs
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__ansi_csi_at_sign.snap
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__vttest8_1.snap
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__vttest8_2.snap
This is a fix for https://github.com/zellij-org/zellij/issues/1346 and https://github.com/zellij-org/zellij/issues/1345
> fix(compatibility): fix crash and don't allow cursor beyond row width

- src/sessions.rs
- zellij-client/src/lib.rs
- zellij-client/src/os_input_output.rs
- zellij-client/src/unit/input_handler_tests.rs
- zellij-server/src/route.rs
- zellij-utils/src/ipc.rs
This fixes some edge cases in which the ipc message buffer (between client and server) was corrupted and Zellij would crash as a result. Now, instead of crashing we will log the error and attempt to re-read the channel.
This might be masking other problems (maybe the channel buffer is too small? and there are times when it is filled up?) but in any case these errors should be almost invisible to the user (one render missed or one keypress missed when the load is heavy, etc.)
If this is indeed masking other problems, it'll be much easier to find them and fix them individually now that we log these.
> Fix empty ipc msg crash

- zellij-server/src/panes/link_handler.rs
fix #1354 
Root cause needs investigating, but for now fix the crash.
In theory the index should be present in the hashmap, not sure why this could happen.
> fix(stability): avoid link handler panic on bad index

- zellij-server/src/panes/grid.rs
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__save_cursor_position_across_resizes.snap
- zellij-server/src/tab/unit/tab_integration_tests.rs
Fixes https://github.com/zellij-org/zellij/issues/1146
> fix(compatibility): adjust saved cursor position on resize

- zellij-utils/src/cli.rs
Resolves #918 by utilizing clap's built-in ["visible alias" feature](https://docs.rs/clap/3.0.14/clap/struct.App.html#method.visible_alias). It won't display the aliases exactly as requested in the issue, but I don't believe there's any easy method to format it that way.
Before:
```
SUBCOMMANDS:
attach               Attach to a session
help                 Print this message or the help of the given subcommand(s)
kill-all-sessions    Kill all sessions
kill-session         Kill the specific session
list-sessions        List active sessions
options              Change the behaviour of zellij
setup                Setup zellij and check its configuration
```
After:
```
SUBCOMMANDS:
attach               Attach to a session [aliases: a]
help                 Print this message or the help of the …
```
> feat: Shows subcommand aliases in help text

- zellij-utils/src/input/layout.rs
This PR resolves #1411
If layout exists, zellij have to output an error for **that layout**. but, if an error occurs, zellij finds the layout in the `default` folder again, so, another error may be output.
> fix: update to output error when using `--layout`

- zellij-client/src/stdin_ansi_parser.rs
> fix: macos ansi instruction parsing

- zellij-server/src/lib.rs
- zellij-server/src/pty_writer.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/thread_bus.rs
- zellij-server/src/tty_writer.rs
- zellij-utils/src/errors.rs
Resolve #1366 by offloading writes to a separate thread.
> fix paste freeze (#1366)

- Cargo.lock
- Cargo.toml
I tried to build and run zellij with the updated dependencies and they seem to show no issues.
I need this in order to package zellij for Fedora.
> Updated names and dialoguer crates dependencies

- zellij-utils/src/input/layout.rs
Fixes #1431 
Under the circumstance of checking the existence of a `layout` file, the default assets are always loaded due to missing extensions.
> fix: add checking for missing extensions

- zellij-client/src/lib.rs
- zellij-client/src/os_input_output.rs
- zellij-client/src/unit/input_handler_tests.rs
https://github.com/zellij-org/zellij/issues/1326
https://github.com/zellij-org/zellij/issues/1414
> Fix double panic lockup in clients panic handler

- src/tests/e2e/remote_runner.rs
- zellij-utils/src/cli.rs
- zellij-utils/src/input/layout.rs
- zellij-utils/src/setup.rs
closes #1412 
A layout is considered local if:
`layout.extension().is_some() || layout.components().count() > 1`
This check produces the following results:
"foo": Abs
"foo.yml": Local
"./foo": Local
"foo/bar": Local
"foo/bar.yml": Local
TODO:
> Merge --layout and --layout-path

- zellij-server/src/route.rs
This closes #1419.
By extension it should fix #1410 as well bu I think it would be a good idea to implement a limit for the log file so this doesn't happen again
> Exit client-loop on empty message receive

- default-plugins/status-bar/src/main.rs
- default-plugins/status-bar/src/tip/consts.rs
- default-plugins/status-bar/src/tip/data/compact_layout.rs
- default-plugins/status-bar/src/tip/data/edit_scrollbuffer.rs
- default-plugins/status-bar/src/tip/data/floating_panes_mouse.rs
- default-plugins/status-bar/src/tip/data/mod.rs
- default-plugins/status-bar/src/tip/data/move_focus_hjkl_tab_switch.rs
- default-plugins/status-bar/src/tip/data/quicknav.rs
- default-plugins/status-bar/src/tip/data/send_mouse_click_to_terminal.rs
- default-plugins/status-bar/src/tip/data/sync_tab.rs
- default-plugins/status-bar/src/tip/data/use_mouse.rs
- default-plugins/status-bar/src/tip/data/zellij_setup_check.rs
- default-plugins/status-bar/src/tip/utils.rs
- src/tests/e2e/remote_runner.rs
This adds more tips to the status bar to help users discover more features of Zellij.
The first quicknav tip will be shown at least for the first 10 times Zellij is started, and afterwards a random tip will be chosen.
I used suggestions from here: https://github.com/zellij-org/zellij/issues/938 as well as others. We can of course add more tips in the future.
> Add status bar tips

- Cargo.lock
- zellij-utils/Cargo.toml
There is a possible race condition in `0.8.0`.
> chore(deps): update `crossbeam`

- .github/workflows/rust.yml
- Makefile.toml
Run clippy on all exposed features, to minimize the possiblility
of breakage.
> add(ci/makefile): run clippy on all features

- default-plugins/compact-bar/src/main.rs
Fixes #1477
One thing I wasn't able to figure out:
It works when running "cargo make run -l compact"
but not when running "cargo make install ./test && ./test -l compact".
The latter seems to re-build the old version of the plugin and replace the wasm file in the "plugins" directory?
I don't know enough about WebAssembly / cargo make / the build process to be able to figure this one out.
Any pointers on how to fix this?
Or maybe someone more qualified can take over from here.
> fix: tab selection by left click in compact-bar

- zellij-client/src/input_handler.rs
`WriteChars` is not an idempotent action, that's why it should only
be sent to it's destination client.
> fix(action): send `WriteChars` once per action

- zellij-client/src/input_handler.rs
The  `Write` action should be called once per session.
> fix(action): correctly dispatch the `Write` action

- docs/THIRD_PARTY_INSTALL.md
MacPorts installed in a general way requires `sudo`.
Ref: https://superuser.com/a/1413502
> Fix installation with MacPorts

- src/tests/e2e/snapshots/zellij__tests__e2e__cases__scrolling_inside_a_pane.snap
- zellij-utils/src/input/mod.rs
The order of the "arrow" keys is always left/down/up/right, make the
keybindings for the Scroll mode align with this ordering.
I know it's a nitpick, but I have a talent for spotting such things and subsequently becoming annoyed by them...
> utils/input: Make key order consistent

- zellij-utils/src/input/theme.rs
This is a redo of a previous PR which I had made on a different account. It does the hex conversion in a much nicer way, and uses a custom Deserialize impl.
This adds support for hex colors in the form
```yaml
fg: ff4500
bg: 3f7
```
because hashtags are recognized as comments.
Should solve #880
> feat(theme): allow hex colors for themes

- Cargo.toml
- src/commands.rs
- src/main.rs
- zellij-client/Cargo.toml
- zellij-utils/Cargo.toml
- zellij-utils/src/cli.rs
Add a feature `unstable`, which is intended to communicate the same
intent.
Gate: Send actions from cli with the `unstable` feature.
> add(feature): `unstable`

- zellij-server/src/panes/plugin_pane.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/panes/tiled_panes/mod.rs
- zellij-server/src/panes/tiled_panes/pane_resizer.rs
- zellij-server/src/tab/mod.rs
This fixes a bug where if you opened the in place editor (ctrl+s+e), switched to fullscreen (ctrl+p+f) and closed the editor, the app would be in a bad state and you'd likely have to restart. This also fixes the other way around (switching to fullscreen, opening the inplace editor, switching off fullscreen and closing the pane).
> fix(editor): handle editor in fullscreen

- zellij-server/src/panes/grid.rs
This is a fix for https://github.com/zellij-org/zellij/issues/1206
This also happens when we simply resize the pane without even opening vim or a similar app. The latter happens because we call the resize/reflow method when moving away from an alternative screen (in case the scrollback was resized somewhere in between).
In such a case, we trim lines after the last whitespace to that we won't reflow needless whitespace (eg. have a wrapped line with only whitespace). This mechanism wasn't wide-char aware, and because of that this bug was created. I adjusted it and it now works.
> fix(terminal): properly trim lines with widechars on resize

- zellij-server/src/panes/grid.rs
Fixes https://github.com/zellij-org/zellij/issues/1546
This mostly happened in some edge cases (eg. scrolling up, resizing the terminal and then typing something). This happened because of some mistake in the line reflow calculation in this case.
> fix(scroll): reset scroll properly when typing

- CHANGELOG.md
- zellij-utils/src/logging.rs
- rolls over at 20 MB into `zellij.log.old.0`
- fix #1410
- unsure what happens with multiple zellij instances, probably they all copy over the same old log?
- do we need to update the issue template to tell users to include the old log?
> roll over logs / fix filling up /tmp with logs

- nix/default.nix
The compact bar wasn't an output yet.
> add(nix): add `compact-bar` to the flake outputs

- .github/workflows/update-rust-toolchain.yml
The action still had a reference to the old toolchain location.
> fix(ci): add new rust toolchain location to action

- rust-toolchain.toml
Automatic change by the [update-rust-toolchain](https://github.com/a-kenji/update-rust-toolchain) Github Action.
Github Actions will not run workflows on pull requests which are opened by a GitHub Action.
> rust-toolchain: Update

- CONTRIBUTING.md
- README.md
There references to discord, but not to matrix at the exact same spot.
fixes #1580
> chore(docs): add more matrix links

- zellij-utils/assets/shell/auto-start.fish
This PR adds a usage comment before the auto-start snipped for the fish shell which is emitted by `zellij setup --generate-auto-start fish` as discussed in #1574.
> fix: add usage comment to fish shell auto-start snippet (#1574)

- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/terminal_character.rs
- zellij-server/src/panes/unit/grid_tests.rs
Fixes https://github.com/zellij-org/zellij/issues/617
This was caused by us persisting the cursor hide/show instructions across the alternate terminal screen.
> fix(terminal): persist cursor hide/show through alternate screen

- zellij-server/src/os_input_output.rs
This is a fix to handle the case where the `EDITOR` and `VISUAL` environment variables or `scrollback_editor` config value contain arguments. Eg. `/usr/bin/vim -e`. Previously we either ignored them or silently failed - now we stick them on to the command (after optionally placing the +<line_number> argument).
> fix(editor): handle editor/visual/configured editor with arguments

- zellij-server/src/panes/unit/terminal_pane_tests.rs
- zellij-server/src/tab/mod.rs
resolve  #1376
Avoid forwarding mouse clicks on pane frames/borders to programs.
The improved logic for determining if a click is on a pane frame/border should also be useful for resizing panes with mouse.
> fix: avoid forwarding mouse events on pane border

- CHANGELOG.md
- zellij-client/src/lib.rs
- zellij-utils/src/errors.rs
As an extension to logging only panics in the client (https://github.com/zellij-org/zellij/pull/1433#issuecomment-1135170659), this change should log every panic, no matter if it happens in client or server.
I believe I had some sessions disappearing mysteriously without being attached, so I never saw panic traces. This should be the first step to investigate.
Example log entry:
```
ERROR  |zellij_utils::errors     | 2022-07-25 15:57:30.802 [main      ] [zellij-utils/src/errors.rs:94]: Panic occured:
thread: main
location: At /home/<redacted>/zellij/zellij-utils/src/ipc.rs:158:68
message: called `Result::unwrap()` on an `Err` value: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
```
> Log every panic to the logfile

- zellij-server/src/terminal_bytes.rs
This includes two minor fixes following that changes in https://github.com/zellij-org/zellij/pull/1585
1. We now make sure that when the screen thread is not backed up (i.e. there's room in its buffer to receive immediate render instructions rather than buffering them), we update the render deadline so that timed-out renders will be sent properly.
2. That being said, we also ignore the render deadline if the screen is not backed up to prevent extraneous renders
> performance(pty): update last render time on non-backed-up render

- .github/workflows/release.yml
* macOS does not natively support sha256sum.
> fix(ci): change checksum tool in macos

- CONTRIBUTING.md
- README.md
The default `cargo install` behaviour ignores, in contrast to the `run`,
or `build` behaviour the `Cargo.lock` file. This can lead to
builds breaking after the package is released in a non breaking state.
ref: https://github.com/rust-lang/cargo/issues/7169
We now recommend users to install through `cargo install --locked`.
> fix(readme): cargo install instructions

- .github/workflows/nix-develop.yml
- .github/workflows/nix.yml
Remove the cachix environment.
While environments are a good idea in theory,
github does make working with them tedious, as they do spam status
updates between useful discussions.
> fix(ci): remove cachix environment

- zellij-utils/src/setup.rs
Fixed the theme not being loaded from `themes` folder if there is no `config.yaml` file or `themes:` does not exist in the file.
> fix: theme not loading without config

- zellij-server/src/panes/grid.rs
Following the discussion here: https://github.com/zellij-org/zellij/issues/1620
This adds logging to all unhandled ansi sequences
> chore(logging): log all unhandled ansi sequences

- CHANGELOG.md
- zellij-server/src/screen.rs
- zellij-server/src/unit/screen_tests.rs
while trying to attach a new client. Instead, check whether the first
tab does exist and if not, take the first tab index from the tabs
present in the session. If no tabs exist, panic with a better error
message.
Fixes #1645
> screen: Don't crash when first tab doesn't exist

- zellij-server/src/route.rs
This fixes a crash introduced in the latest release where Zellij would sometimes crash on startup with this error:
```
Error occurred in server:
× Thread 'server_router' panicked.
├─▶ Originating Thread(s)
│     1. stdin_handler_thread: AcceptInput
│   
├─▶ At zellij-server/src/route.rs:503:30
╰─▶ called `Option::unwrap()` on a `None` value
help: If you are seeing this message, it means that something went wrong.
Please report this error to the github issue.
(https://github.com/zellij-org/zellij/issues)
Also, if you want to see the backtrace, you can set the `RUST_BACKTRACE` environment variable to `1`.
```
This was a race condition that happened when the Zellij client sent a message to the server before it was ready. This was exposed in the latest release because we broke down the …
> fix(router): retry messages when server is not ready

- zellij-server/src/panes/csi.rs
- zellij-server/src/panes/mod.rs
- zellij-server/src/panes/terminal_character.rs
- zellij-server/src/panes/terminal_pane.rs
I went a little bit through the code and refactored some little stuff.
> A little refactoring

- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/tab/unit/tab_integration_tests.rs
fix #1687
ensure the check for removing bracketed paste begin/end sequences is run when not in bracketed paste mode
> fix: bracketed paste input not getting adjusted properly

- zellij-server/src/route.rs
Fixes https://github.com/zellij-org/zellij/issues/1696 and https://github.com/zellij-org/zellij/issues/1705
This now uses the same (no longer experimental) retry mechanism we used for one startup message (pixel/cell dimensions) for all startup messages.
> fix(router): startup race

- src/sessions.rs
- zellij-client/src/os_input_output.rs
- zellij-client/src/sessions.rs
- zellij-server/src/lib.rs
- zellij-server/src/os_input_output.rs
- zellij-server/src/route.rs
- zellij-server/src/tab/unit/tab_integration_tests.rs
- zellij-server/src/tab/unit/tab_tests.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-utils/src/ipc.rs
Fixes https://github.com/zellij-org/zellij/issues/1684
With this PR, whenever the server is unable to send messages to the client - instead of crashing - it either marks the client as disconnected (removes it from its state) or does nothing (if for example it's already shutting down or the client is in the process of disconnecting already).
> fix(router): gracefully handle client crashes

- CHANGELOG.md
- Cargo.lock
- zellij-utils/Cargo.toml
turn off default-features for vte, since default includes no_std, and in that case the osc params buffer is capped at 1024 bytes.
Fixes #1709
> fix osc params 1024 bytes limit

- default-plugins/tab-bar/src/line.rs
- default-plugins/tab-bar/src/main.rs
- default-plugins/tab-bar/src/tab.rs
Fixes #1603 , as well as another bigger issue. I noticed that clicking on a tab used index in the linepart vector, which will be incorrect for every tab if there's collapsed tabs. We have to save tab index in LinePart, and then use that to switch tabs.
Clicking on the collapsed tabs brings the user to the first hidden tab on that side.
Fixing the issue in #1603 was as discussed in the issue, as well switching the click comparison to be `click >= length && click < length` instead of `click > length && click <= length`
> fix(tab-bar): fix tab bar click when tabs are collapsed, fix tab bar length calculation

- CHANGELOG.md
- zellij-client/src/lib.rs
fix #1532
Server was closed when the client panics which does not make sense to me, as explained in https://github.com/zellij-org/zellij/issues/1532#issuecomment-1245667341
> Don't send the server an exit signal when client crashes

- zellij-server/src/tab/unit/tab_integration_tests.rs
Reduce boilerplate needed to write tab integration tests that need to check what is being written to pty.
> test: simplify tab integration tests

- CHANGELOG.md
- zellij-server/src/tab/mod.rs
- zellij-server/src/tab/unit/tab_tests.rs
Prevent server from crashing when trying to write bytes to a terminal pane that is suppressed. Closes #1734.
> Fix: issue 1734

- docs/ERROR_HANDLING.md
- zellij-utils/src/errors.rs
Moves the docblock from `utils::errors` to a separate file and links there from the docblock instead.
I'll be phrasing an issue to invite anyone who is interested to help out with error handling in zellij soon.
> Add docs about error handling

- docs/ERROR_HANDLING.md
- zellij-server/src/screen.rs
Got rid of last `unwrap()` calls on result, replacing them with error propagation. The only `unwrap()` left are on `Option` type which would be converted into `fatal()` anyway since the code already checks for the corresponding condition in that same function (`move_clients_from_closed_tab`)
WIP #1753
> zellij-server/src/screen: improve error handling

- .nix/crate2nix.nix
- .nix/zellij.nix
Zellij would not link without the DiskArbitraction and Foundation frameworks on macos (Big Sur). It seems sysinfo requires them. They must be passed as `buildInputs` in the nix flake.
> fix(nix) missing frameworks on darwin

- Cargo.lock
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/tab/unit/tab_integration_tests.rs
- zellij-server/src/tab/unit/tab_tests.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-utils/Cargo.toml
- zellij-utils/src/errors.rs
Removes all calls to `unwrap()` in the tab module of `zellij-server`. Makes all relevant functions return `Result`s instead, attaching error context where possible to trace error origins better. Also updates the code in `server::screen` to accept the new `Result`s and attach context there, too.
Related to #1734.
I want to test what it looks like first by provoking some errors in the code to see whether it's really any good.
> Server: Remove `panic`s in `tab` module

- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/thread_bus.rs
- zellij-utils/src/errors.rs
WIP: #1753 
As suggested in my previous [PR](https://github.com/zellij-org/zellij/pull/1770#issuecomment-1266518037), moving thread_bus error changes to a separate one
> zellij-server: improve thread_bus error handling

- zellij-utils/src/kdl/kdl_layout_parser.rs
Fixes https://github.com/zellij-org/zellij/issues/1779
The issue was that we weren't making sure there aren't any mixed nodes in panes and pane templates (eg. both a command and nested panes or a children block). This fixes it by adding a helpful error in this case.
> fix(layouts): error on mixed nodes

- zellij-utils/src/kdl/kdl_layout_parser.rs
Fixes https://github.com/zellij-org/zellij/issues/1780
This will give an error when:
1. There's a duplicate pane_template definition
2. There's a duplicate tab_template definition
3. There's a pane_template and a tab_template with the same name
> fix(layouts): duplicate layout definition error

- zellij-utils/src/input/options.rs
Fixes https://github.com/zellij-org/zellij/issues/1786
> fix(cli): use provided session-name

- CHANGELOG.md
- src/commands.rs
with session names specified in layout files. A "recursive session" is created when, while running inside some zellij session, a user attempts to spawn zellij and make it attach to that same session.
When attaching via CLI (`zellij attach`) we explicitly check for this condition and error out when needed.
However, besides `zellij attach` it is also possible to declare the session to attach to in layout files like so:
```yaml
session:
name: "foo"
```
This takes a different codepath when starting zellij, and hence bypases the checks we already have in place to avoid recursive sessions. Hence, we implement the check in the other codepath, too, and prevent recursive sessions from happening for good.
Fixes: #1735
> zellij/commands: Prevent recursive sessions

- zellij-server/src/tab/mod.rs
- zellij-utils/src/input/layout.rs
- zellij-utils/src/input/unit/layout_test.rs
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__args_added_to_args_in_template.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__args_override_args_in_template.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__children_not_as_first_child_of_pane_template.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__cwd_added_to_cwd_in_template.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__cwd_override_cwd_in_template.snap
- zellij-utils/src/kdl/kdl_layout_parser.rs
- zellij-utils/src/pane_size.rs
This adds various error messages and error recoveries to issues with layouts.
This also adds the ability to override `args` and `cwd` in command pane_templates (I added documentation to this in the original kdl PR, since that's where we keep the relevant docs until we release).
> fix(layouts): various kdl layout issues and features

- zellij-server/src/os_input_output.rs
- zellij-server/src/pty.rs
- zellij-server/src/tab/unit/tab_integration_tests.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-utils/src/cli.rs
- zellij-utils/src/input/actions.rs
- zellij-utils/src/input/layout.rs
- zellij-utils/src/input/unit/layout_test.rs
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__global_cwd_given_to_panes_without_cwd.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__global_cwd_passed_from_layout_constructor.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__global_cwd_passed_from_layout_constructor_overrides_global_cwd_in_layout_file.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__global_cwd_prepended_to_panes_with_cwd.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__pane_template_command_with_cwd_is_overriden_by_its_consumers_bare_cwd.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__pane_template_command_with_cwd_overriden_by_its_consumers_command_cwd.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__pane_template_command_with_cwd_remains_when_its_consumer_command_does_not_have_a_cwd.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__pane_template_command_without_cwd_is_overriden_by_its_consumers_cwd.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__pane_template_command_without_cwd_receives_its_consumers_bare_cwd.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__pane_template_with_bare_cwd_overriden_by_its_consumers_bare_cwd.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__pane_template_with_bare_propagated_to_its_consumer_command_with_cwd.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__pane_template_with_bare_propagated_to_its_consumer_command_without_cwd.snap
- zellij-utils/src/kdl/kdl_layout_parser.rs
- zellij-utils/src/kdl/mod.rs
This change does two things:
1. It allows defining a `cwd` for non-command "normal" terminal panes too. So that we can define panes that start at a certain folder.
2. It allows defining a global `cwd` per layout. This cwd will be given to all panes in the layout. If they have a relative cwd, it will be appended to this cwd, if this have an absolute cwd it will override this cwd.
3. When opening a new tab from the cli with a layout using the `zellij action new-tab --layout /path/to/my/layout.kdl`, we can now add a `--cwd` flag that will be used just like the global `cwd` in 2, and override it if present. This should allow much more flexibility when creating custom layouts.
Thanks @har7an for suggesting this feature!
EDIT: updated the documentation in …
> feat(layouts): global cwd

- zellij-server/src/pty.rs
- zellij-utils/src/input/layout.rs
- zellij-utils/src/input/unit/layout_test.rs
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__pane_template_with_bare_propagated_to_its_consumer_edit.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__pane_template_with_command_propagated_to_its_consumer_edit.snap
- zellij-utils/src/kdl/kdl_layout_parser.rs
This adds `edit` panes in layouts. These are panes that include a path to a file that will be opened with the user's default EDITOR (or `scrollback_editor` config item).
eg.
```kdl
layout {
pane split_direction="vertical" {
pane edit="./git_diff_side_a"
pane edit="./git_diff_side_b"
}
}
```
EDIT: Documentation added to https://github.com/zellij-org/zellij/pull/1759 where we keep that sort of thing for now.
> feat(layouts): edit panes

- src/commands.rs
- src/main.rs
- zellij-client/src/lib.rs
- zellij-utils/src/consts.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/logging.rs
Adds a new static global variable `DEBUG_MODE`, accessible via `zellij_utils::consts`. It is set when the server is spawned and depends on whether the server was started with the `--debug` flag. This is automatically the case when the first client starting a session is started with the `--debug` flag.
The variable is stored globally to make it easily accessible from within error-handling functions without having to carry the option everywhere. Since it is set by the server upon creation, it is only set exactly once: When the session is started for the first time. Hence, clients connecting to a session with the `--debug` flag cannot override the `DEBUG_MODE` value.
Logging of the Instructions sent in the `zellij_server::thread_bus` will only happen when the server is running in …
> Log `thread_bus` IPC messages only in debug mode

- CONTRIBUTING.md
- docs/ERROR_HANDLING.md
Extend the error handling documentation.
@imsnif: You said you wanted to mention the bit about returning an `anyhow::Result` mentioned in `CONTRIBUTING.md`. I'm honestly not sure where it fits in there, and I don't want to bloat it needlessly... So I extended the error handling docs and added a `TL;DR`:
Is that alright for you, too?
> docs: Describe how to handle Options as errors

- zellij-server/src/panes/floating_panes/floating_pane_grid.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__drag_pane_with_mouse.snap
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__five_new_floating_panes.snap
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__mark_text_inside_floating_pane.snap
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__move_floating_pane_focus_down.snap
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__move_floating_pane_focus_left.snap
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__move_floating_pane_focus_right.snap
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__move_floating_pane_focus_up.snap
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__move_floating_pane_focus_with_mouse.snap
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__resize_tab_with_floating_panes.snap
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__shrink_whole_tab_with_floating_panes_horizontally_and_vertically.snap
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__shrink_whole_tab_with_floating_panes_horizontally_and_vertically_and_expand_back.snap
- zellij-server/src/tab/unit/tab_integration_tests.rs
This changes the order in which the floating panes are opened.
I find the new order to be more convenient, with floating panes grouped one above the other with a slight offset to make them visible, rather than seemingly unexpectedly being opened around the screen (in small and somewhat unusable sizes to boot).
> feat(panes): change floating window positions

- zellij-server/src/os_input_output.rs
- zellij-server/src/pty.rs
When no editor is set in the config, and Zellij can't find one in either `$EDITOR` or `$VISUAL` it will default to `vi` which should be available on most systems. This is what git does.
> fix(editor): default to vi when no editor is set

- Cargo.lock
- zellij-utils/Cargo.toml
The newer version depends on more maintained libraries.
> chore(deps): upgrade log4rs

- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__vttest2_6.snap
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__vttest2_7.snap
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__vttest2_8.snap
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__vttest2_9.snap
This was discovered through an edge case where the a vim window gets a SIGWINCH in certain situations.
> fix(terminal): reset scroll region when clearing screen

- zellij-utils/src/input/layout.rs
- zellij-utils/src/input/unit/layout_test.rs
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__global_cwd_and_tab_cwd_prepended_to_panes_with_and_without_cwd.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__global_cwd_and_tab_cwd_prepended_to_panes_with_and_without_cwd_in_pane_templates.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__global_cwd_and_tab_cwd_prepended_to_panes_with_and_without_cwd_in_tab_templates.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__global_cwd_with_tab_cwd_given_to_panes_without_cwd.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__tab_cwd_given_to_panes_without_cwd.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__tab_cwd_prepended_to_panes_with_cwd.snap
- zellij-utils/src/kdl/kdl_layout_parser.rs
Like the global `cwd` this tab `cwd` can be placed in tabs and prepended to the cwd of the panes. If a global `cwd` exists as well, it will be chained (global `cwd` / tab `cwd` / pane `cwd`).
EDIT: Documentation added to https://github.com/zellij-org/zellij/pull/1759
> feat(layouts): allow defining a tab cwd

- zellij-server/src/lib.rs
- zellij-server/src/panes/plugin_pane.rs
- zellij-server/src/wasm_vm.rs
- zellij-utils/src/errors.rs
Removes calls to `unwrap` and `panic` in the server API of `wasm_vm`, replacing explicit calls to `panic!` with `.fatal()` instead. Leaves the plugin API unchanged.
The most notable change is that now, when we load incompatible plugins (older versions, whatever) we get pretty error messages. In the terminal it looks like this:
```
$ ./target/debug/zellij
Error occurred in server:
× Thread 'screen' panicked.
├─▶ Originating Thread(s)
│   	1. ipc_server: NewClient
│   	2. pty_thread: NewTab
│   	3. screen_thread: NewTab
│   
├─▶ At zellij-server/src/panes/plugin_pane.rs:164:42
╰─▶ called `Result::unwrap()` on an `Err` value: RecvError
help: If you are seeing this message, it means that something went wrong.
Please report this error to the github issue. …
```
> errors: Don't panic in `wasm_vm`

- zellij-client/src/old_config_converter/convert_old_yaml_files.rs
Fixes https://github.com/zellij-org/zellij/issues/1819
This was only happening for explicitly set layouts (eg. with `--layout path_to_file.yaml`) we do check in all other cases. Good catch as always, @raphCode !
> fix(layouts): do not override explicitly set layout if it exists

- zellij-server/src/lib.rs
- zellij-server/src/route.rs
- zellij-server/src/unit/screen_tests.rs
Replacing `unwrap` in `route.rs` with error propagation.
Related to #1753
> improve error handling in route

- CHANGELOG.md
- Cargo.lock
- zellij-server/Cargo.toml
- zellij-server/src/panes/plugin_pane.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/ui/pane_contents_and_ui.rs
- zellij-server/src/wasm_vm.rs
- zellij-tile/src/lib.rs
- zellij-tile/src/prelude.rs
- zellij-tile/src/shim.rs
- zellij-utils/src/errors.rs
This PR picks up a long-standing issue with respect to the plugin system. Since we do not make guarantees about plugin version compatibility, we always require the plugin versions to match the zellij version.
This is usually not an issue for people that only install zellij from official releases, because in this case zellij takes care of updating the plugins proper itself. Things start to get hairy when developing zellij, because once a user has built the plugins themselves from `main`, they will not be updated on the next release automatically.
Previously we had no mechanism to check for this: The plugins were just loaded and executed. Errors always cropped up in the plugins `update` functions, where an `Event` is deserialized from stdin on the plugin side (i.e. in the WASM sandbox/VM). …
> plugins: Improve error handling on plugin version mismatch

- zellij-utils/assets/completions/comp.bash
- zellij-utils/assets/completions/comp.fish
- zellij-utils/assets/completions/comp.zsh
- zellij-utils/assets/config/default.kdl
- zellij-utils/src/input/actions.rs
- zellij-utils/src/input/config.rs
- zellij-utils/src/input/layout.rs
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__keybinds__keybinds_test__error_received_on_unknown_input_mode.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__keybinds__keybinds_test__error_received_on_unknown_key_instruction.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__error_on_more_than_one_focused_tab.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__error_on_multiple_layout_nodes_in_file.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__error_on_pane_templates_without_a_name.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__error_on_tab_templates_without_a_name.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__error_on_unknown_layout_node.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__error_on_unknown_layout_pane_property.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__error_on_unknown_layout_pane_template_property.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__error_on_unknown_layout_tab_property.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__error_on_unknown_layout_tab_template_property.snap
- zellij-utils/src/kdl/kdl_layout_parser.rs
- zellij-utils/src/kdl/mod.rs
A bunch of minor fixes before tomorrow's release:
1. Properly link to the layout documentation for layout errors instead of the general configuration documentation
2. Add a comment in the config file about `clear-defaults` for clarity
3. Add the `-i` flag to the bash / zsh aliases (thanks @raphCode !)
4. Change the aliases to be named `zr` => zellij run, `zrf` => zellij run floating, `ze` => zellij edit, `zef` => zellij edit floating.
> fix(various): minor fixes before 32

- zellij-server/src/lib.rs
- zellij-server/src/pty.rs
Replacing unwrap in pty.rs with error propagation.
Related to #1753 .
BTW, I don't know how to handle error in `task.spawn`, any advise? @har7an
> improve error handling in pty

- src/main.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-utils/src/cli.rs
- zellij-utils/src/input/actions.rs
- zellij-utils/src/input/layout.rs
- zellij-utils/src/input/unit/layout_test.rs
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__close_on_exit_added_to_close_on_exit_in_template.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__close_on_exit_overrides_close_on_exit_in_template.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__layout_with_command_panes_and_close_on_exit.snap
- zellij-utils/src/kdl/kdl_layout_parser.rs
This gives an option both in the cli and for layouts to make a pane exit immediately if its command exited (rather than stick around, show its exit status and allow the user to re-run it with <ENTER>).
eg. in layouts
```
layout {
pane command="htop" {
close_on_exit true
}
}
```
eg. in the cli:
```
zellij run --close-on-exit -- htop
```
> feat(command-panes): optionally allow panes to be closed on exit

- zellij-server/src/panes/floating_panes/mod.rs
- zellij-server/src/panes/plugin_pane.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/panes/tiled_panes/mod.rs
- zellij-server/src/pty.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/ui/boundaries.rs
- zellij-server/src/ui/overlay/mod.rs
- zellij-server/src/ui/overlay/prompt.rs
- zellij-server/src/ui/pane_boundaries_frame.rs
- zellij-server/src/ui/pane_contents_and_ui.rs
Replacing unwrap in `ui` module with error propagation.
Related to #1753
> improve error handling in ui module

- zellij-server/src/lib.rs
- zellij-server/src/pty_writer.rs
and handle occuring errors instead. Replace calls to `log::error` with `non_fatal`.
> errors: Don't unwrap in `server::pty_writer`

- CHANGELOG.md
- zellij-server/src/pty.rs
- zellij-server/src/terminal_bytes.rs
and return `Result`s instead, where appropriate.
> errors: Don't unwrap in `server::terminal_bytes`

- CHANGELOG.md
- zellij-server/src/output/mod.rs
- zellij-server/src/panes/tiled_panes/mod.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/tab/unit/tab_integration_tests.rs
- zellij-server/src/ui/pane_contents_and_ui.rs
and return `Result`s instead. Also modify all modules directly calling into `output` to handle the new `Result` types.
> errors: Don't unwrap in `zellij_server::output`

- zellij-utils/src/cli.rs
- zellij-utils/src/setup.rs
fix #1854
Do not use Config::default(), since default() has empty plugins config and that does not work with the default layout.
Use Config::try_from() instead, since it already handles the clean flag.
Also, do not check the clean flag twice.
> fix: resolve setup --clean panic

- zellij-client/src/input_handler.rs
- zellij-client/src/lib.rs
- zellij-client/src/os_input_output.rs
- zellij-client/src/unit/stdin_tests.rs
- zellij-server/src/route.rs
- zellij-utils/src/input/actions.rs
- zellij-utils/src/kdl/mod.rs
Partially address #1712
Add the ability to toggle mouse mode on/off at runtime via keybindings.
For the time being it does not work with `zellij action` since actions get sent to the server only, while in this case it is handled client side.
This does not implement any ui indicator for mouse mode as suggested in the issue, but all of the terminal emulators I tested this on change their mouse cursor when mouse mode gets toggled, so I think it's already pretty clear.
> feature(mouse): allow toggling mouse mode at runtime

- default-plugins/status-bar/src/main.rs
Ref https://github.com/zellij-org/zellij/issues/1864
This PR will display only the controls line of status bar plugin if its pane has `size=1` instead of tip line.
The tip line is still displayed if `size=2`.
(FYI: it's my 1st PR on a Rust project, if it miss something let me know)
> Display controls line of status-bar plugin if pane size=1

- CHANGELOG.md
- zellij-server/src/lib.rs
- zellij-server/src/os_input_output.rs
- zellij-server/src/panes/floating_panes/mod.rs
- zellij-server/src/panes/tiled_panes/mod.rs
- zellij-server/src/pty.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/tab/unit/tab_integration_tests.rs
- zellij-server/src/tab/unit/tab_tests.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/ipc.rs
Rewrites the `os_input_output` module to handle/propagate errors with `anyhow::Error` instead of unwrapping on all `Result` types. Also unifies all error types regarding this module to by `anyhow::Error`.
As part of this PR the previously existing `SpawnTerminalError` is entirely removed and replaced with a new `ZellijError`. Better documentation on that will follow in a subsequent PR.
> errors: Don't unwrap in `server::os_input_output`

- zellij-utils/assets/config/default.kdl
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__default_config_with_no_cli_arguments.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_env_vars_override_config_env_vars.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_plugins_override_config_plugins.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_themes_override_config_themes.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_ui_config_overrides_config_ui_config.snap
fix #1862 
In Rename mode, the space key is registered in the shared except, so it seems to be a problem that the key cannot be used.
@imsnif `shared_except` seems to be a new feature during kdl conversion.
Is this the correct solution? Or should I see this as an unintended bug?
> fix(keybinds): remove space key from shared_except

- zellij-server/src/tab/mod.rs
Hi @imsnif, I found something interesting after I walked around the code base.
Because `\0` is not allowed here,
https://github.com/zellij-org/zellij/blob/5793af7655b327f6cbd6f68a26afe59e470dc366/zellij-server/src/tab/mod.rs#L2610-L2611
it wouldn't step in this branch below.
https://github.com/zellij-org/zellij/blob/5793af7655b327f6cbd6f68a26afe59e470dc366/zellij-server/src/panes/terminal_pane.rs#L653-L656
I don't know if this is on purpose or just an oversight, if this is on purpose, I will close this pr, thanks.
Related to #1817
> allow terminating char to clear search term

- zellij-server/src/panes/terminal_character.rs
This PR fixes #1802 by simply applying the ansi code for normal intensity first and then reapplying bold if appropriate.
Should I write a test for this? I didn't quite find anything close to it to base a implementation on, but would be happy to do so with some help :grin:.
https://user-images.githubusercontent.com/12203476/196070255-27ed6064-653b-45e0-ae30-341bbe46c1a2.mp4
> Reset dim SGR independently from bold

- zellij-server/src/panes/active_panes.rs
- zellij-server/src/panes/floating_panes/mod.rs
- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/mod.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/panes/tiled_panes/mod.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__move_floating_pane_focus_sends_tty_csi_event.snap
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__move_pane_focus_sends_tty_csi_event.snap
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__move_pane_focus_with_sends_tty_csi_event.snap
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__toggle_floating_panes_off_sends_tty_csi_event.snap
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__toggle_floating_panes_on_sends_tty_csi_event.snap
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__toggle_floating_panes_sends_tty_csi_event.snap
- zellij-server/src/tab/unit/tab_integration_tests.rs
This implements https://github.com/zellij-org/zellij/issues/1851
To test:
```
echo -e "\033[?1004h" && cat
```
And then move focus between Zellij panes.
This feature is also aware of floating panes being toggled on/off, however focusing a different tab is not considered an unfocus event for the unfocused tab.
> feat(terminals): send focus in/out events to terminal panes

- CHANGELOG.md
- zellij-server/src/lib.rs
- zellij-server/src/logging_pipe.rs
- zellij-server/src/os_input_output.rs
- zellij-server/src/panes/tiled_panes/mod.rs
- zellij-server/src/pty.rs
- zellij-server/src/route.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/wasm_vm.rs
and replace it with variations of `Err....non_fatal()` to preserve more information in the error log messages.
> errors: Remove `log::error` in server

- zellij-utils/src/consts.rs
The temp folder for storing logs etc. is currently hard-coded to `/tmp`, which is not very portable as this directory doesn't exist on some platforms (e.g. Android). This PR changes to use `temp_dir` from `std::env`, which uses the exact same path as we do now on non-Android Unix systems, but a special Termux path on Android.
This helps with #1021.
> fix: use `temp_dir` for getting temp folder

- zellij-server/src/wasm_vm.rs
- zellij-utils/src/input/plugins.rs
Improves error output when failing to load plugins for some reason. Instead of merely stating that "resolving wasm bytes" failed, we preserve the `io::Error` thrown by the `std` functions involved in trying to read the plugin.
Converts the previous error output:
```
╰─▶ Program terminates: a fatal error occured
Caused by:
0: failed to start plugin PluginConfig {
path: "/home/user/code/zellij.nvim/mode-logger/target/wasm32-wasi/debug/mode-logger.wasm",
run: Pane(
None,
),
_allow_exec_host_cmd: false,
location: File(
"/home/user/code/zellij.nvim/mode-logger/target/wasm32-wasi/debug/mode-logger.wasm",
),
} for client 1
1: cannot resolve wasm bytes
```
Into something a bit more user friendly:
```
╰─▶ Program terminates: a fatal error occured
Caused by:
0: failed to start plugin PluginConfig { …
```
> Fix: better error reporting when failing to load plugins (#1912)

- CHANGELOG.md
- Cargo.toml
because the lack of debug symbols makes the panic backtrace completely useless. It will show a long list of unknown locations then.
Except for a minor space saving of 3-4 MB, debug symbols don't have any negative side-effects for our application that we're aware of.
Note that while the presence of debug symbols allows for backtraces that name the functions involved in the error, they don't contain the exact location in the source files where the error originated (line/column numbers). To enable this, the [`debug`][1] profile setting must be enabled, which will increase the binary size dramatically (>80 MB in my tests). We don't do that, because the current situation is good enough for our debugging purposes.
[1]: https://doc.rust-lang.org/cargo/reference/profiles.html#debug
> cargo: Don't strip release binary

- Cargo.lock
- Cargo.toml
- zellij-utils/Cargo.toml
Thanks to the swift action from Wez (not using @ here to avoid spamming his inbox), https://github.com/wez/wezterm/pull/2694 has been merged and `termwiz` v0.19.0 has been [released](https://crates.io/crates/termwiz/0.19.0) with the fix. This PR bumps the dependency version to v0.19.0 to take advantage of it.
This is part of the effort towards fully resolving #1021, and it should be _much_ less disruptive compared to #1833.
> chore(deps): bump termwiz to 0.19.0

- .github/workflows/nix.yml
Continuing the conversation from: https://github.com/zellij-org/zellij/pull/1896
This will remove the MSRV CI check.
> chore(ci): remove msrv check

- CHANGELOG.md
- zellij-server/src/terminal_bytes.rs
- zellij-utils/src/errors.rs
This fixes a bug where, upon successfully quitting zellij, the log would contain error messages from the `async` tasks associated with the PTYs about failing to send a message to the Screen.
The errors look like this in the logs:
```
INFO   |zellij_client            | 2022-11-09 08:35:43.856 [main      ] [/var/home/har7an/.cargo/registry/src/github.com
-1ecc6299db9ec823/zellij-client-0.32.0/src/lib.rs:393]: Bye from Zellij! 
INFO   |zellij_server::wasm_vm   | 2022-11-09 08:35:43.856 [wasm      ] [/var/home/har7an/.cargo/registry/src/github.com
-1ecc6299db9ec823/zellij-server-0.32.0/src/wasm_vm.rs:326]: wasm main thread exits 
ERROR  |zellij_utils::errors::not| 2022-11-09 08:35:43.857 [async-std/runti] [/var/home/har7an/.cargo/registry/src/githu …
```
> Errors: Ignore errors from async when quitting

- CONTRIBUTING.md
As pr #1898 changes log path from the hardcoded `/temp` to `std::env::temp_dir()`, update contributing.md to avoid unnecessary misleading.
> Update log path in contributing doc

- zellij-server/src/pty.rs
In some environment, the SHELL environemnt variable is not exists. It causes a panic that is reported as #1722. Use generic shell (/bin/sh) to prevent the panic.
> fix(pty): use /bin/sh when SHELL env variable not found (#1722)

- zellij-server/src/tab/mod.rs
Fixes https://github.com/zellij-org/zellij/issues/1930
> fix(panes): ensure ejected pane always has a frame

- default-plugins/compact-bar/src/line.rs
- default-plugins/compact-bar/src/main.rs
- default-plugins/compact-bar/src/tab.rs
Same changes as #1658 but for the compact-bar plugin.
> fix(compact-bar): mouse-click in simplified-ui

- example/themes/catppuccin.kdl
Fixed an issue where the white and black palettes were inverted.
> fix(themes/catppuccin): black and white inverted

- zellij-server/src/os_input_output.rs
Fixes https://github.com/zellij-org/zellij/issues/1781
As per @raphCode 's excellent analysis in the issue comments, since the SSH session seems not to close the controlling terminal, after its buffer is filled, the client thread gets blocked printing to STDOUT, and then in turn the entire router thread *on the Zellij server* gets blocked when trying to send messages to the client.
Instead of sending messages directly to the client from the server, we now employ a separate thread to send messages to each client. This thread has its own buffer (50 messages), and once that buffer is filled, we stop sending messages to this particular client (essentially "forget" about it). If the client ever picks up its end of the IPC socket again, we send it one last "Buffer full" message before telling …
> fix(router): handle client buffer overflow

- src/sessions.rs
> fix: empty session name

- src/tests/e2e/snapshots/zellij__tests__e2e__cases__detach_and_attach_session.snap
- src/tests/e2e/snapshots/zellij__tests__e2e__cases__mirrored_sessions-2.snap
- src/tests/e2e/snapshots/zellij__tests__e2e__cases__mirrored_sessions.snap
- zellij-server/src/panes/floating_panes/mod.rs
- zellij-server/src/panes/tiled_panes/mod.rs
- zellij-server/src/tab/mod.rs
This fixes two bugs:
1. When closing a pane, now the most recently focused pane will be focused - rather than the first pane in the tab.
2. When switching tabs, the focused pane will be remembered
> fix(panes): focus change when closing and between tabs

- CHANGELOG.md
- zellij-utils/src/errors.rs
The `errors::LoggableError` trait provides the `to_log` method as convenience function to log error messages easily. It is increasingly used throughout the zellij codebase, either directly or indirectly from the `non_fatal` function.
Previously, the log messages generated by `to_log` would look something like this:
```
ERROR  |zellij_utils::errors::not| 2022-12-05 21:22:07.662 [stdin_handler] [zellij-utils/src/errors.rs:130]:  a non-fatal error occured
Caused by:
[ ... ]
```
The log output tells us that the error occured at `zellij-utils/src/errors.rs:130`, which is in fact wrong: This is only the location where `to_log` calls `log::error!` to log the actual message content. It loses information about where the error originated.
This PR changes the way the messages are logged, and …
> errors: Maintain caller location in `to_log`

- zellij-client/src/input_handler.rs
- zellij-client/src/lib.rs
- zellij-client/src/stdin_ansi_parser.rs
- zellij-client/src/stdin_handler.rs
- zellij-utils/src/errors.rs
When Zellij loads, it queries the terminal emulator for its default colors and its pixel to cell ratio. Since it gets the responses over STDIN, we must drop all user input in the time that this query happens - otherwise it will get mixed up. For that reason the first 0.5 seconds after Zellij loads, input gets lots.
We can't do anything about that, but this PR communicates this to the user, showing a brief loading prompt while this happens so they know not to start typing.
> feat(ux): show loading screen

- CHANGELOG.md
- zellij-server/src/panes/tiled_panes/tiled_pane_grid.rs
The last release introduced some changes to the resize code. Part of these changes broke the behavior for resizing in combination with plugin panes. This hotfix repairs the resize and makes it work correctly with (flexibly-sized) plugin panes.
> Hotfix: Resize with plugin panes

- zellij-server/src/tab/mod.rs
> fix: properly end selection with copy_on_select = false

- src/commands.rs
- src/sessions.rs
- zellij-server/src/panes/grid.rs
1. https://github.com/zellij-org/zellij/blob/3da1cbf95c34283091186fd54926673fe2ec10f6/zellij-server/src/panes/tiled_panes/tiled_pane_grid.rs#L1168-L1178
first_rect.cols.inner == 1.
Between `split_vertically()` and `relayout()`, there is a `change_size()` call. New pane usually has a frame,so `get_content_columns()` returns 0, `change_size()` is skipped.
However if you set `pane_frames false` and vertically split the right most pane, `get_content_columns()` returns 1.`change_size()` calls `drain_until(1)` for each row.
Finally, `drain_until(1)` discard first widechar and all characters behind it.
2. `ZELLIJ_SOCK_DIR.join(name)` should be a valid filename in directory `ZELLIJ_SOCK_DIR`,so name cannot equals to "." or "..", as well as contains '/'. 
3. `zellij -s ''` Session name cannot be …
> fix 3 bugs

- CHANGELOG.md
- zellij-server/src/plugins/wasm_bridge.rs
- zellij-server/src/pty.rs
- zellij-server/src/route.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/layout_applier.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/tab/unit/tab_integration_tests.rs
- zellij-server/src/tab/unit/tab_tests.rs
Removes a bunch of `unwrap` statements in different parts of the `zellij-server` code and replaces them with `Result`-based error propagation instead.
> Errors: less unwrap in server

- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
To fix #2065 , expand characters in tab name and pane name
> Support UTF-8 character in tab name and pane name

- CHANGELOG.md
- xtask/src/pipelines.rs
- zellij-server/src/lib.rs
- zellij-server/src/os_input_output.rs
- zellij-utils/src/channels.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/ipc.rs
This PR includes a few changes to the behavior when the session server disconnects a client as reaction to the client not handling messages quick enough. This happens for example when the system is under high load or the terminal application is blocked by some sort of user interaction (hence, keeping it from handling server messages). The server will continue sending `ServerToClientMsg` messages to all connected clients via an IPC channel. Currently, if the channel fills up the client is disconnected and a "Buffer full" error message is displayed to the user.
Now, we have a dynamically sized retry queue that stores messages that do not fit into the IPC channel. At the moment the queue is limited to 1000 messages, with the IPC channel itself holding at most 50 messages. This should …
> Improve client disconnect handling

- default-plugins/status-bar/src/main.rs
Closes #2077 
This changes behaviour if `status-bar` is used with `size=1`.
The issue of the status bar not showing with `size=1` arises from using `println!` when reaching the last line.
In this case, `print!` will be used instead.
This will also show the "second layer" of hints when not in normal mode, changing the first line.
Be careful reviewing, it's my first Rust PR 🚀
> Fix status bar not displaying w/ size=1 and show shortcuts

- zellij-server/src/os_input_output.rs
- zellij-utils/src/ipc.rs
As discussed in the last team meeting, this PR performs two minor cleanups:
1. Add a `FIXME` note to the bounded queue between server and client that explains why it has its' current size, and in order to make it easier to find and change if the need arises (again)
2. Don't recommend terminal emulator applications inside error messages. It's fine for users/maintainers to recommend their personal favorite applications and suchlike, but zellij itself remains neutral in this regard
> cleanups around "buffer full" error

- CONTRIBUTING.md
- Cargo.toml
- xtask/src/flags.rs
- xtask/src/pipelines.rs
- zellij-server/Cargo.toml
- zellij-server/src/lib.rs
Fixes https://github.com/zellij-org/zellij/issues/2144
Makes the simplepass compiler opt-in instead of the default compiler for debug mode.
This may be desired due to consistent failure when running the default `cargo x run` command on arm64.
> Make the singlepass compiler opt-in through flags

- example/themes/pencil.kdl
This adds the pencil theme. 
Only a light variant (meant to be used alongside the pencil light theme in your terminal) is available at the moment.
> Add pencil theme

- default-plugins/compact-bar/src/line.rs
- default-plugins/tab-bar/src/line.rs
Fix the color of 'more tabs' message for tab-bar and compact-bar plugins.
Currently: 
Fix:
Thank you.
> Apply correct color on 'more tabs' message

- Cargo.lock
- zellij-utils/Cargo.toml
[termwiz changelog](https://github.com/wez/wezterm/blob/main/termwiz/CHANGELOG.md#termwiz-0200)
fixes #1716
> update termwiz to v0.20.0

- GOVERNANCE.md
This change is a result of an email vote as dictated in the current governance document.
All organization members received an email regarding this change and were asked to vote `yes` (make this change) or `no` (do not make this change). @tlinford was CCed to the email and all responses - I would kindly ask him to confirm this by merging this PR.
We received 8 `yes` votes and zero `no` votes. And so this change is carried.
When I started Zellij, I hoped for it to be a project steered by a small and dedicated group of people. I recruited friends and acquaintances from previous projects. But while many of them contributed significantly to the project (some still do), it has come to pass that running this project and driving it forward has mostly fallen to me.
Right now, I have no income and …
> Project Governance Change

- zellij-server/src/os_input_output.rs
This is dependant on Helix accepting the PR:
https://github.com/helix-editor/helix/pull/5945
> Add Helix editor (`hx`) to editors that support prefix positions

- zellij-server/src/panes/tiled_panes/mod.rs
- zellij-server/src/tab/mod.rs
Closes #2106
Well it started to bother we as well, so I implemented a fix. Instead of focusing the next pane in fullscreen mode, now the corresponding direction is respected.
During the implementation I also saw a small error (the prev focus method used the next focus function instead of the prev focus function;) which I also fixed, but put into a separate commit.
I haven't bothered to add additional tests for these changes, do you want me to add tests as well?
> Fix fullscreen navigation

- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__save_cursor_position_across_resizes.snap
- zellij-server/src/tab/unit/tab_integration_tests.rs
This is a minor fix to address certain edge cases in which we weren't doing the right thing when resizing a (terminal) pane.
This was mostly due to the fact that we were skipping some line reflows because we were wrongly assuming that we'd already done them before.
> fix(grid): glitchy resizes

- .github/ISSUE_TEMPLATE/bug_report.md
Logs on OSX are located in `$TMPDIR` not `/tmp`, this hints to OSX users raising bug reports of where to find the log file
> Update bug_report.md template with OSX log directory

- zellij-server/src/pty.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
Before this fix, especially fast-running command started on startup through a layout would sometimes exit before the layout was applied to a tab. This would result in a command pane that has exited but not "held" - meaning we would be unable to re-run the command or see its exit status.
This fixes it by caching those messages for pending tabs using their tab_ids.
Great find, @har7an !!
> fix(messaging): cache hold pane messages by their tab_id if the tab is not ready

- zellij-server/src/lib.rs
- zellij-server/src/screen.rs
Fixes https://github.com/zellij-org/zellij/issues/2021
This is a regression caused by some performance fixes to starting layouts. These fixes caused a race which made the tab focus instruction get lost.
This fixes it by caching the instructions and reapplying them once there are no more pending tabs in the screen.
> fix(layout): tab focus

- zellij-server/src/unit/screen_tests.rs
- zellij-utils/src/cli.rs
- zellij-utils/src/input/actions.rs
- zellij-utils/src/setup.rs
This fixes the CLI `new-tab` action to also look for layouts in the `layout_dir`, similar to how `--layout` does it.
So now: `zellij action new-tab --layout my-cool-layout` will look for the `my-cool-layout` file first in the `layouts` folder in the config directory and only then try to resolve it as a path.
EDIT: this is a fix for https://github.com/zellij-org/zellij/issues/1969 (and maybe others?)
> fix(cli): new-tab now also looks in layout_dir for layouts

- zellij-server/src/os_input_output.rs
- zellij-server/src/plugins/wasm_bridge.rs
- zellij-server/src/pty.rs
- zellij-server/src/route.rs
- zellij-server/src/unit/snapshots/zellij_server__screen__screen_tests__send_cli_edit_action_with_default_parameters.snap
- zellij-server/src/unit/snapshots/zellij_server__screen__screen_tests__send_cli_edit_action_with_line_number.snap
- zellij-server/src/unit/snapshots/zellij_server__screen__screen_tests__send_cli_edit_action_with_split_direction.snap
- zellij-utils/src/cli.rs
- zellij-utils/src/input/actions.rs
- zellij-utils/src/input/command.rs
- zellij-utils/src/input/layout.rs
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__pane_template_with_bare_propagated_to_its_consumer_edit.snap
- zellij-utils/src/input/unit/snapshots/zellij_utils__input__layout__layout_test__pane_template_with_command_propagated_to_its_consumer_edit.snap
- zellij-utils/src/kdl/kdl_layout_parser.rs
Fixes https://github.com/zellij-org/zellij/issues/2016 and https://github.com/zellij-org/zellij/issues/2044
This sets the cwd when editing a file to the current folder (if opened through a pane or through a new-tab action) instead of to the session cwd as was up until now.
> fix(cli): edit cwd

- src/commands.rs
- src/main.rs
- zellij-server/src/pty.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-utils/src/input/actions.rs
Fixes https://github.com/zellij-org/zellij/issues/2187
This PR does two things:
1. We now take the default shell from the default config when opening a new tab (if it's configured)
2. We now take the layout_dir from the default config when looking for new layouts while opening a new tab with the `zellij action new-tab` cli action.
> fix(new-tab): get config parameters from config file

- zellij-server/src/os_input_output.rs
Fixes https://github.com/zellij-org/zellij/issues/2116
This was due to the `sysinfo` crate reporting permission denied as an empty path. We now check for this before returning the path.
> fix(pty): report no-cwd for empty path returned from sysinfo

- zellij-server/src/os_input_output.rs
- zellij-server/src/panes/floating_panes/mod.rs
- zellij-server/src/panes/tiled_panes/mod.rs
- zellij-server/src/tab/layout_applier.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/tab/unit/tab_integration_tests.rs
- zellij-server/src/tab/unit/tab_tests.rs
- zellij-server/src/unit/screen_tests.rs
This adds a report of pixel sizes (`ws_xpixel` and `ws_ypixel`) to our window size change ioctl.
This might be helpful to certain applications who don't use `XTSMGRAPHICS` queries for this purpose (which Zellij supported since Sixel support was introduced).
> fix(sixel): report pixel size in winsize change ioctl

- Cargo.lock
- zellij-utils/Cargo.toml
- zellij-utils/src/input/layout.rs
- zellij-utils/src/input/plugins.rs
- zellij-utils/src/input/unit/layout_test.rs
- zellij-utils/src/kdl/kdl_layout_parser.rs
- zellij-utils/src/kdl/mod.rs
Using URL file schema for plugin location is currently broken in a couple different ways:
- Naively converting URL path to a `PathBuf` doesn't decode the percent encoded URL. This makes any path with "spaces" or percent encoded characters break.
- Using `path` or now w/ `to_file_path` always returns an "absolute" `PathBuf`. The root prefix is now stripped when adding it to the config directory for relative lookup.
I've tested both relative lookup `file:plugin.wasm` as well as absolute path w/ spaces and both now work.
> Fix plugin location path decoding from Url

- zellij-server/src/os_input_output.rs
Better to log an error and open a pane in the current directory than to crash the entire app...
> fix(pty): do not crash when unable to set cwd

- zellij-utils/src/input/options.rs
Previously `auto_layout false` didn't work through the cli (eg. `zellij options --auto-layout false`). Now it does.
> fix(cli): make auto_layout work through the cli

- .github/workflows/e2e.yml
- .github/workflows/release.yml
- CONTRIBUTING.md
- docs/RELEASE.md
- xtask/src/build.rs
- xtask/src/flags.rs
- xtask/src/main.rs
- xtask/src/pipelines.rs
Zellij is a complex application, consisting of multiple subcrates that need to be released/published separately, along with a few application assets such as plugins, which are usually bundled with the application. For this reasons, it has depended for a long time now on external build-tools such as `cargo-make`/`makers`.
Recent contributions to the project have necessitated a different handling of these application assets (in particular: The bundled plugin binaries, see #1924) and introduced a new build system, `xtask`, to replace the previous `cargo-make` for a plethora of reasons (See #2012). All of these changes, although not obvious at first glance, introduce risk and uncertainty to the release process.
This is especially problematic because releasing a zellij version is not an atomic …
> Feature: simulate publishing

- zellij-server/src/screen.rs
Fixes https://github.com/zellij-org/zellij/issues/2234 and similar situations when applying layout
This started happening because we separated the layout application and tab creation to two different steps (in preparation for applying layouts at runtime and to make swap layouts easier). This opened up some potential for races. This fix addresses the immediate concern, and we might want to add some UI indication to it in the future so that we won't be able to close tabs that are "pending".
> fix(screen): hold and applylayout races

- zellij-server/src/tab/mod.rs
Fixes https://github.com/zellij-org/zellij/issues/2262
This happened because some left-over logic from a previous paradigm I was experimenting with. Removed it and it works as expected now.
> fix(panes): closing a stacked pane should relayout

- Cargo.lock
- zellij-utils/Cargo.toml
When a client connects to the zellij server, a Unix socket is created. However, a bug in version 1.1.1 and earlier of the interprocess crate used for interprocess communication (IPC) prevented the socket from being properly disposed of after use, which generated a descriptor leak. The bug was fixed in version 1.2.0 of the interprocess crate. To ensure that the zellij client and server use the latest interprocess crate version and properly dispose of the Unix socket upon a client's disconnection, it's necessary to upgrade the zellij-utils crate to use interprocess library version 1.2.1.
> Fixed issue #1948

- default-plugins/tab-bar/src/line.rs
- default-plugins/tab-bar/src/main.rs
- zellij-client/src/lib.rs
- zellij-server/src/unit/snapshots/zellij_server__screen__screen_tests__send_cli_rename_tab.snap
- zellij-server/src/unit/snapshots/zellij_server__screen__screen_tests__send_cli_undo_rename_tab.snap
- zellij-utils/src/data.rs
- zellij-utils/src/input/config.rs
- zellij-utils/src/input/theme.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__default_config_with_no_cli_arguments.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_env_vars_override_config_env_vars.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_keybinds_override_config_keybinds.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_plugins_override_config_plugins.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_themes_override_config_themes.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_ui_config_overrides_config_ui_config.snap
Summary
---
This patch adds a `config.ui.pane_frames.hide_session_name` parameter to hide session name from the the Zellij (<session_name>) prefix, as requested in issue https://github.com/zellij-org/zellij/issues/2172
As discussed in https://github.com/zellij-org/zellij/pull/2300, I have adjusted the issue scope to only give the option hide the session name while keeping the tools name in the tab-bar prefix.
I'm open to add tests for this functionality, I would however appreciate guidance on where and how to add those specific tests. Thanks!
> Add option to hide session name in tab-bar (deriving from #2172)

- zellij-utils/src/input/actions.rs
Fixes https://github.com/zellij-org/zellij/issues/2280
Before this fix, when opening a new tab with a layout that did not itself have swap layouts, we would default to the swap layouts of the original session layout. This is a behaviour we never want and this PR removes it.
> fix(layouts): don't default to default swap layouts on new-tab action

- zellij-server/src/tab/unit/snapshots/zellij_server__tab__tab_integration_tests__when_applying_a_truncated_swap_layout_child_attributes_are_not_ignored.snap
- zellij-server/src/tab/unit/tab_integration_tests.rs
- zellij-utils/src/input/layout.rs
Fixes https://github.com/zellij-org/zellij/issues/2292
How this relates to the issue at hand is... involved. But it comes down to this bug:
When reapplying this layout to existing panes:
```kdl
layout {
tab {
pane borderless=true
}
}
```
We identify the `tab` node as its own pane, and remove the `pane borderless=true` completely as one pane too many (since this layout can potentially be applied to any number of panes). While this behaviour is correct for panes without attributes (eg. borderless) it removes those attributes if they exist.
This fix makes sure we always take the deepest "non-logical-container" pane when truncating a layout to fit the panes on screen.
> fix(layouts): nested attribute truncating

- zellij-server/src/os_input_output.rs
Fixes https://github.com/zellij-org/zellij/issues/2335 and https://github.com/zellij-org/zellij/issues/2302
This was happening because we weren't properly treating command strings that had spaces. This is a partial fix, fixing the most common cases: namely commands with one or more flags. It does not fix cases with substrings (eg. `nvim -c "set number"`), because I think this is a bit excessive and sets us down a rabbit hole of command line argument parsing support.
> fix(scrollback-editor): properly invoke editor when command includes spaces

- zellij-server/src/screen.rs
This is a bug exposed by the recent asynchronous plugin loading change. It introduced a race between focusing tabs and their layout being applied. This change makes tab changes during a pending state atomic.
> fix(layouts): focus tab race

- zellij-server/src/panes/tiled_panes/mod.rs
Fixes https://github.com/zellij-org/zellij/issues/2271
This was happening because there was an explicit focus change when setting a plugin unselectable (as we do with the default tab and status-bar) that did not check whether the focus of the client actually needed to be changed (only true if the client is focused on the unselectable plugin).
> fix(layout): pane focus in stack

- zellij-server/src/plugins/wasm_bridge.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/tab/unit/tab_tests.rs
Fixes https://github.com/zellij-org/zellij/issues/2118
This fix includes 2 bug fixes, each of which solves this one individually but better to include them both as they also solve other stuff:
1. When sending key presses to a plugin pane, we now make sure to include the `ClientId` of the client originating the keypress. This is so that the keypress won't default to being sent to all plugins and thus cause the above issue.
2. ~~We now make sure to clean up lingering plugins from memory when their originating client disconnects and not just when the program ends or the plugin exits.~~ (EDIT: this was found to be harmful when detaching and so I undid this change - thank you e2e tests!)
> fix(plugins): prevent Strider from opening double-panes when editing files

- zellij-server/src/lib.rs
- zellij-server/src/tab/unit/tab_integration_tests.rs
fixes #1948 (memory leak)
For each client, a thread `JoinHandle` was being held until the server exits.
As far as I can tell holding on to them explicitly to join them isn't really useful in this case.
Have tested this and observed memory usage stay constant even after `zellij ls` x 10000.
> fix: do not hold on to router thread handle until server exit

- default-plugins/compact-bar/src/line.rs
- default-plugins/compact-bar/src/main.rs
This PR extends the "hide session name" option  from #2301 for the compact-bar plugin.
> fix(plugin): respect hide session option on compact-bar

- zellij-server/src/lib.rs
- zellij-server/src/plugins/mod.rs
- zellij-server/src/pty.rs
- zellij-server/src/route.rs
- zellij-server/src/screen.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-server/src/unit/snapshots/zellij_server__screen__screen_tests__send_cli_new_tab_action_default_params.snap
- zellij-server/src/unit/snapshots/zellij_server__screen__screen_tests__send_cli_new_tab_action_with_name_and_layout.snap
- zellij-server/src/unit/snapshots/zellij_server__screen__screen_tests__send_cli_rename_tab.snap
- zellij-server/src/unit/snapshots/zellij_server__screen__screen_tests__send_cli_undo_rename_tab.snap
- zellij-utils/assets/config/default.kdl
- zellij-utils/src/input/config.rs
- zellij-utils/src/input/options.rs
- zellij-utils/src/input/unit/layout_test.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__cli_arguments_override_config_options.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__cli_arguments_override_layout_options.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__default_config_with_no_cli_arguments-3.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__default_config_with_no_cli_arguments.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_env_vars_override_config_env_vars.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_keybinds_override_config_keybinds.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_options_override_config_options.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_plugins_override_config_plugins.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_themes_override_config_themes.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_ui_config_overrides_config_ui_config.snap
#2205 - supports cwd as option
Screenshot
> Fix 2205 - Support cwd

- docs/ARCHITECTURE.md
Try to keep architecture up-to-date by:
- update file paths
- Remove `Scroll` which does not exist, I think this concept has been evolved into a part of `Grid`
> Update architecture doc

- zellij-utils/src/input/config.rs
- zellij-utils/src/input/layout.rs
- zellij-utils/src/kdl/mod.rs
When I encountered the issue noted in https://github.com/zellij-org/zellij/pull/2411, it was a bit difficult to understand what was happening since the missing file path was not included in the displayed error.
This PR removes `ConfigError::Io` and replaces all usages of it with `ConfigError::IoPath`. Hopefully, this will improve the experience when debugging unexpected errors in the future (although there may be more room to add useful context, such as where in the code these errors are being produced).
> Add file path context to all IO errors in ConfigError

- zellij-utils/src/setup.rs
When I cloned the repo and ran `cargo xtask run` I encountered an issue where the `zellij` was trying to load a themes directory at `~/.config/zellij/themes` that did not exist.
If looks like a recent PR (https://github.com/zellij-org/zellij/pull/2307), removed the `if theme_dir.is_dir() {` that was checking if the theme directory exists before trying to use it. I assume we do want to produce a hard error when the theme dir is specifically specified in the config, so I added an equivalent check that only occurs in the case where the theme dir is **not** specified in the config.
While fixing this, I also noticed that the default themes are applied over the top of the themes specified in the config. Presumably, the opposite is better since it allows overriding the defaults (and is more …
> Fix error loading non-existant themes directory and use default themes as the base when merging

- zellij-server/src/lib.rs
It fails on FreeBSD, making the zellij server quit and the client spin endlessly retrying to connect.
```
INFO   |zellij_client            | 2023-05-04 02:11:28.505 [main      ] [zellij-client/src/lib.rs:143]: Starting Zellij client!
INFO   |zellij_server            | 2023-05-04 02:11:28.516 [main      ] [zellij-server/src/lib.rs:237]: Starting Zellij server!
ERROR  |zellij_utils::errors::not| 2023-05-04 02:11:28.519 [server_listener] [zellij-utils/src/errors.rs:585]: Panic occured:
thread: server_listener
location: At zellij-server/src/lib.rs:281:55
message: called `Result::unwrap()` on an `Err` value: Os { code: 79, kind: Uncategorized, message: "Inappropriate file type or format" }
```
ping @ephemeralriggs – this actually slipped into the latest packaged release…
> Do not unwrap() the sticky bit setting!

- .cargo/config.toml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- rust-toolchain.toml
- src/commands.rs
- src/sessions.rs
- xtask/src/build.rs
- xtask/src/ci.rs
- xtask/src/flags.rs
- xtask/src/main.rs
- xtask/src/pipelines.rs
- zellij-utils/Cargo.toml
- zellij-utils/src/lib.rs
Updates the rust toolchain to 1.67 and updates a few dependencies on the way. Fixes #2295 partially.
I chose to go with Rust 1.67 because on the one hand every rust version update brings the potential chance of breaking zellij in unexpected ways, and on the other hand Rust 1.68 doesn't bring new features that are particularly interesting for us.
> Use rust 1.67

- zellij-utils/src/setup.rs
#2421  change the output `CONFIG FILE` to `LOOKING FOR CONFIG FILE FROM`, hopefully, this change could avoid the confusion
> Fix issue 2421 - Update config file output

- zellij-server/src/output/mod.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/tab/unit/tab_integration_tests.rs
This is a fix to some for https://github.com/zellij-org/zellij/issues/1903 - specifically for the case where we blink the cursor on backspace through an SSH session. This was happening because we were hiding the cursor before every dirty render, even if the dirty render did not have any visual assets (in this case, it just had the ANSI ring bell instruction).
> fix(output): do not hide cursor on a render that does not include visual assets

- zellij-server/src/screen.rs
Previously, `LaunchOrFocus` plugin would only work if the user was in the same tab as the plugin - not good!
> fix(screen): focus tab as well as pane when launching existing plugin

- zellij-server/src/plugins/mod.rs
- zellij-server/src/plugins/unit/plugin_tests.rs
- zellij-server/src/plugins/wasm_bridge.rs
- zellij-server/src/plugins/zellij_exports.rs
- zellij-server/src/screen.rs
- zellij-utils/src/errors.rs
The notify task can be a bit heavy at times, let's only start it if a plugin explicitly requested HD events.
> fix(plugins): only listen to hd if a plugin is subscribed to hd events

- src/tests/e2e/remote_runner.rs
- zellij-server/src/lib.rs
- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/plugin_pane.rs
- zellij-server/src/panes/terminal_character.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/panes/unit/grid_tests.rs
- zellij-server/src/panes/unit/search_in_pane_tests.rs
- zellij-server/src/panes/unit/terminal_pane_tests.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/layout_applier.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/tab/unit/tab_integration_tests.rs
- zellij-server/src/tab/unit/tab_tests.rs
- zellij-server/src/unit/screen_tests.rs
These unhandled ANSI instruction logs are very useful, but only when debugging. Otherwise they really get in the way.
> fix(logs): suppress debug logs when not debugging

- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__start_or_reload_plugin.snap
- zellij-server/src/plugins/zellij_exports.rs
- zellij-server/src/route.rs
- zellij-server/src/screen.rs
- zellij-utils/src/cli.rs
- zellij-utils/src/input/actions.rs
- zellij-utils/src/input/layout.rs
- zellij-utils/src/kdl/kdl_layout_parser.rs
- zellij-utils/src/kdl/mod.rs
This allows loading both relative URLs and shell env variables (eg. starting with `~`).
> fix(plugins): allow loading relative urls

- Cargo.lock
- zellij-server/src/plugins/wasm_bridge.rs
- zellij-server/src/plugins/watch_filesystem.rs
- zellij-utils/Cargo.toml
- zellij-utils/src/lib.rs
Mostly a drop in replacement for notify to prevent cross channel and wasm spamming of events.
> performance(plugins): use a debounced fs watcher

- default-plugins/fixture-plugin-for-tests/src/main.rs
- zellij-server/src/panes/plugin_pane.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/plugins/unit/plugin_tests.rs
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__close_plugin_pane_plugin_command.snap
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__close_terminal_pane_plugin_command.snap
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__focus_plugin_pane_plugin_command.snap
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__focus_terminal_pane_plugin_command.snap
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__rename_plugin_pane_plugin_command.snap
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__rename_tab_plugin_command.snap
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__rename_terminal_pane_plugin_command.snap
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__show_self_plugin_command.snap
- zellij-server/src/plugins/zellij_exports.rs
- zellij-server/src/route.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-tile/src/shim.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/input/actions.rs
This PR adds:
* show_self (opposite of hide_self)
* rename pane
* rename tab
* close pane with id
* focus pane with id
More documentation will come before the release.
> feat(plugins): more plugin api methods

- default-plugins/fixture-plugin-for-tests/src/main.rs
- default-plugins/strider/src/main.rs
- default-plugins/strider/src/search/search_state.rs
- zellij-tile/src/shim.rs
Change some signatures in zellij-tile to make things a little bit friendlier to the developer.
> refactor(plugins): improve api

- zellij-tile/src/shim.rs
- zellij-utils/src/data.rs
Add some initial in-line documentation to make things easier.
> docs(plugins): document the zellij-tile events and commands api

- zellij-utils/src/setup.rs
There is issue found as follows:
> Hotfix: theme issue in `v0.37.0`

- default-plugins/compact-bar/src/main.rs
- default-plugins/compact-bar/src/tab.rs
- default-plugins/tab-bar/src/main.rs
- default-plugins/tab-bar/src/tab.rs
Caching the click position wasn't working across multiple plugin instances, so clicking (always in the same column) wasn't causing the tab to be switched.
Also a couple of refactors:
- move the code with the tab switching logic to `update`
- avoid rendering when calling `switch_tab_to`, since it will happen anyway afterwards
> fix(tab-bar,compact-bar): tab switching with mouse sometimes not working

- default-plugins/status-bar/src/first_line.rs
- default-plugins/status-bar/src/main.rs
- default-plugins/status-bar/src/second_line.rs
- default-plugins/status-bar/src/tip/cache.rs
- default-plugins/status-bar/src/tip/data/compact_layout.rs
- default-plugins/status-bar/src/tip/data/edit_scrollbuffer.rs
- default-plugins/status-bar/src/tip/data/floating_panes_mouse.rs
- default-plugins/status-bar/src/tip/data/quicknav.rs
- default-plugins/status-bar/src/tip/data/sync_tab.rs
- src/tests/e2e/cases.rs
- src/tests/e2e/snapshots/zellij__tests__e2e__cases__lock_mode.snap
- src/tests/e2e/snapshots/zellij__tests__e2e__cases__mirrored_sessions-2.snap
- src/tests/e2e/snapshots/zellij__tests__e2e__cases__scrolling_inside_a_pane.snap
This is an effort to finally solve the "colliding keys" problem.
This adds a new mode to the status bar, basically defaulting to "locked" mode and treating any other non-normal mode as a "sticky" mode. So that whenever a user moves from "locked" to "normal", they will be placed in said sticky mode. When the user then returns from the sticky mode to normal, they will be placed back in locked mode.
This would effectively mean that when most times, Zellij will only take up 1 keybinding (by default `Ctrl g` to enter the sticky mode).
Right now, this is behind a feature flag, but after this I plan to do work to allow plugins to be configurable and users will be able to goggle this off/on.
> feat(ui): new status bar mode

- zellij-server/src/output/mod.rs
- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__alternate_screen_change_size.snap
This fixes some more glitches that happened while resizing. The user facing effects of this are that now when we switch focus for terminals while in full screen, their size will consistently stay the same. This also catches some bugs where we did not redraw our own state properly sometimes, causing a drift between the terminal program state and what appeared on screen.
On the technical side, this was fixed by:
1. Not doing any sort of line wrapping for alternate screen applications
2. Making the output buffer aware of the viewport width and only taking the characters it needs to render and no extras (needed to support 1).
> fix(terminal): properly handle resizes in alternate screen

- zellij-tile/src/shim.rs
While porting harpoon to Zellij as a [plugin](https://github.com/Nacho114/harpoon), I had to know the currently active pane and tab via the `Vec<TabInfo>` and the `PaneManifest`. Since this might be a useful utility function I propose to add them in this PR. 
TL;DR
Given the `PaneManifest` and `Vec<TabInfo>`, I want to easily get the active pane and tab.
> Added utility functions to find active pane and tab

- zellij-server/src/output/mod.rs
- zellij-server/src/panes/grid.rs
- zellij-server/src/ui/pane_boundaries_frame.rs
Fixes https://github.com/zellij-org/zellij/issues/1625
For some reason (which I admittedly cannot fully explain) when we pre-allocate memory for the terminal viewport, scrollback and each line therein that memory is not deallocated when its container is dropped.
Removing this pre-allocation doesn't harm performance in a noticeable way and plugs this leak. If any Rustacean reading this has ideas for why this is happening, I'd be very curious to hear them. :)
> fix(performance): plug memory leak

- default-plugins/status-bar/src/second_line.rs
- zellij-server/src/route.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-utils/assets/config/default.kdl
- zellij-utils/src/cli.rs
- zellij-utils/src/input/actions.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/plugin_api/action.proto
- zellij-utils/src/plugin_api/action.rs
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__default_config_with_no_cli_arguments.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_env_vars_override_config_env_vars.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_plugins_override_config_plugins.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_themes_override_config_themes.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_ui_config_overrides_config_ui_config.snap
The main reason for doing this is to allow the session-manager to always show itself in the focused tab.
The way we do this is adding a `move_to_focused_tab true` attribute to `LaunchOrFocusPlugin`, as well as a matching cli argument (`--move-to-focused-tab`) to the `zellij action launch-or-focus-plugin` command.
> feat(plugins): optionally move plugin to focused tab

- zellij-utils/src/kdl/mod.rs
This fixes an oversight where it was impossible to start a floating pane or a pane with a title from a keybinding.
So now, we can do:
```kdl
keybinds {
// ...
shared {
Run "htop" "--tree" {
floating true;
name "my awesome floating pane";
}
}
//...
}
```
> fix(keybinds): add 'floating' and 'name' to the Run command keybinding

- zellij-server/src/panes/floating_panes/mod.rs
- zellij-server/src/plugins/mod.rs
- zellij-server/src/pty.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/layout_applier.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/tab/unit/tab_integration_tests.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-utils/src/input/layout.rs
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__default_config_with_no_cli_arguments.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_env_vars_override_config_env_vars.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_plugins_override_config_plugins.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_themes_override_config_themes.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_ui_config_overrides_config_ui_config.snap
Fixes https://github.com/zellij-org/zellij/issues/2674 and some other similar issues.
The issue was that the plugin configuration was not used as part of the plugin identification.
This PR also introduces the following reserved words that cannot be used as plugin user configuration (because they will collide with various zellij configurations): "hold_on_start", "hold_on_close", "cwd", "name", "direction", "floating", "move_to_focused_tab".
> fix(plugins): make sure configuration is also part of the plugin keys

- zellij-server/src/plugins/zellij_exports.rs
- zellij-tile/src/shim.rs
- zellij-utils/src/data.rs
- zellij-utils/src/plugin_api/action.proto
- zellij-utils/src/plugin_api/action.rs
- zellij-utils/src/plugin_api/plugin_command.proto
- zellij-utils/src/plugin_api/plugin_command.rs
Fixes https://github.com/zellij-org/zellij/issues/2695
> fix(plugins): remove protobuf duplications

- default-plugins/session-manager/src/main.rs
- default-plugins/session-manager/src/session_list.rs
- zellij-server/src/panes/floating_panes/mod.rs
- zellij-server/src/panes/plugin_pane.rs
- zellij-server/src/plugins/zellij_exports.rs
This:
1. Fixes the permission request screen for plugins so that it renders properly on one-liner plugins
2. Fixes the session-manager built-in plugin so that it properly clears its own state after the user selects a session/tab/pane to switch to
3. Adds the `SwitchSession` plugin command to the permission system
> fix(plugins): various ui fixes

- zellij-server/src/panes/floating_panes/mod.rs
- zellij-server/src/panes/tiled_panes/mod.rs
- zellij-server/src/screen.rs
- zellij-utils/src/cli.rs
Fixes https://github.com/zellij-org/zellij/issues/2733
This problem was happening because in certain cases, when switching focus between tabs we'd forgo some initialization steps that made sure for example that the proper pane in the stacked panes was focused.
> fix(panes): refocus pane properly on tab change

- zellij-server/src/plugins/wasm_bridge.rs
- zellij-server/src/screen.rs
Hey!
I got the following compiler warnings while building `Zellij` `0.38.0` for Arch Linux:
```
warning: variable does not need to be mutable
--> zellij-server/src/plugins/wasm_bridge.rs:412:25
|
412 |         for (plugin_id, mut current_size) in self.cached_resizes_for_pending_plugins.iter_mut() {
|                         ----^^^^^^^^^^^^
|                         |
|                         help: remove this `mut`
|
= note: `#[warn(unused_mut)]` on by default
warning: variable does not need to be mutable
--> zellij-server/src/screen.rs:1735:29
|
1735 |                 if let Some(mut already_running_layout) = floating_panes_layout
|                             ----^^^^^^^^^^^^^^^^^^^^^^
|                             |
|                             help: remove this `mut`
warning: …
```
> refactor(server): remove unnecessary mut

- default-plugins/status-bar/src/second_line.rs
- src/tests/e2e/snapshots/zellij__tests__e2e__cases__mirrored_sessions-2.snap
Add status bar hints in `Tab` mode for the new `BreakPane`, `BreakPaneRight` and `BreakPaneLeft` actions.
> fix(status-bar): add break tab hints

- zellij-server/src/output/mod.rs
use hashset instead of vec for changed lines, to avoid output buffer growing indefinitely if  a tab is producing output but does not get rendered
> fix(grid): memory leak with unfocused tabs

- zellij-client/src/input_handler.rs
- zellij-client/src/lib.rs
Fixes https://github.com/zellij-org/zellij/issues/2752
In the recent version we switched how the `Run` keybinding is handled, breaking it into specific "run tiled" and "run floating" variants, and I forgot to make these specific variants block until complete. For this reason, the toggle-full-screen instruction came to the server before the run action and so this did not work. Sorry about that!
> fix(input): block input thread for newtiledpane and newfloatingpane as well

- zellij-server/src/panes/grid.rs
Fixes https://github.com/zellij-org/zellij/issues/2785
This was my bad, and happened when implementing https://github.com/zellij-org/zellij/pull/2654 - most changes in that PR are desired, except the one change where we actually *should* wrap lines while typing when in alternate screen mode.
Incidentally, this was only caught a week after this release because (as far as I understand), neovim 0.9.1 does not rely on this behavior while neovim 0.9.2 (which was released while I was on vacation) does. Anyhoo - we should totally support this, so this is the fix.
> fix(terminal): wrap lines when adding characters in alternate screen

- zellij-utils/src/cli.rs
- zellij-utils/src/consts.rs
> fix(utils): validate session name

- zellij-utils/assets/themes/gruvbox.kdl
Linked to https://github.com/zellij-org/zellij/issues/2790, I have change the FG color for better clarity.
See screenshots.
Before : 
After :
> Fix: fg color for gruvbox light theme

- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/setup.rs
> fix: display parsing error for kdl files located under the 'themes' directory

- Cargo.lock
- zellij-server/Cargo.toml
- zellij-utils/Cargo.toml
Another small PR updating a dependency. Appears to be used in an API-compatible way already, no code changes were required.
> chore: update uuid dependency to 1.4.1

- zellij-server/src/lib.rs
- the upgrade from wasmer 2.3 to 3.1 brought in a version of cranelift-codegen with a security vulnerability: https://github.com/bytecodealliance/wasmtime/security/advisories/GHSA-ff4p-7xrq-q5r8
- for the removal of doubt: we caught this issue before releasing a version, so there is no version with this vulnerability
- we intend to move away from wasmer, and so decided on this temporary mitigation which does not affect our performance rather than another lengthy breaking upgrade
> fix(plugins): address potential security issue

- zellij-client/src/stdin_ansi_parser.rs
- zellij-server/src/plugins/plugin_loader.rs
- zellij-utils/src/consts.rs
Also use the zellij version to cache compiled plugin artifacts.
This avoids breakage with the recent updates to the plugin system's dependencies, by ensuring we do not reuse artifacts that were built with a different version of wasmer, cranelift, etc.
> fix(plugins): add zellij version to cached artifact path

- zellij-client/src/input_handler.rs
- zellij-client/src/lib.rs
- zellij-client/src/stdin_ansi_parser.rs
- zellij-utils/src/errors.rs
I noticed some screen flickering/tearing while using zellij and an code editor like neovim at the same time. Apparently it's possible to block the terminal emulator from updating the window: 
https://gist.github.com/christianparpart/d8a62cc1ab659194337d73e399004036
I tested the terminal feature detection on foot, kitty, alacrity and st, it does recognize successfully when the feature is available (foot and kitty).
**I did notice visual improvement on a low end laptop**
> feat(client): terminal synchronized output

- zellij-server/src/pty.rs
- zellij-utils/src/session_serialization.rs
In certain edge cases we are not able to properly construct a layout from the current session state. In these cases we should log the failure instead of crashing the app. This is what this change does.
> fix(resurrection): log failure instead of crashing in some edge cases

- zellij-tile/src/shim.rs
I forgot to make auxiliary functions public (`get_focused_tab` and `get_focused_pane`). This is fixed in this PR.
> fix(plugins): make auxiliary functions (get_focused_tab and get_focused_pane) public

- default-plugins/fixture-plugin-for-tests/src/main.rs
- default-plugins/session-manager/src/main.rs
- zellij-server/src/background_jobs.rs
- zellij-server/src/plugins/unit/plugin_tests.rs
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__run_command_plugin_command.snap
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__run_command_with_env_vars_and_cwd_plugin_command.snap
- zellij-server/src/plugins/zellij_exports.rs
- zellij-tile/src/shim.rs
- zellij-utils/assets/prost/api.event.rs
- zellij-utils/assets/prost/api.plugin_command.rs
- zellij-utils/src/data.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/plugin_api/event.proto
- zellij-utils/src/plugin_api/event.rs
- zellij-utils/src/plugin_api/plugin_command.proto
- zellij-utils/src/plugin_api/plugin_command.rs
This adds a new run_command plugin api command. This API will allow plugins to run an arbitrary command on the user's machine (after the user grants them permission) in the background.
These commands will be run, their exit code, STDOUT and STDERR will be collected and sent back to the plugin as the new `RunCommandResult` event. If the plugin is subscribed to this event, it will be able to receive it and react to it as normal.
This API also includes a custom `context` attribute, which is an arbitrary key/value map. This context will not be altered or read by Zellij, but instead transferred back to the plugin with the `RunCommandResult` event. This can be useful for marking a specific request and being able to identify it later (eg. with a custom `request_id` field), marking the timestamp …
> feat(plugins): plugin run_command api

- Cargo.lock
- default-plugins/fixture-plugin-for-tests/src/main.rs
- zellij-server/src/background_jobs.rs
- zellij-server/src/plugins/unit/plugin_tests.rs
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__granted_permission_request_result.snap
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__request_plugin_permissions.snap
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__web_request_plugin_command.snap
- zellij-server/src/plugins/zellij_exports.rs
- zellij-tile/src/shim.rs
- zellij-utils/Cargo.toml
- zellij-utils/assets/prost/api.event.rs
- zellij-utils/assets/prost/api.plugin_command.rs
- zellij-utils/assets/prost/api.plugin_permission.rs
- zellij-utils/src/data.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/lib.rs
- zellij-utils/src/plugin_api/event.proto
- zellij-utils/src/plugin_api/event.rs
- zellij-utils/src/plugin_api/plugin_command.proto
- zellij-utils/src/plugin_api/plugin_command.rs
- zellij-utils/src/plugin_api/plugin_permission.proto
- zellij-utils/src/plugin_api/plugin_permission.rs
This allows plugins to make web-requests (behind a new `WebAccess` permission). The API is similar to the recently added `run_command` API. Allowing users to make http(s) get/post/put/delete requests and receive responses as a `WebRequestResult` event.
Here's an example:
```rust
// ...
let headers: BTreeMap<String, String> = BTreeMap::new(); // http headers
let context: BTreeMap<String, String> = BTreeMap::new(); // will be returned verbatim in the context result
let body = vec![1, 2, 3];
web_request(
"https://example.com/foo?arg1=val1&arg2=val2",
HttpVerb::Get,
headers,
body,
context,
);
// ...
fn update(&mut self, event: Event) -> bool {
match event {
Event::WebRequestResult(status, headers, body, context) => {
eprintln!("status: {:?}", status);
eprintln!("headers: {:?}", headers); …
```
> feat(plugins): web requests api

- src/commands.rs
- src/main.rs
- src/sessions.rs
- zellij-utils/assets/completions/comp.fish
- zellij-utils/src/cli.rs
This pull request addresses https://github.com/zellij-org/zellij/issues/2852 . It implements a `--short` flag for `zellij ls`, that is then used in the fish autocompletion for completing session names without formatting and other information.
> fix(cli): session names only for attach in fish completion

- Cargo.lock
- default-plugins/session-manager/Cargo.toml
- default-plugins/session-manager/src/main.rs
- default-plugins/session-manager/src/resurrectable_sessions.rs
- default-plugins/session-manager/src/ui/components.rs
- zellij-server/src/background_jobs.rs
- zellij-server/src/plugins/zellij_exports.rs
- zellij-server/src/screen.rs
- zellij-tile/src/shim.rs
- zellij-utils/assets/prost/api.event.rs
- zellij-utils/assets/prost/api.plugin_command.rs
- zellij-utils/src/data.rs
- zellij-utils/src/plugin_api/event.proto
- zellij-utils/src/plugin_api/event.rs
- zellij-utils/src/plugin_api/plugin_command.proto
- zellij-utils/src/plugin_api/plugin_command.rs
This adds a new screen to the session manager (exclusively using the recently added UI components) that allows users to resurrect sessions from within Zellij (including a fuzzy find for those sessions):
This also adds two relevant APIs (behind the "change session state" permission):
`delete_dead_session(name: &str)`
and
`delete_all_dead_sessions()`
The `SessioUpdate` plugin event now also includes resurrectable sessions on the machine:
```rust
SessionUpdate(
Vec<SessionInfo>,
Vec<(String, Duration)>, // resurrectable sessions, (name, creation_time)
),
```
> feat(sessions): resurrect sessions through the session-manager (and plugin API)

- default-plugins/session-manager/src/main.rs
- default-plugins/session-manager/src/resurrectable_sessions.rs
- default-plugins/session-manager/src/session_list.rs
- default-plugins/session-manager/src/ui/components.rs
- zellij-client/src/cli_client.rs
- zellij-client/src/lib.rs
- zellij-server/src/plugins/zellij_exports.rs
- zellij-server/src/route.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-tile/src/shim.rs
- zellij-utils/assets/prost/api.action.rs
- zellij-utils/assets/prost/api.plugin_command.rs
- zellij-utils/src/cli.rs
- zellij-utils/src/data.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/input/actions.rs
- zellij-utils/src/ipc.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/plugin_api/action.proto
- zellij-utils/src/plugin_api/action.rs
- zellij-utils/src/plugin_api/plugin_command.proto
- zellij-utils/src/plugin_api/plugin_command.rs
This adds:
1. A new CLI command: `zellij action rename-session <new-name>`
2. A new API for plugins `rename_session(&str)` behind the `ChangeSessionState` permission
3. The ability to change session names through the `session-manager` (`Ctrl o` + `w`).
> feat(ux): allow renaming sessions

- .github/workflows/rust.yml
- zellij-server/src/plugins/mod.rs
- zellij-server/src/plugins/unit/plugin_tests.rs
- zellij-server/src/plugins/wasm_bridge.rs
- zellij-server/src/pty.rs
- zellij-server/src/screen.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-server/src/unit/snapshots/zellij_server__screen__screen_tests__send_cli_launch_or_focus_plugin_action.snap
- zellij-utils/src/errors.rs
Until this PR, new plugins that were launched at runtime always got the cwd that Zellij originally started with. This behavior is very desirable when starting a layout, but is almost never desirable when launching a new plugin.
This PR fixes this.
> fix(plugins): start plugin pane in cwd of focused pane if possible

- zellij-server/src/os_input_output.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-tile/src/shim.rs
This adds some missing documentation to the rust plugin SDK as well as clear up some compilation warnings.
> docs(api): docs for shim.rs

- src/tests/e2e/remote_runner.rs
- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/plugin_pane.rs
- zellij-server/src/panes/terminal_character.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/panes/unit/grid_tests.rs
- zellij-server/src/panes/unit/search_in_pane_tests.rs
- zellij-server/src/panes/unit/terminal_pane_tests.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/layout_applier.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/tab/unit/tab_integration_tests.rs
- zellij-server/src/tab/unit/tab_tests.rs
- zellij-server/src/ui/boundaries.rs
- zellij-server/src/unit/screen_tests.rs
Styled underlines fail to render in text editors like neovim and helix while in a Zellij session. 
This is because `RESET_STYLES` in `terminal_character.rs` sets `styled_underlines` to false. In order to address this, a new parameter is added on `Cursor::new` to read the `styled_underlines` config variable as it's passed down the stack from `Screen` > `Tab` > `TerminalPane` > `Grid`.
I've tried to make this as minimal of a change as possible but some significant boilerplate had to be added.
Finally, I was only able to test this in Neovim. Helix, for whatever reason, ws not rendering styled underlines inside or outside of Zellij. Probably an issue with my config. But if someone else can confirm this works, that would be greatly appreciated.
> Fix styled underlines in editors

- zellij-server/src/plugins/mod.rs
- zellij-server/src/plugins/plugin_loader.rs
- zellij-server/src/plugins/plugin_map.rs
- zellij-server/src/plugins/unit/plugin_tests.rs
- zellij-server/src/plugins/zellij_exports.rs
- zellij-server/src/route.rs
- zellij-server/src/screen.rs
- zellij-utils/assets/prost/api.action.rs
- zellij-utils/src/cli.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/input/actions.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/plugin_api/action.proto
- zellij-utils/src/plugin_api/action.rs
This adds the `LaunchPlugin` keybind, which is just like the `LaunchOrFocus` one, except it always launches a new instance of the plugin.
This also fixes some issues with cwd in plugins (specifically we now do the right thing when opening files/terminals from a different cwd than the one Zellij was started in).
It also adds the plugin's cwd to its title pane for clarity.
> fix(ux): LaunchPlugin and some cwd fixes

- zellij-server/src/os_input_output.rs
Use `refresh_processes_specifics`   will use more cpu. Use refresh_process_specifics instead of refresh_processes_specifics to reduce cpu usage.
> optimize: update refresh prorcess for sysinfo to reduce cpu usage

- src/tests/e2e/remote_runner.rs
- zellij-server/src/background_jobs.rs
- zellij-server/src/lib.rs
- zellij-utils/src/input/options.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__cli_arguments_override_config_options.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__cli_arguments_override_layout_options.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__default_config_with_no_cli_arguments-3.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__default_config_with_no_cli_arguments.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_env_vars_override_config_env_vars.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_keybinds_override_config_keybinds.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_options_override_config_options.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_plugins_override_config_plugins.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_themes_override_config_themes.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_ui_config_overrides_config_ui_config.snap
This adds a `serialization_interval` configuration parameter. Allowing users to set the interval in seconds in which the session serialization (if active) will happen. These serializations are then used in order to resurrect sessions.
The default interval has also been changed from 1 second to 60 seconds.
> feat(config): add serialization interval configuration

- zellij-server/src/plugins/plugin_loader.rs
- zellij-server/src/plugins/wasm_bridge.rs
- zellij-server/src/ui/loading_indication.rs
This fixes an issue where if a plugin crashed, reloading while skipping cash would be impossible without restarting Zellij. This is relevant to the `start-or-reload` command and is mostly used for plugin development.
> fix(plugins): reloading plugin after crash

- zellij-utils/src/cli.rs
I noticed this small typo in the help pages. I'm not familiar with the code so I assumed these comments are also used to populate the help pages. If this is not the case the typo should also be wherever the help page is getting it from.
Great work btw, i'm loving zellij.
> Fix typo in help page

- docs/THIRD_PARTY_INSTALL.md
> docs: Update Arch Linux package URL in THIRD_PARTY_INSTALL.md

- zellij-server/src/screen.rs
- zellij-server/src/ui/loading_indication.rs
This fixes 2 things:
1. Plugin errors will now be properly aligned when displayed in the UI
2. When loading a plugin that does not exist, we'll get a proper error instead of the pane hanging
> fix(plugins): display errors properly

- CHANGELOG.md
- rust-toolchain.toml
- zellij-utils/src/input/layout.rs
Rust 1.75.0 is the current latest release of the Rust language and toolchains. This change is necessary since I have discovered that with the previously used version, 1.67.0, future releases will no longer be possible. The reason is that `cargo publish`, even when using the `--locked` flag, seems to perform its' own package version resolution. During this process it hits an issue with one of our dependencies that has bumped its' MSRV to 1.70.0.
While I think technically this is a bug in the Rust tooling, it's still a nice idea to do the upgrade. The commits in this PR perform the upgrade in "three" steps with Rust versions 1.69, 1.70 and 1.75. I have picked these versions as I think that each of these mentioned something in their `CHANGELOG` that offers a potential benefit or risk to …
> Bump rust version to 1.75.0

- zellij-server/src/panes/grid.rs
cc https://github.com/zellij-org/zellij/issues/2622
First in a series: #3045 (this pr), #3032, #3043
This PR contains targeted improvements to reflow performance. Gives about 3x improvement on a 1MB line, significantly more on a 10MB line (because of quadratic behavior).
I highly recommend reviewing these changes commit-by-commit, as I've carefully tried to make each one standalone and self-consistent.
> Improvements to reflow performance by removing O(n^2) behavior

- CHANGELOG.md
- xtask/src/flags.rs
- xtask/src/pipelines.rs
to allow simulated releases without having to offer a fork of the zellij repo to push the release commit to. This serves multiple purposes:
1. It saves the user from having to provide a writable repo to push the release commit to in the first place
2. When performing multiple subsequent releases, e.g. when a previous run failed near the end, there is no need to clean up said remote (remove the release commit and tags), as no commit was pushed at all
This PR is currently based on #3039 to allow simulating releases using my repo [over here][1]
[1]: https://gitlab.com/hartang/zellij/simulate-release
> xtask: Disable pusing during publish

- src/main.rs
- zellij-server/src/plugins/unit/plugin_tests.rs
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__open_file_floating_plugin_command.snap
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__open_file_plugin_command.snap
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__open_file_with_line_floating_plugin_command.snap
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__open_file_with_line_plugin_command.snap
- zellij-server/src/plugins/zellij_exports.rs
- zellij-server/src/pty.rs
- zellij-server/src/route.rs
- zellij-server/src/screen.rs
- zellij-server/src/unit/snapshots/zellij_server__screen__screen_tests__send_cli_launch_or_focus_plugin_action.snap
- zellij-utils/src/input/actions.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/plugin_api/action.rs
This fixes some edge cases where the working directory was not respected when launching new commands through `zellij run` or new plugins through `zellij plugin`.
> fix(cli): respect cwd in zellij run and zellij plugin

- zellij-server/src/panes/terminal_character.rs
This is a small fix for a recent regression in main (that was not released yet) in which curly underlines were not rendered mid line.
@aidanhs - any chance you could briefly take a look to make sure I didn't ruin any of your improvements?
> fix(terminal): curly underlines mid-chunk

- zellij-server/src/tab/layout_applier.rs
Fixes https://github.com/zellij-org/zellij/issues/3105
This was caused by an inadvertent change when introducing session resurrection in the last release. The fix is to make sure existing panes (eg. the one being broken out of a tab) get priority and get placed in the right place in the default layout when breaking out panes.
> fix(panes): break pane to new tab

- zellij-server/src/plugins/mod.rs
- zellij-utils/assets/prost/api.plugin_command.rs
- zellij-utils/src/data.rs
- zellij-utils/src/plugin_api/plugin_command.proto
- zellij-utils/src/plugin_api/plugin_command.rs
This is mainly so that plugins can send queries and replies to one another.
> feat(plugins): allow piping messages to a specific plugin id

- default-plugins/fixture-plugin-for-tests/src/main.rs
- default-plugins/session-manager/src/new_session_info.rs
- src/commands.rs
- zellij-server/src/plugins/unit/plugin_tests.rs
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__switch_session_plugin_command.snap
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__switch_session_with_layout_and_cwd_plugin_command.snap
- zellij-server/src/plugins/zellij_exports.rs
- zellij-tile/src/shim.rs
- zellij-utils/assets/prost/api.plugin_command.rs
- zellij-utils/src/data.rs
- zellij-utils/src/input/layout.rs
- zellij-utils/src/plugin_api/plugin_command.proto
- zellij-utils/src/plugin_api/plugin_command.rs
This builds on the `switch_session_with_layout` plugin API command, adding an optional "cwd" - allowing plugins to specify the working directory when creating new sessions.
This is more infrastructure for allowing the session-manager / welcome screen to start new sessions with a specific layout in a specific folder.
> feat(plugins): allow specifying the cwd when switching sessions

- zellij-server/src/screen.rs
Fixes https://github.com/zellij-org/zellij/issues/3183 as well as quite a few other stability issues.
The code fix is small, but this finally brings our error reporting system to the same philosophical standpoint as our application business logic: state corruption is fine as long as we can fix it later.
The error we get from this previously-crashing macro happens 100% of the time when the state is corrupted (due to race conditions stemming from our actor-like architecture, and the like). We always know how to fix these state corruptions, and the worst effect that can happen by logging the error instead of crashing is losing one or two keypresses from the user. While this is not ideal and we should introduce some sort of cashing/retry mechanism, this is light years better than crashing in …
> fix(stability): various crashes

- src/commands.rs
- src/main.rs
- zellij-utils/assets/completions/comp.bash
- zellij-utils/assets/completions/comp.fish
- zellij-utils/assets/completions/comp.zsh
- zellij-utils/src/cli.rs
- zellij-utils/src/input/plugins.rs
This adds the `zpipe` alias, which is an alias to `zellij pipe`. If arguments are provided, they will be treated as the plugin alias/path (eg. `zpipe filepicker` or `zpipe https://example.com/my-plugin.wasm`).
This PR also adds the `zellij list-aliases` command which can be used to list all the configured aliases. This is in order to facilitate fast typing and completions when using zpipe.
> chore(integrations): zpipe alias

- default-plugins/fixture-plugin-for-tests/src/main.rs
- zellij-server/src/plugins/mod.rs
- zellij-server/src/route.rs
- zellij-utils/assets/prost/api.action.rs
- zellij-utils/assets/prost/api.pipe_message.rs
- zellij-utils/src/data.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/input/actions.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/plugin_api/action.proto
- zellij-utils/src/plugin_api/action.rs
- zellij-utils/src/plugin_api/pipe_message.proto
- zellij-utils/src/plugin_api/pipe_message.rs
This adds a pipe interface, similar to the one already existing in the command line, to keybindings.
This allows users to bind a `MessagePlugin` action in the keybindings configuration.
eg.
```kdl
bind "Alt w" {
// filepicker is the built-in alias, but any plugin url can be used (eg. https://example.com/my-plugin.wasm)
MessagePlugin "filepicker" {
name "optional_message_name"
payload "optional_message_payload"
should_float true // if this message results in loading a new plugin, should it float
launch_new true // force a new plugin to be launched even if an existing one with this destination/config is running
skip_cache true // if launching a new plugin, skip the plugin cache and force recompiling it (good for development)
title "this will be the pane title if launching a new plugin" …
```
> feat(pipes): allow piping messages to plugins from keybindings

- zellij-utils/src/input/layout.rs
This fixes an issue introduced with plugin aliases recently. The issue was that when swapping layouts, we would not identify the plugin aliases properly and instead just place them randomly around the tab (sometimes in a very bad manner like swapping UI panes such as the status-bar with other plugins). This fixes it by properly comparing aliases regardless of whether we've interpreted them yet or not.
> fix(swap-layouts): properly identify plugin aliases

- zellij-utils/src/cli.rs
I guess that this was only a typo, and it is actually meant to be `p` for "plugin".
(With `r` being taken by "run", this would otherwise never be activated.)
> fix: adjust duplicated cli alias

- zellij-server/src/os_input_output.rs
- zellij-server/src/panes/floating_panes/mod.rs
- zellij-server/src/panes/tiled_panes/mod.rs
- zellij-server/src/pty.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-utils/src/plugin_api/event.rs
Removes some warnings added when we upgraded our Rust version.
> style(fmt): fix warnings

- default-plugins/status-bar/src/first_line.rs
- default-plugins/status-bar/src/main.rs
- src/tests/e2e/snapshots/zellij__tests__e2e__cases__status_bar_loads_custom_keybindings.snap
- src/tests/fixtures/configs/changed_keys.kdl
- zellij-utils/src/data.rs
- zellij-utils/src/input/mod.rs
- zellij-utils/src/plugin_api/key.rs
Previously, it was not possible to define keybindings with a modifier and a function key. The `Key` enum only supported combinging the Ctrl and Alt modifiers with letters. This is somewhat limiting: I would like to make the Zellij keybindings more "distant" than those used in the programs I use from within Zelilj, so that Zellij does not intefere with those programs. Thus I would like to move some of the keybindings from Ctrl+_character_ to Ctrl+_function key_.
This change adds:
* support for function keys with the Ctrl and Alt modifiers in the `Key` enum,
* support for parsing such keybindings from the configuration file,
* support for such keybindings in the protobuf which communicates the keybindings to plugins, and
* support for these keybindings in the plugin API.
This is tested by …
> Add support for Ctrl and Alt modifiers on function keys in keybindings.

- default-plugins/session-manager/src/main.rs
- default-plugins/session-manager/src/new_session_info.rs
- default-plugins/session-manager/src/ui/components.rs
This fixes three issues with the session manager/welcome screen when starting a new session:
1. The "New session folder:" prompt now always appears in the UI, whether actively selecting a layout or not
2. The session-name is now truncated properly if it's too long to fit on screen
3. Scrolling through the layout list and the layout search results now works as intended
> fix(ui): session manager UI fixes

- zellij-server/src/plugins/mod.rs
- zellij-server/src/plugins/zellij_exports.rs
- zellij-server/src/pty.rs
- zellij-server/src/screen.rs
- zellij-tile/src/shim.rs
- zellij-utils/assets/prost/api.plugin_command.rs
- zellij-utils/src/data.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/plugin_api/plugin_command.proto
- zellij-utils/src/plugin_api/plugin_command.rs
This adds a plugin API that allows plugins to request the serialized layout of the current session. The serialized KDL layout will be returned as a `CustomMessage` API `Event` with the `session_layout` key. If there's an error, a `CustomMessage` API `Event` will be returned with the `session_layout_error` key. Either way, the plugin needs to subscribe to the `CustomMessage` `Event`.
This requires the `ReadApplicationState` permissions.
> feat(plugins): add api to dump the current session layout to a plugin

- zellij-utils/src/input/layout.rs
- zellij-utils/src/input/unit/layout_test.rs
In #2863 and #3157, remote plugins are now designed with their raw URL directly, without the `remote:` prefix but they were still serialized using the `remote:` prefix in session layouts.
As a result, session using remote plugins were not able to restore remote plugins (like `zjstatus`).
This PR just apply the same serialization everywhere to ensure no more `remote:` prefix is used.
> fix(plugins): session layouts are still serialized using the legacy plugin syntax (remote:)

- zellij-server/src/plugins/zellij_exports.rs
- zellij-tile/src/shim.rs
- zellij-utils/assets/prost/api.plugin_command.rs
- zellij-utils/src/data.rs
- zellij-utils/src/plugin_api/plugin_command.proto
- zellij-utils/src/plugin_api/plugin_command.rs
This adds the `close_self` plugin API method that will allow plugins to close the current instance regardless of whether it's focused or not.
> feat(plugins): add api to close current plugin instance

- default-plugins/session-manager/src/new_session_info.rs
- default-plugins/strider/src/file_list_view.rs
Removes some compilation warnings from the built-in plugins
> style(fmt): remove plugin compilation warnings

- zellij-server/src/plugins/zellij_exports.rs
Plugins can often be in a position where they want to start another instance of themselves. While this could previously be done by starting a pipe to the same URL this plugin was launched with (eg. `https://example.com/my-plugin.wasm`), this would force the plugin to know which url it was launched from, whether it was launched through an alias, through a local file or a remote http url.
This PR solves this by allowing plugins to specify a special `zellij:OWN_URL` destination when posting messages to other plugins. When doing so, Zellij will internally replace this destination with the plugin's own URL.
> feat(plugins): allow plugins to specify own_url in pipe destination

- CHANGELOG.md
- zellij-utils/src/cli.rs
- zellij-utils/src/input/actions.rs
which was previously only exposed through keybindings. This is a follow-up to #3047 which likely forgot to add this.
> utils/cli: Add `move-tab` action

- zellij-tile/src/ui_components/nested_list.rs
- zellij-tile/src/ui_components/ribbon.rs
- zellij-tile/src/ui_components/table.rs
- zellij-tile/src/ui_components/text.rs
Add ways to serialize/format ui components instead of only proposing `print` options.
I can remove the first commit if you want, but it did not work on my PC without it:
1. `rust -vV` error when using the "previous" rust toolchain.
2. `protoc` complain that `optional` is an experimental feature of the syntax3.
I also changed the interface to borrow the `Text` elements instead of owning it, so it can be reused.
I had some reflection on the `ribbon`: plugin developers will often want to have multiples of them in a row, so accepting an `into_iter` sounded nicer.
I also wanted to have a possibility to color the full line with the background color, but I’m not sure how to get the bg color from the user’s theme.
Note: I changed the session plugin as needed and others, but I did not `run` …
> Feature/format UI components

- zellij-server/src/tab/layout_applier.rs
- zellij-server/src/tab/swap_layouts.rs
- zellij-utils/src/input/layout.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/pane_size.rs
This fixes two issues:
1. In some cases, Zellij would not properly resurrect a session which had a certain layout (namely one that our constraint system cannot handle due to some ancient bugs I'll address separately)
2. Swap layouts were not picked up in the `NewTab` keybinding - now they are
> fix(layouts): recover from resurrection crash and pick up swap layouts properly

- zellij-utils/src/input/layout.rs
Fixes an edge case where plugins would sometimes switch locations (eg. the filepicker and the status-bar) when starting a session in a specific directory.
> fix(swap-layouts): properly identify plugin aliases with initial cwd

- README.md
This updates the roadmap in the README (the one on the website will be updated with the new release docs next week) and removes the "getting involved" section in favor of the already present link to CONTRIBUTING.md.
> docs(readme): update roadmap and remove extraneous section

- src/commands.rs
- zellij-client/src/cli_client.rs
- zellij-client/src/lib.rs
- zellij-client/src/os_input_output.rs
- zellij-server/src/os_input_output.rs
- zellij-server/src/unit/os_input_output_tests.rs
- zellij-utils/src/cli.rs
This adds the `zellij attach --background <session-name>` command, which allows creating a session in the background through the CLI.
This also (unrelated) makes sure pipes send an empty message to plugins when they end (similar to how pipes work in the shell, so that plugins know when a pipe has ended and can eg. close themselves).
> feat(cli): allow starting a session detached

- zellij-server/src/background_jobs.rs
- zellij-server/src/lib.rs
- zellij-utils/assets/config/default.kdl
- zellij-utils/src/input/options.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__cli_arguments_override_config_options.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__cli_arguments_override_layout_options.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__default_config_with_no_cli_arguments-3.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__default_config_with_no_cli_arguments.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_env_vars_override_config_env_vars.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_keybinds_override_config_keybinds.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_options_override_config_options.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_themes_override_config_themes.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_ui_config_overrides_config_ui_config.snap
This adds the `disable_session_metadata true/false` configuration option to the config file and the CLI, allowing users to disable Zellij's periodic writes of session metadata to the HD (for access by other sessions in eg. the session-manager).
> feat(config): allow disabling writing session metadata to disk

- default-plugins/compact-bar/src/line.rs
This PR updates the compact-bar plugin to make the mode indicator to be always centered.
mode indicator section hard-coded to 8-chars length, on mode names > 6 there's no padding
mode section gets printed as ` <mode-name> `, use a whitespace for padding.
Closes https://github.com/zellij-org/zellij/issues/3248
> fix(compact-bar): properly pad mode indicator

- default-plugins/session-manager/src/resurrectable_sessions.rs
- zellij-server/src/background_jobs.rs
This includes two fixes:
1. We now no longer list sessions that are not resurrectable in plugins as resurrectable (i.e. sessions that do not have a session-layout file saved on disk - namely short lived sessions)
2. Some UI fixes for the resurrectable sessions in the session-manager: namely allowing to delete resurrectable sessions while searching as well as properly updating search results when new session info events arrive
> fix(resurrection): some ui fixes and not listing unresurrectable sessions

- src/commands.rs
- zellij-utils/src/cli.rs
Following https://github.com/zellij-org/zellij/pull/3257 - after some comments from the Discord gang, I changed the name of this flag to make it a little clearer.
> fix(cli): rename `attach --background` to `attach --create-background`

- zellij-utils/src/setup.rs
Fixes an issue where some options specified in `zellij attach --create` weren't being picked up (eg. `zellij attach --create options --default-layout compact`).
> fix(cli): merge attach options

- zellij-client/src/cli_client.rs
Fixes https://github.com/zellij-org/zellij/issues/3269
This was a regression caused by the `pipes` implementation and some refactoring in this area. Namely, only the first action created from a single cli command was used and the rest were ignored. This only affected renaming panes and tabs through the CLI.
> fix(cli): tab and pane name input

- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__open_terminal_floating_plugin_command.snap
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__open_terminal_plugin_command.snap
- zellij-server/src/plugins/zellij_exports.rs
Fixes https://github.com/zellij-org/zellij/issues/3272 and https://github.com/zellij-org/zellij/issues/3267
Previously, this only worked when the shell was configured explicitly through `default_shell` in the config. Now it should work also when it isn't (and thus pick up `$SHELL`).
> fix(plugins): respect default shell when configured in the $SHELL env variable

- zellij-server/src/screen.rs
Fixes https://github.com/zellij-org/zellij/issues/3286
The issue was that this function was using the tab indices rather than their position. This is understandbly confusing - we have no reason to keep track of indices at all, and only do so for legacy reasons.
This fixes this issue - hopefully in the future we'll keep the tab state in a nicer way so as to avoid such mistakes.
> fix(tabs): moving tabs after one was deleted

- zellij-server/src/plugins/mod.rs
- zellij-server/src/pty.rs
- zellij-server/src/route.rs
- zellij-server/src/screen.rs
- zellij-server/src/session_layout_metadata.rs
- zellij-utils/src/cli.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/input/actions.rs
- zellij-utils/src/plugin_api/action.rs
- zellij-utils/src/session_serialization.rs
This adds the `zellij action list-clients` CLI command, which returns a list of the clients connected to the session, as well as their focused pane_id and (when available) the command running inside that pane..
Example output:
```
$ zellij action list-clients
CLIENT_ID ZELLIJ_PANE_ID RUNNING_COMMAND
1         plugin_2       zellij:session-manager
2         terminal_3     vim /tmp/my-file.txt
```
This is intended as a solution to those wanting to implemented integrated navigation with other multiplexers (eg. nvim).
> feat(cli): list clients, their focused pane_id and the running command

- zellij-client/src/input_handler.rs
- zellij-utils/src/input/mod.rs
Made it possible to bind Ctrl+j to a key, this would be very helpful for people using vim keybindings. 
Closes issue #2679 and #2954. 
Should be safe since it doesn't do anything as long as the key is not bound, this is the same behavior as tmux. I manually tested with Ctrl+j both bound and unbound in Kitty, Alacritty, Gnome Terminal and Konsole. 
One remark with this conditional parsing is that the keybindings are not available [here](https://github.com/zellij-org/zellij/blob/158260799b5112e31d86557af8a32b7ab0d77a26/zellij-server/src/tab/mod.rs#L1761C1-L1770C19). As a result, plugins still won't be able to use Ctrl+j, although I don't think that is so big of an issue.
> Fixed keybinding of Control J

- src/commands.rs
- zellij-utils/src/data.rs
- zellij-utils/src/downloader.rs
- zellij-utils/src/input/actions.rs
- zellij-utils/src/input/config.rs
- zellij-utils/src/input/layout.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/plugin_api/event.rs
- zellij-utils/src/setup.rs
This adds the ability to consume layouts with an `http://` or `https://` prefix anywhere we consume layouts.
So for example:
`zellij --layout https://example.com/my-layout.kdl` will start a new session with the fetched layout
`zellij action new-tab --layout https://example.com/my-layout.kdl` will open new tab(s) from the specified layout
This also works for plugins with the existing `switch_session_with_layout` and `new_tabs_with_layout` commands.
> feat(layouts): allow consuming a layout from a url

- zellij-server/src/plugins/wasm_bridge.rs
This fixes an occasional issue with plugins, where batched events (eg. keypresses coming from a single paste command) would arrive in the plugin out of order.
This is fixed here by synchronizing these batches (sending them to the plugin(s) through a single async task rather than one task per event).
This can theoretically be optimized by paralleling the handling on a client level (i.e. that the same event would be sent to all clients in parallel, moving on to the next event once all clients handled it), but I think it's best to only consider this optimization if it becomes an issue (as is it's pretty fast and a rare occurrence).
> fix(plugins): synchronize event batch handling

- zellij-server/src/panes/grid.rs
When Zellij receives the control sequence `\e[1;r` (`DECSTBM` with the parameter string `1;`) from a terminal application, it uses "*the terminal height*" (`self.height`) for the second parameter (which is supposed to be the bottom-line 1-based index of the scrolling region).
https://github.com/zellij-org/zellij/blob/c72f3a712bfa92a4a80b4c1ad1dbe7669892a324/zellij-server/src/panes/grid.rs#L1570
However, the internal index of the bottom line should be "*(the terminal height) - 1*" (`self.height - 1`) because the internal index is 0-based.
- **Steps to reproduce**: See the following reduced case. You can run the command inside Zellij.
```bash
$ printf '\e[1;r'; seq 999; printf '\e[r'
```
- **What I expect**: Suppose the current terminal height is *N*. I expect that the **last** *N*-lines in …
> fix(grid): fix a problem that the default bottom line of the scrolling region (DECSTBM) is placed outside the terminal screen

- zellij-server/src/panes/grid.rs
In the current `main` branch of Zellij, the standard control functions `DL` (`\e[%dM`) and `IL` (`\e[%dL`) are no-op until any other control function directly or indirectly sets the scrolling region.
- **Steps to reproduce**: The following is a reduced case. Please run the command in **a new session** of Zellij [before any other terminal applications send `ED` (`\e[...J`) or `DECSTBM` (`\e[...r`). To make sure, you could use a simple shell such as Bash or Dash].
```bash
$ seq 10; printf '\e[10A\e[10MHello, world!\n'
```
- **What I expect**: The output of the `seq` command should be removed by `\e[10M` (delete 10 lines). Then, `Hello, world!` is printed.
- **What I get in the `main` branch**: Nothing happens with `\e[10M`. The output of the `seq` command remains in the terminal screen, and …
> fix(grid): fix DL/IL being ineffective without scrolling region

- zellij-server/src/screen.rs
Fixes some minor issues where we would issue an extraneous render on CLI client exit that caused some flickering when entering CLI commands at times.
> fix(rendering): do not render if resizing screen to same size

- zellij-server/src/panes/terminal_pane.rs
Fixes an issue caused by https://github.com/zellij-org/zellij/pull/3383 wherein mouse clicks would not be properly translated to programs using the kitty keyboard protocol.
> fix(mouse): mouse click translation to kitty keyboard programs

- CHANGELOG.md
- Cargo.toml
from `Cargo.toml`. This has gone out of sync with the rust version specified in `rust-toolchain.toml` and appears to have little consequence to development, since it defines only the MSRV. We're using `rust-toolchain.toml` to strictly enforce a specific rust version for development, hence we stick with that.
Closes #3476
> cargo: Remove `rust-version` (msrv) field

- CHANGELOG.md
- Cargo.toml
- rust-toolchain.toml
in `Cargo.toml` since it appears that client-side `cargo` will check this field and [error when the users rust toolchain is too old][1]. Add comments in `Cargo.toml` and `rust-toolchain.toml` pointing to each other so the rust versions mentioned in each file are hopefully kept in sync in the future.
Reverts #3480.
[1]: https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field
> cargo: Reintroduce `rust-version` field

- src/commands.rs
- src/sessions.rs
- zellij-server/src/plugins/zellij_exports.rs
- zellij-server/src/tab/unit/tab_integration_tests.rs
- zellij-utils/src/data.rs
- zellij-utils/src/input/layout.rs
- zellij-utils/src/input/unit/layout_test.rs
- zellij-utils/src/kdl/kdl_layout_parser.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/plugin_api/event.rs
When switching sessions through the plugin API, there is now an option to provide a stringified layout rather than one of the builtin ones, from a file or from a URL.
eg.
```rust
switch_session_with_layout(Some("my-cool-session-name"), LayoutInfo::Stringified("
layout {
tab split_direction=\"vertical\" {
pane;
pane;
}
tab {
pane
pane;
pane;
}
}".to_owned()), Some("/tmp".into()));
```
> feat(plugins): add stringified layout to switch_session_with_layout

- zellij-server/src/os_input_output.rs
Update `get_cwd()` to only refresh process specifics for the given PID, matching the `get_cwds()` implementation.
This significantly reduces the latency of opening a new Pane or Tab.
On a 64-core Threadripper system, this reduces the latency of `get_cwd()` from 850ms to 1ms. On an 8-core Ryzen system, the improvement is smaller, but still perceptible.
> fix(terminal): only refresh process specifics for given PID in get_cwd()

- zellij-server/src/plugins/unit/plugin_tests.rs
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__open_command_pane_background_plugin_command.snap
- zellij-server/src/plugins/zellij_exports.rs
- zellij-utils/src/kdl/kdl_layout_parser.rs
This fixes two issues:
1. Background command panes were based on the Zellij cwd rather than the plugin cwd
2. Floating panes defined in layouts did not get the cwd of the tab they were in if it were set
> fix(plugins): various cwd fixes

- default-plugins/fixture-plugin-for-tests/src/main.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/plugins/unit/plugin_tests.rs
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__rerun_command_pane_plugin_command.snap
- zellij-server/src/plugins/zellij_exports.rs
- zellij-server/src/pty.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/layout_applier.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/unit/snapshots/zellij_server__screen__screen_tests__screen_can_break_floating_plugin_pane_to_a_new_tab-2.snap
- zellij-server/src/unit/snapshots/zellij_server__screen__screen_tests__screen_can_break_floating_plugin_pane_to_a_new_tab-3.snap
- zellij-server/src/unit/snapshots/zellij_server__screen__screen_tests__screen_can_break_floating_plugin_pane_to_a_new_tab-4.snap
- zellij-server/src/unit/snapshots/zellij_server__screen__screen_tests__screen_can_break_floating_plugin_pane_to_a_new_tab-6.snap
- zellij-server/src/unit/snapshots/zellij_server__screen__screen_tests__screen_can_break_floating_plugin_pane_to_a_new_tab-7.snap
- zellij-server/src/unit/snapshots/zellij_server__screen__screen_tests__screen_can_break_floating_plugin_pane_to_a_new_tab.snap
- zellij-tile/src/shim.rs
- zellij-utils/assets/prost/api.plugin_command.rs
- zellij-utils/src/data.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/plugin_api/plugin_command.proto
- zellij-utils/src/plugin_api/plugin_command.rs
This allows plugins to rerun a command pane that has exited (similar to what would happen if a user focused on the pane and pressed `<ENTER>`, only to any such pane without changing user focus).
> feat(plugins): rerun_command_pane API

- zellij-client/src/lib.rs
- zellij-server/src/lib.rs
- zellij-utils/src/input/config.rs
This is the beginning of a series of changes that will allow fully reloading and reapplying the Zellij configuration file (by default `~/.config/zellij/config.kdl`) at runtime.
This PR adds a filesystem watcher to the config file on `zellij-client`. When the file is created or modified, we reload its contents and send them to `zellij-server` who reapplies them to the current session if they changed.
In this PR, aside from this infrastructure, we add support for reapplying the `keybinds` block and the `default_mode` option setting from the configuration file. Nothing else works yet!
Adding support for all the rest of the config file (themes, configuration options, plugin aliases, etc.) - upcoming in next PRs!
> feat(ux): reload config at runtime

- zellij-server/src/plugins/mod.rs
- zellij-server/src/route.rs
- zellij-utils/src/input/actions.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/plugin_api/action.rs
This adds the `MessagePluginId` bindable keybind action. Similar to `MessagePlugin`, this will create a pipe that will send a message to a specific plugin - only here it will be done by this plugin's runtime ID.
The purpose is to use this with the `reconfigure` plugin API to essentially allow plugins to temporarily bind global keys in the session to send messages to themselves.
Example:
```rust
let own_plugin_id = Some(get_plugin_ids().plugin_id);
let save_configuration_to_file = false;
reconfigure(format!(r#"
keybinds {{
shared {{
bind "F1" {{
MessagePluginId {own_plugin_id}  {{
name "F1"
}}
}}
bind "F2" {{
MessagePluginId {own_plugin_id} {{
name "F2"
}}
}}
bind "F3" {{
MessagePluginId {own_plugin_id} {{
name "F3"
}}
}}
}}
}}
"#), save_configuration_to_file);
// ...
impl State {
fn …
```
> feat(plugins): API to temporarily bind keys to send a message to a specific plugin id

- zellij-server/src/lib.rs
- zellij-server/src/panes/floating_panes/mod.rs
- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/plugin_pane.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/panes/tiled_panes/mod.rs
- zellij-server/src/plugins/mod.rs
- zellij-server/src/plugins/plugin_map.rs
- zellij-server/src/plugins/wasm_bridge.rs
- zellij-server/src/pty.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-utils/assets/config/default.kdl
- zellij-utils/src/data.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/kdl/snapshots/zellij_utils__kdl__bare_config_from_default_assets_to_string_with_comments.snap
- zellij-utils/src/kdl/snapshots/zellij_utils__kdl__config_options_to_string_with_comments.snap
- zellij-utils/src/kdl/snapshots/zellij_utils__kdl__plugins_to_string.snap
- zellij-utils/src/kdl/snapshots/zellij_utils__kdl__plugins_to_string_with_file_and_web.snap
This concludes the work began in https://github.com/zellij-org/zellij/pull/3558 and continued in https://github.com/zellij-org/zellij/pull/3559, to now allow reloading everything defined in the config at runtime with a few notable exceptions (see below).
* Reloading `simplified_ui` (i.e. changing arrow font support)
* Reloading `default_shell`
* Reloading `pane_frames`
* Reloading `copy_command` (i.e. clipboard replacement for terminals not supporting OSC52)
* Reloading `copy_to_clipboard` (i.e. the clipboard destination)
* Reloading `copy_on_select`
* Reloading `auto_layout`
* Reloading `rounded_corners`
* Reloading `hide_session_name`
* Reloading `scrollback_editor`
Most of these were not worked on due to some internal limitations that would have required considerable development to get …
> feat(ux): reload config options at runtime

- zellij-utils/src/session_serialization.rs
- zellij-utils/src/snapshots/zellij_utils__session_serialization__tests__can_serialize_multiple_tabs.snap
- zellij-utils/src/snapshots/zellij_utils__session_serialization__tests__can_serialize_new_tab_template.snap
- zellij-utils/src/snapshots/zellij_utils__session_serialization__tests__can_serialize_swap_floating_panes.snap
- zellij-utils/src/snapshots/zellij_utils__session_serialization__tests__can_serialize_swap_tiled_panes.snap
- zellij-utils/src/snapshots/zellij_utils__session_serialization__tests__can_serialize_tab_focus.snap
- zellij-utils/src/snapshots/zellij_utils__session_serialization__tests__can_serialize_tab_hide_floating_panes.snap
- zellij-utils/src/snapshots/zellij_utils__session_serialization__tests__can_serialize_tab_name.snap
- zellij-utils/src/snapshots/zellij_utils__session_serialization__tests__can_serialize_tab_with_floating_panes.snap
- zellij-utils/src/snapshots/zellij_utils__session_serialization__tests__can_serialize_tab_with_stacked_panes.snap
- zellij-utils/src/snapshots/zellij_utils__session_serialization__tests__can_serialize_tab_with_tiled_panes.snap
- zellij-utils/src/snapshots/zellij_utils__session_serialization__tests__global_cwd.snap
This fixes various serialization issues in regards to the session resurrection feature. Previously, we relied on our hand-rolled serialization of the session layout and metadata to disk. Now we use `kdl-rs` to do the serialization part after we've done the encoding.
This addresses lots of issues where sessions would not be resurrected properly.
> fix(resurrection): various serialization issues

- Cargo.lock
- zellij-server/src/background_jobs.rs
- zellij-utils/Cargo.toml
- zellij-utils/src/downloader.rs
- zellij-utils/src/lib.rs
Web requests now work consistently both for fetching and loading plugins, layouts and for plugins initiating http requests themselves.
There were some issues with `surf`, namely that (for reasons admittedly unknown to me) we had to explicitly include a newer version of `isahc` in our `Cargo.toml` in order for it to work. Seeing that surf is currently [unmaintained](https://github.com/http-rs/surf/issues/352#issuecomment-1709404352), I opted to move us to using `isahc` directly. This should have no changes for us - we were using it anyway, just now we will do so without the surf wrapper.
> fix(http): web requests

- zellij-server/src/screen.rs
This fixes a race (likely introduced as a result of https://github.com/zellij-org/zellij/pull/3349) that would cause UI plugins (eg. the tab-bar) to sometimes become selectable even though they set themselves to non-selectable. This happened because the event would get to the screen thread before the layout was applied, and thus it did not recognize the plugin id.
Now, if case this happens, the screen caches the event and attempts to reapply it when the layout is applied.
> fix(plugins): handle race when setting plugin selectable

- zellij-utils/src/setup.rs
This adds the cache folder to the output of `zellij setup --check`.
> feat(cli): show CACHE_DIR in `zellij setup --check`

- default-plugins/configuration/src/main.rs
- default-plugins/plugin-manager/src/main.rs
- zellij-server/src/tab/mod.rs
This fixes:
1. An issue that prevented plugin panes from being renamed
2. The plugin manager now properly sets its title
3. The Configuration now properly sets its title
> fix(ui): various pane name fixes

- zellij-server/src/tab/mod.rs
This fixes an issue where when resizing panes we would set both the tiled and swap layout to "damaged", whereas we should only set the relevant layer (tiled for resizing tiled panes, floating for resizing floating panes).
The user-facing effect of this was that (for example) after resizing a floating pane, when opening new tiled panes they would be added in a "best effort" way rather than following the swap layouts and arranging themselves "nicely" on screen.
> fix(ux): only damage the relevant swap layout layer when resizing panes

- zellij-server/src/ui/components/nested_list.rs
- zellij-server/src/ui/components/table.rs
- zellij-server/src/ui/components/text.rs
- zellij-utils/assets/themes/catppuccin.kdl
This fixes a minor issue in the UI components where `Text` and its various consumers would not set the theme background as their background - causing the UI to look a bit disjointed at times.
> fix(ui): set background color for UI components according to theme

- default-plugins/configuration/src/main.rs
Make sure `ESC` always drops us back to our base more (was the case in all keybinding presets except the new unlock-first one).
> fix(ux): make sure esc works as expected in unlock-first

- zellij-server/src/plugins/wasm_bridge.rs
- zellij-utils/src/downloader.rs
This should hopefully fix https://github.com/zellij-org/zellij/issues/3479
Previously, if loading the same plugin multiple times from a remote URL - the downloads would each cache to the same file on the HD and corrupt each other.
This solves the problem by creating a concurrent locking mechanism, making sure there's only one download of the same URL happening at the same time.
> fix(plugins): handle concurrent http downloads

- src/main.rs
- zellij-server/src/panes/floating_panes/mod.rs
- zellij-server/src/panes/tiled_panes/mod.rs
- zellij-server/src/tab/mod.rs
- zellij-utils/src/consts.rs
- zellij-utils/src/input/actions.rs
This fixes:
1. Plugins can now no-longer make unselectable panes selectable
2. We now make sure the cache/config folders are created on app start (this prevents some races with the http downloading client).
> fix(plugins): various plugin api and other fixes

- Cargo.lock
- zellij-utils/Cargo.toml
There were in the past some problems with downloading plugins via HTTPS on macOS (https://github.com/zellij-org/zellij/issues/3036#issuecomment-2024214955, https://github.com/zellij-org/zellij/issues/3479#issuecomment-2407490553).
The cause is, that curl is not properly recognised when building zellij, especially after the latest changes to the isahc crate in favour of surf. This results in zellij not being linked to `libcurl`, which utilises some other dependencies in the background to implement the functionality, that results in crashes for certain scenarios. 
This pull request fixes the issue, as it forces `curl-sys` to use system libs of macOS instead of choosing it on its own. On my macOS with nix as build environment and in a VM with curl installed via brew, the issue is fixed and …
> fix(plugins): force use curl system lib on macOS

- zellij-server/src/lib.rs
This prevents a hard-crash when plugins attempt to attach to the same session (which is not allowed). Instead, we log an error in the Zellij logs.
> fix(plugins): do not allow attaching to the same session

- src/commands.rs
- zellij-server/src/plugins/mod.rs
- zellij-tile/src/shim.rs
- zellij-utils/src/data.rs
This adds a new plugin API `switch_session_with_cwd` that allows switching to a new session with the default layout and specifying a cwd (eg. `/tmp`).
This also includes some fixes that get `default_cwd` to work once more when specified as a CLI option.
> fix(plugins): allow switching to a new session with cwd without specifying a layout

- default-plugins/fixture-plugin-for-tests/src/main.rs
- zellij-server/src/lib.rs
- zellij-server/src/plugins/unit/plugin_tests.rs
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__rebind_keys_plugin_command.snap
- zellij-server/src/plugins/zellij_exports.rs
- zellij-tile/src/shim.rs
- zellij-utils/assets/prost/api.plugin_command.rs
- zellij-utils/src/data.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/plugin_api/plugin_command.proto
- zellij-utils/src/plugin_api/plugin_command.rs
This adds a plugin API that allows plugins to explicitly unbind/rebind certain keys in certain modes, rather than change the entire runtime configuration in order to rebind one or two keys.
This API also uses the internal `KeyWithModifier`, `InputMode` and `Action` entities rather than making plugins send a stringified KDL config.
Context: I plan on using this in the upcoming "rebind primary/secondary/superkey" PR that will add a UI to the configuration allowing users to change these modifiers without changing their entire config at runtime like is possible now through the setup wizard/configuration.
> feat(plugins): rebind keys api

- zellij-server/src/route.rs
We come from #3506 
The sleeping time has been set to 5ms, as suggested. As noted in https://github.com/zellij-org/zellij/pull/3506#issuecomment-2299829281, entering the while loop does not significantly impact performance.
> fix(terminal): repeat retry screen instruction sending during stdin cache replay (cont)

- Cargo.lock
- zellij-server/Cargo.toml
This fixes a race condition which causes occasional crashes and may enable a sandbox escape:
<https://github.com/bytecodealliance/wasmtime/security/advisories/GHSA-7qmx-3fpx-r45m>
> Update to Wasmtime 21.0.2

- default-plugins/fixture-plugin-for-tests/src/main.rs
- zellij-server/src/plugins/mod.rs
- zellij-server/src/plugins/unit/plugin_tests.rs
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__list_clients_plugin_command.snap
- zellij-server/src/plugins/zellij_exports.rs
- zellij-server/src/pty.rs
- zellij-server/src/screen.rs
- zellij-server/src/session_layout_metadata.rs
- zellij-tile/src/shim.rs
- zellij-utils/assets/prost/api.event.rs
- zellij-utils/assets/prost/api.plugin_command.rs
- zellij-utils/src/data.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/plugin_api/event.proto
- zellij-utils/src/plugin_api/event.rs
- zellij-utils/src/plugin_api/plugin_command.proto
- zellij-utils/src/plugin_api/plugin_command.rs
This adds a plugin API that returns an `Event::ListClients` with info about the running clients, their focused pane and the running command inside this pane (or the plugin url).
This is an API version of `zellij action list-clients` so that plugins don't have to rely on the command line to get this info.
> feat(plugins): add API to list clients, their focused panes and running commands/plugins

- default-plugins/compact-bar/src/tab.rs
- default-plugins/tab-bar/src/tab.rs
- src/tests/e2e/snapshots/zellij__tests__e2e__cases__toggle_pane_fullscreen.snap
This brings back the full indication that has been removed when the UI was changed recently. Here, instead of having it on the extra status-bar line (which now does not exist) we add it to the tab name. The upshot of which is that we can see if a tab is in full-screen even if we're not focused on it.
> feat(ui): bring back fullscreen indication

- default-plugins/configuration/src/presets.rs
- default-plugins/status-bar/src/main.rs
- default-plugins/status-bar/src/one_line_ui.rs
This includes two fixes:
1. Bring back the "copied to clipboard" indication to the new UI
2. Make is possible to scroll out of a scrolled pane without resetting the scroll (previously only possible with the mouse, now also with `Alt+<arrows>` or `Alt+<hjkl>`.
> fix(ux): new interface/configuration touch-ups

- default-plugins/configuration/src/presets_screen.rs
- default-plugins/configuration/src/rebind_leaders_screen.rs
- default-plugins/plugin-manager/src/main.rs
- zellij-server/src/panes/active_panes.rs
- zellij-server/src/panes/tiled_panes/mod.rs
Rebind insert key in the plugin manager and configuration, since it doesn't exist on macOS (thanks @dj95 !)
This also fixes an issue where if the tab-bar or status-bar were closed through the plugin manager, the UI would get stuck. Right now, due to the built-in swap layouts, another pane fills their place - but this will be fixed at another time. Right now I preferred to leave this option open in order to empower users to make this decision on their own.
> fix(plugins): rebind insert

- zellij-server/src/panes/grid.rs
This is a fix for https://github.com/zellij-org/zellij/issues/3525
The issue that was happening here is that a canonical line exceeded the scrollback size and was only partially dropped. Then when scrolling back down we were trying to connect its non-canonical edge to it. This should not have happened, but my guess is that due to some recent algorithm changes in this area this situation became possible.
For this reason we now recover from this situation by making the partial line canonical (which is probably nicer anyway).
> fix(terminal): recover from partial line drop

- default-plugins/configuration/src/main.rs
- default-plugins/configuration/src/presets_screen.rs
- default-plugins/configuration/src/rebind_leaders_screen.rs
This is a minor fix for the new configuration plugin that prevents the "configuration applies to current session" notification from disappearing when the base input mode changes (eg. from `normal` to `locked`).
> fix(configuration): leave notification up when base mode changes

- default-plugins/configuration/src/rebind_leaders_screen.rs
- zellij-server/src/lib.rs
- zellij-server/src/plugins/mod.rs
- zellij-server/src/plugins/plugin_loader.rs
- zellij-server/src/plugins/wasm_bridge.rs
- zellij-server/src/pty.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/layout_applier.rs
- zellij-server/src/tab/mod.rs
- zellij-utils/src/input/config.rs
- zellij-utils/src/ipc.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/session_serialization.rs
This addresses the cargo warnings as well as fixes a minor rounding error in the configuration UI
> style(fmt): various cleanups

- zellij-utils/assets/themes/ayu.kdl
Based on the AYU theme colors from https://github.com/dempfi/ayu.
> Added ayu mirage, light, and dark themes

- zellij-utils/assets/themes/vesper.kdl
Add Vesper theme, based on https://github.com/raunofreiberg/vesper.
> feat(themes): add Vesper theme

- zellij-utils/assets/themes/iceberg.kdl
Add light and dark themes based off the iceberg theme https://github.com/cocopon/iceberg.vim. The attached examples also set the relevant terminal colorscheme as well.
> feat: add iceberg dark/light themes

- zellij-utils/assets/themes/onedark.kdl
Onedark is a popular theme from Atom text editor. 
I've used these sources as the reference for implementing the theme in zellij. https://github.com/joshdick/onedark.vim
https://www.figma.com/community/file/1137445418485757476/atom-one-dark-color-palette
> theme: add onedark theme to the available themes

- zellij-utils/assets/themes/ansi.kdl
This adds a simple theme using only the base 16 ANSI colors.
Some terminal emulators (like the macOS Terminal.app) do not support truecolor, and one can get around this by applying custom values to the 16 ANSI colors through the terminal's "theme". This theme utilizes only those colors so that one's applied terminal theme will carry through to zellij.
> Add basic ANSI theme

- zellij-utils/assets/themes/gruvbox.kdl
the previous themes do not have the correct colors and aren't great for the eyes. when selecting e.g. to copy text, it uses red for light theme and the same bg for dark theme for highlighting text.
the previous light theme is not even a light theme so I also fixed that as well.
> fix(theme): this was a fast fix for gruvbox light and dark

- default-plugins/fixture-plugin-for-tests/src/main.rs
- default-plugins/session-manager/src/ui/components.rs
- default-plugins/tab-bar/src/line.rs
- zellij-utils/src/input/layout.rs
Remove compilation cargo warnings from plugins
> style(fmt): remove warnings

- zellij-server/src/panes/tiled_panes/mod.rs
- zellij-server/src/tab/mod.rs
> fix: (tabs) move to next tab if moving to next pane from fullscreen pane

- default-plugins/configuration/src/presets_screen.rs
- default-plugins/configuration/src/rebind_leaders_screen.rs
- default-plugins/configuration/src/ui_components.rs
- zellij-utils/src/home.rs
- zellij-utils/src/input/config.rs
This includes a few fixes for the `configuration` screen:
1. The `<TAB>` indicator was partially cut off, not is isn't
2. `Ctrl s` was rebound to `Ctrl a` (because it's already bound in the `Default` preset)
3. The `RebindingLeaders` screen was removed from the `PresetsScreen` because it was deemed too confusing for users. The same functionality can be achieved by choosing a preset and then rebinding the leaders if desired.
> fix(ux): configuration fixes

- zellij-server/src/lib.rs
- zellij-server/src/route.rs
- zellij-utils/src/input/keybinds.rs
This fixes an issue where keys would be forwarded to panes only in locked mode and hard-coded normal mode. Which is alright for the default preset, but not so much for unlocked-first (because then they would also be forwarded when the interface is unlocked and one must press single-letter aliases to enter the different modes).
This fixes it by forwarding the keys in locked mode always and also in the base mode (in unlocked-first the base mode is locked mode, so this works fine).
> fix(ux): forward keys to pane in locked mode and base mode rather than hard-coded normal mode

- zellij-utils/src/data.rs
Implementation of the Kitty Keyboard protocol, especially in regards to the more unusual modifiers such as `NumLock`, `Capslock` etc. varies wildly between terminal emulators. This causes some odd bugs such as keybindings not being recognized when `NumLock` is pressed - but only in some terminals!
To remove the confusion, I removed these keys from Zellij's internal representation. We will still forward them to terminal panes that request them (since we forward the STDIN buffer verbatim) but will not interpret them or send them to plugins.
> fix(input): remove support for extra modifiers

- src/tests/e2e/cases.rs
- zellij-utils/src/input/keybinds.rs
The previous fix for differentiating `Ctrl j` from `Enter` happened before the re-architecture involved in reloading the configuration at runtime - so it no longer works for anything but the default config (which is now not a thing in itself since we make sure the config is written on first run).
This fixes it by moving the differentiation to the server side.
> fix(input): refix ctrl-j

- default-plugins/plugin-manager/src/main.rs
- zellij-server/src/plugins/plugin_loader.rs
- zellij-server/src/plugins/wasm_bridge.rs
This includes a few fixes:
1. Maintain plugin cwd when reloading it (eg. through the plugin manager)
2. Default to loading plugins in the foreground through the plugin manager
3. Allow sending space in configuration parameters when starting plugins through the plugin manager
> fix(plugins): cwd and usability fixes

- zellij-server/src/output/mod.rs
This fixes a rendering issue where sometimes when terminals would render themselves multiple times while being resized, their output would "spill" onto other panes. This is now fixed by always truncating the rendered buffer to the grid sized, even when it's cached and only partially rendered.
> fix(output-buffer): truncate grid height when not rendering it fully

- zellij-utils/src/input/layout.rs
This is a fix for `LaunchOrFocusPlugin` (which is used in the default configuration to launch the session-manager, plugin manager and configuration screen) which would previously not work well with plugin aliases (which all the aforementioned use).
This fix makes it so that when launching the session-manager, it will always be the same session-manager.
> fix(plugins): do not open extra instances of aliases

- zellij-server/src/panes/grid.rs
Minor fix to make sure the kitty keyboard support is reset when resetting the terminal state (eg. using the `reset` command).
> fix(terminal): reset kitty keyboard support when resetting terminal state

- zellij-client/src/lib.rs
This fixes a crash that happened on startup when Zellij did not have read permissions to the config parent folder - ouch!
> fix(config): crash if unable to watch config folder

- zellij-server/src/lib.rs
- zellij-server/src/route.rs
This fixes an issue where on some occasions the Zellij startup would be delayed by a few seconds until the terminal colors were queried.
This was happening because due to recent changes in the sending retry mechanism, the retry-queue was holding the lock on the session metadata for all messages.
This was fixed by only acquiring the lock when trying to send a message to the server, releasing it before placing it in the retry-loop.
> fix(statup): slow startup on some occasions

- Cargo.toml
- zellij-utils/Cargo.toml
Closes #3720
Supersedes #3745
The additive and by-default nature of the `vendored-curl` feature is the cleanest way I could come up with to retain the old vendored behavior and also achieve the "off switch" that I talk about in the issue above.
> chore: add vendored_curl feature

- default-plugins/plugin-manager/src/main.rs
This changes `Ctrl d` to `Ctrl f` in the plugin manager for loading a new plugin from disk. This is so that there will be consistency with other built-in plugins (eg. the session-manager) for opening the filepicker.
> fix(ux): change plugin manager shortcut

- zellij-server/src/screen.rs
The `PaneClosed` event was not being sent to plugins when the pane was closed as a result of closing an entire tab. This fixes it.
> fix(screen): send PaneClosed event to plugins also when closing the whole tab

- zellij-server/src/plugins/plugin_loader.rs
- zellij-server/src/plugins/plugin_map.rs
This adds a `/cache` folder accessible to plugins. This folder is similar to the `/data` folder, except Zellij will not delete it when the plugin is unloaded.
Another difference to the `/data` folder is that this folder is shared between all instances of the plugin loaded with the same URL (either remote or local).
This folder is also particular to the current version of Zellij - meaning that the same plugin loaded in a newer version will have a clean `/cache` folder.
Like all of the Zellij cache, this folder can be explicitly deleted by users (eg. to save disk space). It's located inside the Zellij cache folder (whose path can be seen in `zellij setup --check`).
> feat(plugins): add /cache folder

- Cargo.lock
- zellij-utils/Cargo.toml
- zellij-utils/src/common_path.rs
- zellij-utils/src/lib.rs
As mentioned in #3702, this PR should help packaging zellij by avoiding dependency on `common-path`, whose repository is not available anymore.
One thing I haven't done is mentioning the original author. What's the best way to mention them in the source code? Should I just mention it through a comment or should I add it to rustdoc?
> Vendoring common_path

- zellij-utils/src/data.rs
This is a minor fix to the plugin API - namely adding the `Hash` and `Ord` derives for the exported `PaneId` type to make it easier to use this type as a key in a `HashMap` and `BTreeMap` in plugins.
> fix(plugins): derive hash and ord for PaneId

- zellij-server/src/screen.rs
This fixes a minor issue where the `focus_pane_with_id` and `suppress_pane` plugin API commands would not work properly if a tab was closed.
The issue was that the tab was being focused by its index and not by its position.
> fix(plugins): properly focus pane after tab was closed

- default-plugins/configuration/src/presets_screen.rs
- default-plugins/configuration/src/rebind_leaders_screen.rs
- zellij-server/src/ui/components/text.rs
This fixes UI elements to always color text background until the element width if the there is a width and the element has a background.
For example, when doing `print_text_with_coordinates(text_element.selected(), 0, 0, Some(10), None)`, the selection would be colored until the width of 10 characters even if `text_element` is only 8 characters long.
> fix(plugins): properly pad UI elements when they have a background

- zellij-server/src/plugins/mod.rs
- zellij-server/src/plugins/plugin_loader.rs
- zellij-server/src/plugins/wasm_bridge.rs
- zellij-server/src/plugins/zellij_exports.rs
- zellij-tile/src/shim.rs
- zellij-utils/assets/prost/api.event.rs
- zellij-utils/assets/prost/api.plugin_command.rs
- zellij-utils/assets/prost/api.plugin_permission.rs
- zellij-utils/src/data.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/plugin_api/event.proto
- zellij-utils/src/plugin_api/event.rs
- zellij-utils/src/plugin_api/plugin_command.proto
- zellij-utils/src/plugin_api/plugin_command.rs
- zellij-utils/src/plugin_api/plugin_permission.proto
- zellij-utils/src/plugin_api/plugin_permission.rs
This adds the ability to change a plugin's `/host` folder at runtime through a new `change_host_folder` plugin command.
This command has been gated behind the new `FullHdAccess` permission, since this means that a plugin will be able to access any part of the HD that the Zellij process itself has access to (which in turn depends on which user runs it), instead of just to the working directory in which the plugin was run.
> feat(plugins): allow changing the plugin's `/host` folder (under a new permission)

- default-plugins/session-manager/src/main.rs
- default-plugins/session-manager/src/ui/components.rs
- zellij-server/src/plugins/zellij_exports.rs
Session names cannot contain slashes. Previously, if trying to rename the session or start a new session with a slash in it - Zellij would detach (the check was only made on the client-side *after* detaching from the current session - yikes!)
This fixes the issue by verifying there's no slash in the session name both in the plugin API and in the session-manager plugin (so that it can show an informative error message).
> fix(plugins): do not detach if using a slash in a session name

- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
This is a fix for https://github.com/zellij-org/zellij/issues/3834 (among other issues).
What was happening here is that `LaunchOrFocusPlugin` was unintentionally going through the logic for switching back to a normal pane after having edited its scrollback with the scrollback editor. The relevant parameter in the function had an outdated name (my bad!) which caused this confusion when implementing this feature in the first place.
Now opening the session-manager properly brings it to the focused tab.
> fix(plugins): properly focus plugin after it was hidden

- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/ui/pane_contents_and_ui.rs
This fixes an old bug where the fake cursors rendered for other players in multiplayer sessions would sometimes not be properly cleared when their line was not updated (this sometimes happened in older shells like bash or sh).
> fix(multiuser): properly clear fake cursors

- zellij-server/src/panes/grid.rs
Hi, thank you for Zellij!
I help maintain [Textual](https://github.com/textualize/textual/) and some dependent TUI apps like [Posting](https://github.com/darrenburns/posting) which make use of mode 2026.
I started using Zellij yesterday (loving it!) and noticed that the mode 2026 query response was not being parsed as expected and so the output could not be synchronized.
Looking into the code of Zellij, I think the response is missing a `?` character. If I'm understanding correctly, response should be of the format `CSI ? 2026 ; N $ y` where N can be any value in the range 0-4 (inclusive).
References:
- https://gist.github.com/christianparpart/d8a62cc1ab659194337d73e399004036
- https://vt100.net/docs/vt510-rm/DECRPM.html
Notice the tearing effect as the cursor moves through the list. It's …
> Fix Synchronized Output (mode 2026) reporting

- zellij-server/src/panes/grid.rs
- zellij-utils/assets/layouts/default.swap.kdl
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__default_config_with_no_cli_arguments-2.snap
This fixes a small issue where in some cases where the application running inside a terminal pane would report an out-of-bounds cursor position, we would render the cursor on the pane border. This was likely introduced during some changes in the past months.
This fixes it as well as one minor issue introduced in a recent PR regarding swap layout placement.
> fix(terminal): cursor overflow

- zellij-server/src/panes/grid.rs
From
https://sw.kovidgoyal.net/kitty/keyboard-protocol/#progressive-enhancement:
> The escape code for requesting enhancements is:
> CSI = flags ; mode u
That means it can be *set* with CSI =, not just pushed/popped onto the stack with CSI < and CSI >.
This is important because otherwise zellij would interpret this as restore_cursor_position, which would move the cursor.
This would be hit by the next fish-shell release, which sends CSI = 5 u and CSI = 0 u to enable/disable the kitty keyboard enhancements unconditionally,
so if you used any program that saved the cursor position it would constantly move your cursor back on every prompt.
Fixes #3852
> fix(terminal): Support kitty keyboard protocol setting with "="

- zellij-server/src/panes/tiled_panes/mod.rs
This fixes an issue in main introduced by the recent stacked-resize feature where tiled panes would not be opened from the CLI. Thanks @dj95 for the find!
> fix(tiled-panes): opening panes from the cli

- zellij-server/src/panes/plugin_pane.rs
- zellij-server/src/panes/terminal_pane.rs
- zellij-server/src/tab/mod.rs
- zellij-utils/assets/prost/api.event.rs
- zellij-utils/src/data.rs
- zellij-utils/src/plugin_api/event.proto
- zellij-utils/src/plugin_api/event.rs
This makes it so that if a user pastes text while focused on a plugin, the text will arrive in one go with the new `PastedText` event rather than character by character as before.
This should make it much easier to invite users to paste text into plugins and handle it as a whole rather than rendering on each keystroke and trying to figure out when the paste ended with debounces and other methods.
> feat(plugins): add `PastedText` Event

- zellij-server/src/panes/floating_panes/mod.rs
- zellij-server/src/plugins/zellij_exports.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-tile/src/shim.rs
- zellij-utils/assets/prost/api.plugin_command.rs
- zellij-utils/src/data.rs
- zellij-utils/src/plugin_api/plugin_command.proto
- zellij-utils/src/plugin_api/plugin_command.rs
Currently, plugins are only able to open new panes from the perspective of the user. For example, if a user is focused in a different tab than the plugin, the plugin could only open panes in that tab.
This adds new plugin API methods that allow a plugin to open new panes "near" it. So for example, if a plugin would use the new `open_terminal_near_plugin` command, the terminal will be opened near in its own tab regardless of whether the user is focused on it or not (and it will also not change the user focus).
The APIs that were added:
`open_terminal_near_plugin`
`open_terminal_floating_near_plugin`
`open_terminal_in_place_of_plugin` (will override the plugin pane with the terminal until the terminal is closed, at which point the plugin will reappear)
`open_command_pane_near_plugin` …
> feat(plugins): Allow opening panes near plugin

- zellij-server/src/lib.rs
- zellij-server/src/plugins/unit/snapshots/zellij_server__plugins__plugin_tests__switch_to_mode_plugin_command.snap
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/tab/unit/tab_integration_tests.rs
- zellij-server/src/tab/unit/tab_tests.rs
- zellij-server/src/unit/screen_tests.rs
- zellij-utils/assets/prost/api.event.rs
- zellij-utils/src/data.rs
- zellij-utils/src/input/mod.rs
- zellij-utils/src/plugin_api/event.proto
- zellij-utils/src/plugin_api/event.rs
This adds an `editor` and `shell` optional fields to the `ModeInfo` sent on `ModeUpdate` to plugins.
Meaning plugins would be able to (for example) use the user's default shell to launch commands and shell aliases (if they have permission). Also to display helpful information to the user about which program would be used to edit files in the built-in editor.
> feat(plugins): send info about $EDITOR and $SHELL

- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
This is a small fix to the recent change-floating-panes plugin API, to make it so that if a pane is tiled or suppressed - changing its floating coordinates would make it floating.
> fix(floating-panes): when changing coordinates, if a pane is not floating - make it floating

- zellij-server/src/panes/tiled_panes/mod.rs
This fixes an issue with the yet-to-be-released logical position refactor where panes broken into a new tab under certain conditions would crash or disappear.
The issue was that the logical position from the previous tab was kept and cause chaos. This fixes it by stripping it before adding the pane to the new tab.
> fix(break-pane): strip logical position when inserting pane to new tab

- default-plugins/strider/src/file_list_view.rs
- default-plugins/strider/src/main.rs
- default-plugins/strider/src/state.rs
- zellij-server/src/plugins/zellij_exports.rs
- zellij-server/src/pty.rs
- zellij-server/src/route.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-server/src/ui/components/text.rs
- zellij-tile/src/shim.rs
- zellij-utils/assets/prost/api.plugin_command.rs
- zellij-utils/src/data.rs
- zellij-utils/src/plugin_api/plugin_command.proto
- zellij-utils/src/plugin_api/plugin_command.rs
This improves the filepicker (strider) UI somewhat, and also adds the ability to close a plugin once it has replaced itself with another pane.
In Strider this is used when opening a file in place of strider, or when using the "open terminal here" functionality.
> fix(ux): some filepicker improvements

- default-plugins/compact-bar/src/main.rs
- default-plugins/status-bar/src/main.rs
- default-plugins/status-bar/src/one_line_ui.rs
- default-plugins/status-bar/src/second_line.rs
- zellij-server/src/route.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-utils/src/input/actions.rs
This fixes some issues with the "Text copied to clipboard" message:
1. The message now properly appears with an opaque background
2. The message now also appears in the compact layout
3. The message does not jitter when double-clicking a word to copy it
> fix(clipboard): clipboard message

- Cargo.lock
This fixes an occasional segfault that happened in the `chrono` crate (used for our logger) when logging from an async task (eg. when loading plugins).
> fix(logging): segfault in chrono crate

- zellij-server/src/tab/mod.rs
- zellij-server/src/tab/swap_layouts.rs
This fixes an issue where the swap layouts would remain "damaged" after closing the last floating pane (if they were damaged beforehand).
> fix(floating-panes): reset swap floating layouts when closing last floating pane

- zellij-server/src/panes/plugin_pane.rs
Fixes an issue with the recently added "pinned panes" feature where one would not be able to pin floating plugin panes with the mouse.
> fix(pinned-panes): allow pinning floating plugin panes with the mouse

- CHANGELOG.md
- zellij-server/src/screen.rs
- zellij-utils/assets/prost/api.event.rs
- zellij-utils/src/data.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/kdl/snapshots/zellij_utils__kdl__serialize_and_deserialize_session_info.snap
- zellij-utils/src/kdl/snapshots/zellij_utils__kdl__serialize_and_deserialize_session_info_with_data.snap
- zellij-utils/src/plugin_api/event.proto
- zellij-utils/src/plugin_api/event.rs
This gives plugins access to the tab history of each connected client through the `SessionUpdate` Event (meaning they will also be available for other sessions).
The tab history is an ascending zero-indexed vector of the previously visited tabs of each client. So for example `0 1 3` means that the user's last visited tab index is `3`, before that `1` and before that `0`. The current tab never appears in the list, so it might not be linear.
> feat(plugins): add tab history to the `SessionUpdate` Event

- Cargo.lock
- zellij-server/src/os_input_output.rs
- zellij-utils/src/ipc.rs
This updates `rmp-serde` and `rustix` to avoid some potential crashes.
> chore(deps): update some dependencies

- zellij-server/src/panes/grid.rs
No code paths existed to clear sixel images when handling csi dispatch for clear.
Fixes #3173
> fix(grid): Clear sixels when clearing terminal

- default-plugins/about/src/main.rs
This adds a more verbose error to the startup tips when unable to permanently dismiss them due to the config being read only (or some other error).
This now shows a more verbose error inviting the user to manually add the specific line to their config file.
> fix(about): more verbose config readonly error

- CHANGELOG.md
- zellij-server/src/panes/tiled_panes/tiled_pane_grid.rs
This fixes an annoying UX issue where when focusing panes off the screen edge using `Alt <arrows>`, the selectable pane with the lowest x would be focused on the relevant edge regardless of which one was previously active. Now these ties will be broken with `active_at` instead of the opposite direction, which is a much better user experience.
> fix(panes): when focusing pane off the tab edge, break ties with active_at instead of y

- CHANGELOG.md
- zellij-server/src/panes/tiled_panes/mod.rs
- zellij-server/src/panes/tiled_panes/stacked_panes.rs
This fixes various issues that happened when combining multiplayer and stacked panes. Namely having to do with the stack focus moving for all clients if only one client moves focus for it.
> fix(panes): multiplayer stack issues

- zellij-server/src/plugins/plugin_loader.rs
This is a fix for an issue where if one would run a development instance of Zellij that shared cache with a release instance, plugins would sometimes be paged from the HD, causing segfaults. More info here: https://github.com/bytecodealliance/wasmtime/issues/10283#issuecomment-2692084111
> fix(plugins): prevent paging plugins from cache at runtime

- zellij-server/src/panes/grid.rs
This fixes a minor issue where some apps using scroll region rotate would try to clear the scroll region bounds before they updated them to the terminal window size (eg. after a resize). While this is an error on the app side (I think it comes from ncurses), we should be able to handle this without crashing. This fixes that!
> fix(grid): out of bounds removal when app does not update its scroll region on resize

- default-plugins/status-bar/src/one_line_ui.rs
This adds the `Split Right` and `Split Down` shortcuts (by default `r` and `d` in `PANE` mode) to the status-bar display. This is important as they will be more widely used with the new `stacked resize` feature, since they can also now split stacks (eg. one can split a full-screen stack to the right in order to make it take up half the screen and create a multiple-select).
> fix(ui): add split right/down shortcut hints to the status-bar

- default-plugins/about/src/tips.rs
- src/tests/e2e/cases.rs
- zellij-server/src/panes/tiled_panes/pane_resizer.rs
- zellij-server/src/panes/tiled_panes/stacked_panes.rs
- zellij-utils/src/input/layout.rs
Fixed a number of other typos and issues I came across, but the last commit is the one that actually solves the resize issue!
There is another experiment on `tll-pane-resizer-with-stackinfo` for the future when we have <N panes above / below>
I might need @imsnif's help to write a test if one is wanted!
> fix(stacked): stacked panes can't resize status-bar

- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/selection.rs
- zellij-server/src/panes/unit/selection_tests.rs
This fixes some issues with the new multiple-mouse-click feature for marking word/line boundaries on double-triple click. Namely, the selection is now properly taken into account on mouse drag in these scenarios.
> fix(selection): add proper multi-click dragging options

- CHANGELOG.md
- default-plugins/about/src/pages.rs
- default-plugins/about/src/tips.rs
Hey @imsnif,
in preparation for the next release I had a glance at the startup tips and feature highlights (nice job, btw). I noticed some minor "bugs" so here are the fixes for that (see first two commits).
While reading through the tips in the "about" plugin I also noticed that keybindings aren't formatted nor painted consistently. Before I go about fixing that I wanted to know: Was that a deliberate choice, or may I go ahead and bring them in line with how we format keys in e.g. the status-bar plugin?
> Styling fixes in the "about" plugin 

- CHANGELOG.md
- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__full_screen_scroll_region_and_scroll_up.snap
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__move_cursor_below_scroll_region.snap
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__vim_scroll_region_down.snap
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__vttest1_2.snap
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__vttest1_3.snap
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__vttest2_6.snap
- zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__vttest2_8.snap
This is a long overdue refactor to the terminal code to keep track of the scroll_region as a tuple rather than an `Option`.
The only functional change is that the scroll region lines are not explicitly padded now (which they shouldn't really have been in the first place).
> refactor(terminal): log scroll region as tuple rather than Option<tuple>

- CHANGELOG.md
- Cargo.toml
- xtask/Cargo.toml
- zellij-client/Cargo.toml
- zellij-server/Cargo.toml
- zellij-tile-utils/Cargo.toml
- zellij-tile/Cargo.toml
- zellij-utils/Cargo.toml
and deduplicate dependency entries across all non-plugin workspace members. In the future this hopefully makes dependency upgrade easier since shared dependencies need only be touched in one location.
> chore: Introduce workspace dependencies

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- xtask/Cargo.toml
- zellij-client/Cargo.toml
- zellij-server/Cargo.toml
- zellij-server/src/logging_pipe.rs
- zellij-utils/Cargo.toml
- zellij-utils/src/consts.rs
but instead specify all the dependency features we need/want explicitly. This cuts down the number of dependencies in the compilation from 587 to 565 and also makes our code more robust against unexpected changes in upstream default features.
> build: Don't use default features

- CHANGELOG.md
- zellij-server/src/background_jobs.rs
- zellij-server/src/output/mod.rs
- zellij-server/src/screen.rs
- zellij-server/src/terminal_bytes.rs
- zellij-utils/src/errors.rs
This improves the overall rendering performance of the tool (greatly mitigating various "flickering" issues caused in applications that do not perform synchronized renders) by consolidating renders to the `Screen` thread and introducing an async repaint_delay of 10ms.
> performance(render): improve rendering performance by consolidating renders and introducing repaint_delay

- Cargo.lock
Noticed when rebuilding 0.42.1 for rust 1.86.
The cause is https://github.com/bytecodealliance/wasmtime/issues/10184, and the fix is updating the `wit-parser` dependency to 0.221.3
> fix(deps): fix --locked build on rust 1.86

- zellij-utils/src/lib.rs
until shortly before the next minor release, just to make sure that subsequent patch releases don't unexpectedly break downstream consumers code.
Originally introduced via 6be8c495 (#4087).
> fix(utils): Re-export prost

- CHANGELOG.md
- zellij-server/src/panes/grid.rs
- zellij-server/src/panes/hyperlink_tracker.rs
- zellij-server/src/panes/link_handler.rs
- zellij-server/src/panes/mod.rs
This adds built-in support for hyperlinks that span across multiple line-wraps. It works by detecting URL patterns while parsing ANSI instructions and then surrounding each wrapped line segment in an OSC8 link instruction that leads to the full link. The segments are given the same OSC8 id, so that the terminal will highlight all segments if the mouse hovers over one of them.
As with all links, if mouse_support in Zellij is enabled, one must hold the SHIFT key to click on the link (and to get it highlighted when hovering over it). Without mouse_mode, they still "just work".
> feat(terminal): multiline hyperlink support

- CHANGELOG.md
- zellij-server/src/background_jobs.rs
- zellij-server/src/lib.rs
- zellij-server/src/os_input_output.rs
- zellij-server/src/pty.rs
- zellij-server/src/screen.rs
- zellij-server/src/session_layout_metadata.rs
- zellij-utils/assets/config/default.kdl
- zellij-utils/src/errors.rs
- zellij-utils/src/input/options.rs
- zellij-utils/src/kdl/mod.rs
- zellij-utils/src/kdl/snapshots/zellij_utils__kdl__bare_config_from_default_assets_to_string_with_comments.snap
- zellij-utils/src/kdl/snapshots/zellij_utils__kdl__config_options_to_string_with_comments.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__cli_arguments_override_config_options.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__cli_arguments_override_layout_options.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__default_config_with_no_cli_arguments-3.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__default_config_with_no_cli_arguments.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_env_vars_override_config_env_vars.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_keybinds_override_config_keybinds.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_options_override_config_options.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_themes_override_config_themes.snap
- zellij-utils/src/snapshots/zellij_utils__setup__setup_test__layout_ui_config_overrides_config_ui_config.snap
This PR issues some fixes for session serialization - used in order to resurrect sessions after they have exited.
This includes two things:
1. We no longer serialize sessions which only include UI elements on top of the base layout (eg. the `about` plugin with startup tips)
2. We not provide a `post_command_discovery_hook`, which will run if present after Zellij discovers a command running inside one of its panes. This hook will be provided the discovered command as a `RESURRECT_COMMAND` environment variable, and is expected to edit the command and send it back through STDOUT. This might be useful for stripping wrappers off commands (eg. for NixOS).
Example: `post_command_discovery_hook "echo \"$RESURRECT_COMMAND\" | sed 's/^sudo\\s\\+//'" // strip sudo from commands`
> fix(serialization): don't serialize when only UI elements present and provide post command discovery hook

- CHANGELOG.md
- default-plugins/compact-bar/src/tab.rs
- src/tests/e2e/cases.rs
This fixes an issue with the compact bar that happened after some refactoring. When multiple users are connected, it calculated the length wrong (ignoring the square brackets), causing the bar to add extra padding that messed up the rendering.
This also attempts to fix some flakiness in our e2e tests (unrelated).
> fix(compact-bar): fix cursor length calculation for multiple users

- CHANGELOG.md
- zellij-client/src/web_client/ipc_listener.rs
- zellij-client/src/web_client/mod.rs
- zellij-client/src/web_client/server_listener.rs
This fixes an issue in the yet-to-be-released web server where we would watch the config again for each connection (and not clean up the watcher on disconnect!) - causing a thread leak. While this did not really affect CPU/memory since all the threads were waiting, it's still not an ideal situation.
To fix, I removed the extra watcher and merged the client/server config change notifications.
> fix(web-server): thread leak due to excess file watching

- zellij-server/src/os_input_output.rs
- zellij-server/src/pty.rs
Add cmd from sysinfo in terminal_ids_to_commands if no cmd are return by ps. So then, cmd and cwd are udpated in "session-layout.kdl" even if no cmd is runing in pane.
Fix related issue : #2978, #3041, #3374, #4023
> fix: populate layout metadata with the right cmd and cwd

- zellij-client/assets/input.js
Previously we interpreted ctrl-shift-v and sent it to the terminal, now an exception was added so that it will be instead interpreted by xterm.js and do the right thing.
> fix(web): allow pasting with ctrl-shift-v

- CHANGELOG.md
- src/tests/e2e/cases.rs
- zellij-server/src/panes/grid.rs
This is a fix for https://github.com/zellij-org/zellij/issues/4162 - in which when we double-click a word which has an emoji *before* it, the marking would not account for wide characters.
When I implemented this feature, I accounted for wide characters inside the clicked word, but I forgot to account for wide characters before the word (oops!)
This remedies the situation.
> fix(grid): account for wide characters when double-triple mouse clicking

- CHANGELOG.md
- zellij-client/src/input_handler.rs
- zellij-server/src/panes/mod.rs
- zellij-server/src/screen.rs
- zellij-server/src/tab/mod.rs
- zellij-utils/src/shared.rs
This fixes several issues:
1. It is now possible to paste strings into the search, when renaming tabs and when renaming panes
2. It is now possible to have tab names and pane names that include wide characters (eg. emojis)*
*it is unfortunately still not possible to search for emojis, because the search is not wide-char aware - something I'd be happy to fix given the chance!
> fix(ux): allow pasting and inputing wide-chars in search + tab rename + pane rename

- default-plugins/compact-bar/src/action_types.rs
- default-plugins/compact-bar/src/keybind_utils.rs
- default-plugins/compact-bar/src/main.rs
This fixes a few issues with the new tooltip functionality of the compact-bar:
1. We now use the proper configuration when for the keybind toggle (so as not to launch the compact-bar a second time)
2. We now only send the tooltip toggle once (based on the focused tab) to prevent double opening of the tooltip in multiple tabs (we move the tooltip to the active tab anyway)
3. The new "new stacked pane" action has been added to pane mode
> fix(compact-bar): tooltip duplication

- default-plugins/compact-bar/src/main.rs
- default-plugins/multiple-select/src/main.rs
- zellij-server/src/pane_groups.rs
- zellij-server/src/panes/grid.rs
- zellij-server/src/plugins/zellij_exports.rs
- zellij-server/src/screen.rs
- zellij-tile/src/shim.rs
- zellij-utils/assets/prost/api.plugin_command.rs
- zellij-utils/src/data.rs
- zellij-utils/src/plugin_api/plugin_command.proto
- zellij-utils/src/plugin_api/plugin_command.rs
This fixes some issues in the new multiple select plugin and new compact-bar tooltip with regards to multiplayer usage. Namely we make sure to only toggle UI elements once per connected user and plugin instance.
This also fixes some problems when stacking panes through the multiple-select plugins if the root pane is floating.
> fix(plugins): multiple-select + compact-bar tooltip multiplayer issues

- zellij-server/src/panes/grid.rs
This PR dramatically improves the `dump_screen!` macro performance. 
First of all, I love the editing scrollback feature!
I was playing around with `scroll_buffer_size` setting. I tried setting it to 1,000,000.
I executed `yes` to fill up the screen buffer and then tried to edit the scrollback.
There was a big delay from issuing the command to editing in my editor.
So I tried to figure out what causing this delay. "1 million lines shouldn't be too big?", I thought.
* Pre-allocates `buf` string.
* Uses `trim_end_matches()` instead of using regex.
I wrote a simple benchmark [here](https://gist.github.com/zynaxsoft/c26f9e2e08be2d5315203e172596d5ab), simulating what I experienced.
```
Result
Old method: 7.55s
New method: 16.72ms
```
> performance(server): greatly improve dump_screen! performance

- src/commands.rs
- src/main.rs
- zellij-client/src/web_client/mod.rs
- zellij-utils/src/cli.rs
Previously it was only possible to specify these through the config, now it's also possible to specify them through the cli.
> feat(web): allow specifying ip/port/cert/key through the cli

- zellij-client/src/web_client/utils.rs
Thanks for the feature, I was testing it locally and on a server and I started having problems.
I was experiencing an issue with authorization when accessing my server, but not my local instance. The `/login` request was passing with `200` but the `/session` request was returning `401`. This was caused by the fact that for a request with a cookie header containing multiple cookies like:
```
Cookie: a=x; b=x; c=x; session_token=xxxx
```
the call to `request.headers().get("cookie")` only returned `a=x`. That's why changing it to `get_all` solves the problem.
Now the reason is still unknown to my as to why is Axum doing this. I tried removing the `cookie` feature but it was still happening. I tried sending the exact same request locally with curl and the exact same headers and it was not …
> fix(web_server): Handle extracting session_token from multiple cookies

- zellij-client/assets/input.js
- zellij-client/assets/terminal.js
Always focus the terminal during init instead of on a mouse event.
> fix(web): focus terminal on init

- zellij-client/src/web_client/authentication.rs
- zellij-client/src/web_client/http_handlers.rs
- zellij-client/src/web_client/mod.rs
- zellij-client/src/web_client/types.rs
Previously, we would set the `secure` cookie flag (meaning the cookie should only be sent on https connections) to our session_token cookie whether we were on http or https. Most browsers have a "localhost exception" for this, meaning they send secure cookies on non-https connections so long as they are to localhost. Safari does not have this exception, so users were unable to log-in before they set an https certificate.
This fixes the issue by conditionally setting the `secure` flag depending on whether the connection is https or not. Since the web client does not perform any http (or indeed, any remote) requests other than to the server, this is not considered risky.
> fix(web): set secure cookie flag only for https

- zellij-utils/src/shared.rs
The session name was removed from the terminal title on certain conditions (honestly, I thought this was a good idea - I was wrong!) - this fixes it.
> fix: terminal title should include session name

- zellij-utils/src/sessions.rs
Fixes a regression where `zellij ls` would list dead sessions as resurrectable even if they were not.
> fix(list): do not list sessions as resurrectable unless they are

- CHANGELOG.md
- zellij-client/assets/index.js
Minor adjustment so that the tab name would be the same as the session name initially, rather than "Zellij Web Client".
> fix(web): use session name as initial document title

- CHANGELOG.md
- zellij-client/assets/input.js
- zellij-client/src/web_client/mod.rs
- extend the logic already used to skip single modifier key presses to meta
- refactor: extract the code into a function, make it simpler and use event.key instead of deprecated event.keyCode
- cleanup leftover axum cors config from feature development
Fix #4359
> fix(web): avoid sending single meta keypresses, cleanup

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/commands.rs
- zellij-client/Cargo.toml
- zellij-client/src/lib.rs
- zellij-client/src/os_input_output.rs
- zellij-client/src/remote_attach/auth.rs
- zellij-client/src/remote_attach/config.rs
- zellij-client/src/remote_attach/http_client.rs
- zellij-client/src/remote_attach/mod.rs
- zellij-client/src/remote_attach/unit/mod.rs
- zellij-client/src/remote_attach/unit/remote_attach_tests.rs
- zellij-client/src/remote_attach/websockets.rs
- zellij-client/src/unit/mod.rs
- zellij-client/src/unit/terminal_loop_tests.rs
- zellij-client/src/web_client/control_message.rs
- zellij-client/src/web_client/mod.rs
- zellij-client/src/web_client/websocket_handlers.rs
- zellij-server/src/lib.rs
- zellij-utils/src/cli.rs
- zellij-utils/src/errors.rs
- zellij-utils/src/lib.rs
- zellij-utils/src/remote_session_tokens.rs
This adds built-in remote attach capabilities to Zellij*, allowing users to attach to a remote Zellij session that has a running web-server over https, for example:
```
$ zellij attach https://example.com/my-cool-session
Enter authentication token: <hidden>
```
Once attached, this works exactly like the web-client. Users see the same terminal as those active in the session (if there are any), receive their own unique cursor, etc. The only difference is that this works through the terminal rather than the browser. For more info: https://zellij.dev/tutorials/web-client/
The connection is established over https, using the same token authentication as the browser. It's possible to save the session-token (received from the server in exchange for the real token) in an SQLite database accessible …
> New Feature: remote attach to a Zellij session from the terminal
